import { registerLabels } from '@/lib/labels';

/** English labels for metrics, analytics and report enums (spec §15–§17, §31.2). */
registerLabels({
  metricStatus: {
    known: 'Known',
    partial: 'Partial',
    no_data: 'No data',
    not_defined: 'Not Defined',
    not_enough_data: 'Not Enough Data',
    not_measured: 'Not Measured',
    not_attributable: 'Not Attributable',
    pending: 'Pending',
    not_applicable: 'Not Applicable',
    not_comparable: 'Not Comparable',
  },
  valueAvailability: { known: 'Known', unknown: 'Unknown', not_provided: 'Not Provided', not_applicable: 'Not Applicable' },
  observationKind: { snapshot: 'Snapshot', period: 'Period', cumulative: 'Cumulative' },
  metricEntityType: { account: 'Account', publication: 'Publication', ofm_account: 'OFM Account' },
  metricSourceType: { manual: 'Manually recorded', csv: 'CSV import', external_report: 'External report' },
  metricQuality: { unverified: 'Unverified', reviewed: 'Reviewed source record', superseded: 'Superseded', pending_correction: 'Correction pending', rejected: 'Rejected' },
  metricSegment: { unknown: 'Total (unspecified)', organic: 'Organic', paid: 'Paid', combined: 'Combined total' },
  checkpointStatus: { upcoming: 'Upcoming', due: 'Due', overdue: 'Overdue', completed: 'Submitted', missing: 'Missing', cancelled: 'Cancelled' },
  checkpointTiming: { on_time: 'On Time', early: 'Early', late: 'Late' },
  observationDataset: { account_snapshot: 'Account snapshot', account_period: 'Account period results', publication_cumulative: 'Publication results', ofm_period: 'OFM period results' },
  analyticsTab: { production: 'Production', accounts: 'Accounts', content: 'Content', ofm: 'OFM', team: 'Team', finance: 'Finance' },
  periodPreset: {
    today: 'Today',
    last_7_days: 'Last 7 days',
    last_30_days: 'Last 30 days',
    last_90_days: 'Last 90 days',
    this_week: 'This week',
    last_week: 'Last week',
    this_month: 'This month',
    last_month: 'Last month',
    this_quarter: 'This quarter',
    last_quarter: 'Last quarter',
    this_year: 'This year',
    custom: 'Custom',
  },
  timeGrain: { day: 'Day', week: 'Week', month: 'Month', quarter: 'Quarter' },
  reportDataset: { tasks: 'Tasks & Time', content: 'Content Production', publications: 'Publications & Results', account_metrics: 'Account Metrics', ofm: 'OFM Operations', finance: 'Finance' },
  reportChart: { table: 'Table', line: 'Line', bar: 'Bar', stacked_bar: 'Stacked bar' },
  reportCadence: { daily: 'Daily', weekly: 'Weekly (Monday)', monthly: 'Monthly (1st)' },
  reportSharing: { private: 'Private', shared: 'Shared' },
  scheduleStatus: { active: 'Active', paused: 'Paused', paused_needs_owner: 'Paused — Needs Owner' },
  metricWarning: {
    REACH_ABOVE_IMPRESSIONS: 'Reach above impressions',
    COMPLETIONS_ABOVE_VIEWS: 'Completions above views',
    CUMULATIVE_DECREASE: 'Lower than an earlier total',
    PERIOD_OVERLAP: 'Overlapping period',
    ALTERNATE_SOURCE: 'Alternate source',
    CHECKPOINT_LATE: 'Recorded outside the target window',
    CHECKPOINT_EARLY: 'Recorded outside the target window',
  },
});
