import { z } from 'zod';
import { LIMITS, MEMBERSHIP_STATUSES, SCOPE_TYPES, SETUP_STEPS, THEMES, DENSITIES } from '@castlane/domain';
import { endpoint } from './core';
import { isoDateTime, okResponse, timezone, uuid, currencyCode, shortName } from './common';

const email = z.string().trim().email().max(254);
const password = z.string().min(LIMITS.passwordMin).max(LIMITS.passwordMax);
const anyPassword = z.string().min(1).max(LIMITS.passwordMax);
const totp = z.string().trim().regex(/^\d{6}$/, 'Enter the 6-digit code.');

export const workspaceSummary = z.object({
  id: uuid,
  name: z.string(),
  timezone: z.string(),
  baseCurrency: z.string(),
  setupStep: z.enum(SETUP_STEPS),
  membershipId: uuid,
  membershipStatus: z.enum(MEMBERSHIP_STATUSES),
  logoUrl: z.string().nullable(),
});

export const sessionUser = z.object({
  id: uuid,
  email: z.string(),
  displayName: z.string(),
  avatarUrl: z.string().nullable(),
  mfaEnabled: z.boolean(),
  mustChangePassword: z.boolean(),
  timezone: z.string().nullable(),
  theme: z.enum(THEMES),
  density: z.enum(DENSITIES),
});

export const meResponse = z.object({
  user: sessionUser,
  workspaces: z.array(workspaceSummary),
  currentWorkspaceId: uuid.nullable(),
  mfaVerified: z.boolean(),
  mfaRequired: z.boolean(),
  csrfToken: z.string(),
});
export type MeResponse = z.infer<typeof meResponse>;

const signInResult = z.discriminatedUnion('status', [
  z.object({ status: z.literal('signed_in'), redirectTo: z.string() }),
  z.object({ status: z.literal('mfa_required'), challengeId: z.string() }),
  z.object({ status: z.literal('mfa_setup_required'), challengeId: z.string() }),
]);

export const authEndpoints = {
  csrf: endpoint({
    id: 'auth.csrf',
    method: 'GET',
    path: '/auth/csrf',
    summary: 'Issue a pre-session CSRF token (double-submit cookie).',
    tags: ['Auth'],
    auth: 'public',
    response: z.object({ csrfToken: z.string() }),
    rateLimit: 'auth',
  }),
  signIn: endpoint({
    id: 'auth.signIn',
    method: 'POST',
    path: '/auth/sign-in',
    summary: 'Sign in with e-mail and password.',
    tags: ['Auth'],
    auth: 'public',
    body: z.object({ email, password: anyPassword, returnTo: z.string().max(500).optional() }),
    response: signInResult,
    rateLimit: 'auth',
    errors: ['UNAUTHENTICATED', 'RATE_LIMITED'],
  }),
  mfaVerify: endpoint({
    id: 'auth.mfaVerify',
    method: 'POST',
    path: '/auth/mfa/verify',
    summary: 'Complete sign-in with a TOTP or recovery code.',
    tags: ['Auth'],
    auth: 'public',
    body: z.object({
      challengeId: z.string().min(10).max(200),
      code: z.string().trim().min(6).max(32),
      kind: z.enum(['totp', 'recovery']).default('totp'),
    }),
    response: z.object({ redirectTo: z.string() }),
    rateLimit: 'auth',
  }),
  mfaSetupStart: endpoint({
    id: 'auth.mfaSetupStart',
    method: 'POST',
    path: '/auth/mfa/setup',
    summary: 'Start TOTP setup (from a setup challenge or a recently authenticated session).',
    tags: ['Auth'],
    auth: 'public',
    body: z.object({ challengeId: z.string().min(10).max(200).optional() }),
    response: z.object({ challengeId: z.string(), otpauthUrl: z.string(), secret: z.string(), qrSvg: z.string() }),
    rateLimit: 'auth',
  }),
  mfaSetupConfirm: endpoint({
    id: 'auth.mfaSetupConfirm',
    method: 'POST',
    path: '/auth/mfa/setup/confirm',
    summary: 'Confirm TOTP setup with a valid code; returns recovery codes once.',
    tags: ['Auth'],
    auth: 'public',
    body: z.object({ challengeId: z.string().min(10).max(200), code: totp }),
    response: z.object({ recoveryCodes: z.array(z.string()), redirectTo: z.string() }),
    rateLimit: 'auth',
  }),
  recovery: endpoint({
    id: 'auth.recovery',
    method: 'POST',
    path: '/auth/recovery',
    summary: 'Request a password reset link (response never reveals whether the account exists).',
    tags: ['Auth'],
    auth: 'public',
    body: z.object({ email }),
    response: z.object({ accepted: z.literal(true), message: z.string() }),
    rateLimit: 'auth',
  }),
  reset: endpoint({
    id: 'auth.reset',
    method: 'POST',
    path: '/auth/reset',
    summary: 'Reset the password with a one-time token; revokes all sessions.',
    tags: ['Auth'],
    auth: 'public',
    body: z.object({ token: z.string().min(20).max(200), newPassword: password }),
    response: okResponse,
    rateLimit: 'auth',
  }),
  signOut: endpoint({
    id: 'auth.signOut',
    method: 'POST',
    path: '/auth/sign-out',
    summary: 'Revoke the current session.',
    tags: ['Auth'],
    auth: 'session',
    allowWithoutMfa: true,
    response: okResponse,
  }),
  me: endpoint({
    id: 'auth.me',
    method: 'GET',
    path: '/auth/me',
    summary: 'Current user, workspaces and CSRF token.',
    tags: ['Auth'],
    auth: 'session',
    allowWithoutMfa: true,
    response: meResponse,
  }),
  reauthenticate: endpoint({
    id: 'auth.reauthenticate',
    method: 'POST',
    path: '/auth/reauthenticate',
    summary: 'Confirm password (and TOTP when enabled) for critical actions (recent authentication).',
    tags: ['Auth'],
    auth: 'session',
    allowWithoutMfa: true,
    body: z.object({ password: anyPassword, code: totp.optional() }),
    response: z.object({ recentAuthAt: isoDateTime }),
    rateLimit: 'auth',
  }),
  changePassword: endpoint({
    id: 'auth.changePassword',
    method: 'POST',
    path: '/auth/password',
    summary: 'Change own password; other sessions are revoked.',
    tags: ['Auth'],
    auth: 'session',
    allowWithoutMfa: true,
    body: z.object({ currentPassword: anyPassword, newPassword: password }),
    response: okResponse,
    rateLimit: 'auth',
  }),
  sessions: endpoint({
    id: 'auth.sessions',
    method: 'GET',
    path: '/auth/sessions',
    summary: 'List own active sessions.',
    tags: ['Auth'],
    auth: 'session',
    response: z.array(
      z.object({ id: uuid, current: z.boolean(), createdAt: isoDateTime, lastSeenAt: isoDateTime, userAgent: z.string().nullable() }),
    ),
  }),
  revokeSession: endpoint({
    id: 'auth.revokeSession',
    method: 'POST',
    path: '/auth/sessions/{sessionId}/revoke',
    summary: 'Revoke one of own sessions.',
    tags: ['Auth'],
    auth: 'session',
    params: z.object({ sessionId: uuid }),
    response: okResponse,
  }),
  revokeOtherSessions: endpoint({
    id: 'auth.revokeOtherSessions',
    method: 'POST',
    path: '/auth/sessions/revoke-others',
    summary: 'Sign out all other sessions.',
    tags: ['Auth'],
    auth: 'session',
    response: z.object({ revoked: z.number().int() }),
  }),
  regenerateRecoveryCodes: endpoint({
    id: 'auth.regenerateRecoveryCodes',
    method: 'POST',
    path: '/auth/mfa/recovery-codes',
    summary: 'Regenerate recovery codes (recent authentication required). Old codes stop working.',
    tags: ['Auth'],
    auth: 'session',
    response: z.object({ recoveryCodes: z.array(z.string()) }),
  }),
  invitationInfo: endpoint({
    id: 'auth.invitationInfo',
    method: 'GET',
    path: '/auth/invitations/{token}',
    summary: 'Describe an invitation (workspace and e-mail only; closed projects are not revealed).',
    tags: ['Auth'],
    auth: 'public',
    params: z.object({ token: z.string().min(20).max(200) }),
    response: z.object({
      status: z.enum(['valid', 'expired', 'revoked', 'accepted']),
      workspaceName: z.string().nullable(),
      email: z.string().nullable(),
      existingAccount: z.boolean(),
      accessSummary: z.array(z.string()),
      invitationId: uuid.nullable(),
    }),
    rateLimit: 'auth',
  }),
  acceptInvitation: endpoint({
    id: 'auth.acceptInvitation',
    method: 'POST',
    path: '/auth/invitations/accept',
    summary: 'Accept an invitation: new account (display name + password) or existing account (password).',
    tags: ['Auth'],
    auth: 'public',
    body: z.object({
      token: z.string().min(20).max(200),
      displayName: z.string().trim().min(LIMITS.displayNameMin).max(LIMITS.displayNameMax).optional(),
      password: anyPassword,
    }),
    response: z.discriminatedUnion('status', [
      z.object({ status: z.literal('signed_in'), redirectTo: z.string() }),
      z.object({ status: z.literal('mfa_setup_required'), challengeId: z.string() }),
      z.object({ status: z.literal('mfa_required'), challengeId: z.string() }),
    ]),
    rateLimit: 'auth',
  }),
  requestNewInvitation: endpoint({
    id: 'auth.requestNewInvitation',
    method: 'POST',
    path: '/auth/invitations/request-new',
    summary: 'Ask the workspace administrators for a new invitation after expiry.',
    tags: ['Auth'],
    auth: 'public',
    body: z.object({ token: z.string().min(20).max(200) }),
    response: z.object({ accepted: z.literal(true) }),
    rateLimit: 'auth',
  }),
  switchWorkspace: endpoint({
    id: 'auth.switchWorkspace',
    method: 'POST',
    path: '/auth/workspace',
    summary: 'Set the current workspace of the session.',
    tags: ['Auth'],
    auth: 'session',
    body: z.object({ workspaceId: uuid }),
    response: okResponse,
  }),
};

export const setupEndpoints = {
  progress: endpoint({
    id: 'setup.progress',
    method: 'GET',
    path: '/workspaces/{workspaceId}/setup',
    summary: 'Workspace setup progress (Owner only).',
    tags: ['Setup'],
    auth: 'workspace',
    permission: 'workspace.update',
    params: z.object({ workspaceId: uuid }),
    response: z.object({
      step: z.enum(SETUP_STEPS),
      workspace: z.object({
        name: z.string(),
        timezone: z.string(),
        baseCurrency: z.string(),
        weekStartsOn: z.enum(['monday', 'sunday']),
        baseCurrencyLocked: z.boolean(),
        rowVersion: z.number().int(),
      }),
      directions: z.array(z.object({ id: uuid, name: z.string(), leadMembershipId: uuid.nullable(), presetKind: z.string().nullable() })),
      roles: z.array(z.object({ id: uuid, key: z.string(), name: z.string(), defaultScopeType: z.enum(SCOPE_TYPES), permissions: z.array(z.string()) })),
      members: z.array(z.object({ id: uuid, displayName: z.string() })),
    }),
  }),
  saveWorkspace: endpoint({
    id: 'setup.saveWorkspace',
    method: 'POST',
    path: '/workspaces/{workspaceId}/setup/workspace',
    summary: 'Setup step 1: name, timezone, base currency, week start.',
    tags: ['Setup'],
    auth: 'workspace',
    permission: 'workspace.update',
    idempotent: true,
    params: z.object({ workspaceId: uuid }),
    body: z.object({
      name: z.string().trim().min(2).max(80),
      timezone,
      baseCurrency: currencyCode,
      weekStartsOn: z.enum(['monday', 'sunday']).default('monday'),
    }),
    response: z.object({ step: z.enum(SETUP_STEPS) }),
  }),
  saveDirections: endpoint({
    id: 'setup.saveDirections',
    method: 'POST',
    path: '/workspaces/{workspaceId}/setup/directions',
    summary: 'Setup step 2: create/rename directions (at least one).',
    tags: ['Setup'],
    auth: 'workspace',
    permission: 'directions.manage',
    idempotent: true,
    params: z.object({ workspaceId: uuid }),
    body: z.object({
      directions: z
        .array(z.object({ id: uuid.optional(), name: shortName, leadMembershipId: uuid.nullable().optional(), presetKind: z.enum(['series', 'model', 'influencer']).nullable().optional() }))
        .min(1)
        .max(20),
    }),
    response: z.object({ step: z.enum(SETUP_STEPS) }),
  }),
  inviteTeam: endpoint({
    id: 'setup.inviteTeam',
    method: 'POST',
    path: '/workspaces/{workspaceId}/setup/team',
    summary: 'Setup step 3: invite up to 20 people, or finish without invitations.',
    tags: ['Setup'],
    auth: 'workspace',
    permission: 'members.invite',
    idempotent: true,
    params: z.object({ workspaceId: uuid }),
    body: z.object({
      invitations: z
        .array(z.object({ email: z.string().trim().email().max(254), roleId: uuid, scopeType: z.enum(SCOPE_TYPES), scopeId: uuid.nullable() }))
        .max(20),
      finish: z.boolean(),
    }),
    response: z.object({
      step: z.enum(SETUP_STEPS),
      results: z.array(
        z.object({ email: z.string(), outcome: z.enum(['queued', 'resent', 'already_member', 'invalid_role', 'invalid_scope']), invitationId: uuid.nullable() }),
      ),
    }),
  }),
};
