import { z } from 'zod';
import { CHARACTER_VERSION_STATES, CONTENT_FORMATS, CONTENT_STAGES, LIMITS, PROJECT_TYPES, REFERENCE_TAGS } from '@castlane/domain';
import { endpoint } from './core';
import { boolQuery, csv, isoDateTime, memberRef, okResponse, page, pageQuery, reason, shortName, uuid, wsId } from './common';

/**
 * Creative structure: characters and their versioned profiles (S16), series seasons / episodes /
 * scenes (S17) and references (S21).
 */

// ——— Characters (S16) ———

const longText = z.string().max(LIMITS.noteMax);

export const characterProfile = z.object({
  fictionalIdentityNote: longText.optional(),
  adultAgeDeclaration: z.object({ declared: z.boolean(), statedAge: z.number().int().min(18).max(120).optional() }).optional(),
  appearance: longText.optional(),
  voice: longText.optional(),
  personality: longText.optional(),
  tone: longText.optional(),
  allowedVariation: longText.optional(),
  biography: longText.optional(),
  audience: longText.optional(),
  styleConstraints: longText.optional(),
  toolsSettings: longText.optional(),
});
export type CharacterProfileInput = z.infer<typeof characterProfile>;

export const characterPrompt = z.object({
  title: z.string().trim().min(1).max(120),
  text: z.string().trim().min(1).max(LIMITS.noteMax),
  tool: z.string().trim().max(80).optional(),
});

export const MAX_CHARACTER_REFERENCES = 12;

export const characterReference = z.object({
  assetId: uuid,
  assetVersionId: uuid,
  name: z.string(),
  status: z.string(),
  thumbnailUrl: z.string().nullable(),
});

export const characterVersionView = z.object({
  id: uuid,
  characterId: uuid,
  versionNo: z.number().int(),
  state: z.enum(CHARACTER_VERSION_STATES),
  profile: characterProfile,
  prompts: z.array(characterPrompt),
  references: z.array(characterReference),
  changeNote: z.string().nullable(),
  submittedAt: isoDateTime.nullable(),
  approvedAt: isoDateTime.nullable(),
  approvedBy: memberRef.nullable(),
  pendingReview: z.object({ id: uuid, reviewer: memberRef.nullable(), author: memberRef.nullable(), submittedAt: isoDateTime }).nullable(),
  lastDecision: z.object({ decision: z.string(), summary: z.string().nullable(), decidedAt: isoDateTime, decidedBy: memberRef.nullable() }).nullable(),
  createdAt: isoDateTime,
  rowVersion: z.number().int(),
});
export type CharacterVersionView = z.infer<typeof characterVersionView>;

export const characterSummary = z.object({
  id: uuid,
  projectId: uuid,
  name: z.string(),
  role: z.string().nullable(),
  isPrimary: z.boolean(),
  approvedVersion: z.object({ id: uuid, versionNo: z.number().int(), approvedAt: isoDateTime.nullable() }).nullable(),
  openVersion: z.object({ id: uuid, versionNo: z.number().int(), state: z.enum(CHARACTER_VERSION_STATES) }).nullable(),
  thumbnailUrl: z.string().nullable(),
  referenceCount: z.number().int(),
  archivedAt: isoDateTime.nullable(),
  updatedAt: isoDateTime,
  rowVersion: z.number().int(),
});
export type CharacterSummary = z.infer<typeof characterSummary>;

export const characterDetail = characterSummary.extend({
  project: z.object({ id: uuid, name: z.string(), type: z.enum(PROJECT_TYPES), ofmEnabled: z.boolean() }),
  versions: z.array(z.object({ id: uuid, versionNo: z.number().int(), state: z.enum(CHARACTER_VERSION_STATES), changeNote: z.string().nullable(), approvedAt: isoDateTime.nullable(), createdAt: isoDateTime })),
  /** The open draft/submitted version, if any. */
  open: characterVersionView.nullable(),
  approved: characterVersionView.nullable(),
  /** Content items flagged Needs Consistency Review after a newer profile was approved. */
  flaggedContentCount: z.number().int(),
  permissions: z.object({ write: z.boolean(), approve: z.boolean(), archive: z.boolean(), setPrimary: z.boolean(), uploadReferences: z.boolean() }),
});
export type CharacterDetail = z.infer<typeof characterDetail>;

export const affectedContentItem = z.object({
  id: uuid,
  title: z.string(),
  stage: z.enum(CONTENT_STAGES),
  format: z.enum(CONTENT_FORMATS),
  needsConsistencyReview: z.boolean(),
  characterVersionNo: z.number().int(),
  updatedAt: isoDateTime,
});

const characterVersionPatch = z.object({
  profile: characterProfile.optional(),
  prompts: z.array(characterPrompt).max(50).optional(),
  referenceAssetVersionIds: z.array(uuid).max(MAX_CHARACTER_REFERENCES).optional(),
  changeNote: z.string().trim().max(2000).nullable().optional(),
});

export const characterEndpoints = {
  list: endpoint({
    id: 'characters.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/projects/{projectId}/characters',
    summary: 'Characters of a project with their approved and open profile versions.',
    tags: ['Characters'],
    auth: 'workspace',
    permission: 'characters.read',
    params: wsId({ projectId: uuid }),
    query: z.object({ includeArchived: boolQuery.optional() }),
    response: z.array(characterSummary),
  }),
  create: endpoint({
    id: 'characters.create',
    method: 'POST',
    path: '/workspaces/{workspaceId}/projects/{projectId}/characters',
    summary: 'Create a character with a first draft profile version.',
    tags: ['Characters'],
    auth: 'workspace',
    permission: 'characters.write',
    idempotent: true,
    params: wsId({ projectId: uuid }),
    body: z.object({ name: shortName, role: z.string().trim().max(120).nullable().optional(), isPrimary: z.boolean().optional() }).merge(characterVersionPatch),
    response: characterDetail,
    successStatus: 201,
  }),
  get: endpoint({
    id: 'characters.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/characters/{characterId}',
    summary: 'Character profile: approved and open versions, version list and allowed actions.',
    tags: ['Characters'],
    auth: 'workspace',
    permission: 'characters.read',
    params: wsId({ characterId: uuid }),
    response: characterDetail,
  }),
  update: endpoint({
    id: 'characters.update',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/characters/{characterId}',
    summary: 'Rename the character or change its role (profile fields live in versions).',
    tags: ['Characters'],
    auth: 'workspace',
    permission: 'characters.write',
    ifMatch: true,
    params: wsId({ characterId: uuid }),
    body: z.object({ name: shortName.optional(), role: z.string().trim().max(120).nullable().optional() }),
    response: characterDetail,
  }),
  setPrimary: endpoint({
    id: 'characters.setPrimary',
    method: 'POST',
    path: '/workspaces/{workspaceId}/characters/{characterId}/set-primary',
    summary: 'Mark (or unmark) the primary character of a Model/Influencer project; the previous primary is unmarked.',
    tags: ['Characters'],
    auth: 'workspace',
    permission: 'characters.write',
    idempotent: true,
    ifMatch: true,
    params: wsId({ characterId: uuid }),
    body: z.object({ primary: z.boolean() }),
    response: characterDetail,
  }),
  newVersion: endpoint({
    id: 'characters.newVersion',
    method: 'POST',
    path: '/workspaces/{workspaceId}/characters/{characterId}/versions',
    summary: 'Start a new draft profile version (copied from the latest version unless fields are given).',
    tags: ['Characters'],
    auth: 'workspace',
    permission: 'characters.write',
    idempotent: true,
    params: wsId({ characterId: uuid }),
    body: characterVersionPatch,
    response: characterDetail,
    successStatus: 201,
  }),
  updateVersion: endpoint({
    id: 'characters.updateVersion',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/character-versions/{versionId}',
    summary: 'Save Draft: change fields of a draft profile version. Submitted and approved versions are frozen.',
    tags: ['Characters'],
    auth: 'workspace',
    permission: 'characters.write',
    ifMatch: true,
    params: wsId({ versionId: uuid }),
    body: characterVersionPatch,
    response: characterDetail,
  }),
  submitVersion: endpoint({
    id: 'characters.submitVersion',
    method: 'POST',
    path: '/workspaces/{workspaceId}/character-versions/{versionId}/submit',
    summary: 'Submit a draft profile version for approval (creates a review).',
    tags: ['Characters'],
    auth: 'workspace',
    permission: 'characters.write',
    idempotent: true,
    ifMatch: true,
    params: wsId({ versionId: uuid }),
    body: z.object({ reviewerMembershipId: uuid.nullable().optional() }),
    response: characterDetail,
  }),
  approveVersion: endpoint({
    id: 'characters.approveVersion',
    method: 'POST',
    path: '/workspaces/{workspaceId}/character-versions/{versionId}/approve',
    summary: 'Approve Profile: freeze the version; content using older versions is flagged Needs Consistency Review.',
    tags: ['Characters'],
    auth: 'workspace',
    permission: 'characters.approve',
    idempotent: true,
    ifMatch: true,
    params: wsId({ versionId: uuid }),
    body: z.object({ reviewId: uuid, note: z.string().trim().max(2000).optional() }),
    response: characterDetail,
  }),
  requestChanges: endpoint({
    id: 'characters.requestChanges',
    method: 'POST',
    path: '/workspaces/{workspaceId}/character-versions/{versionId}/request-changes',
    summary: 'Return a submitted profile version to draft with a summary of required changes.',
    tags: ['Characters'],
    auth: 'workspace',
    permission: 'characters.approve',
    idempotent: true,
    ifMatch: true,
    params: wsId({ versionId: uuid }),
    body: z.object({ reviewId: uuid, summary: reason }),
    response: characterDetail,
  }),
  affectedContent: endpoint({
    id: 'characters.affectedContent',
    method: 'GET',
    path: '/workspaces/{workspaceId}/characters/{characterId}/affected-content',
    summary: 'Content items that use any version of this character (within the actor’s content scope).',
    tags: ['Characters'],
    auth: 'workspace',
    permission: 'characters.read',
    params: wsId({ characterId: uuid }),
    response: z.object({ items: z.array(affectedContentItem), hiddenCount: z.number().int() }),
  }),
  archive: endpoint({
    id: 'characters.archive',
    method: 'POST',
    path: '/workspaces/{workspaceId}/characters/{characterId}/archive',
    summary: 'Archive a character. Versions, scene and content links stay in history.',
    tags: ['Characters'],
    auth: 'workspace',
    permission: 'characters.write',
    idempotent: true,
    ifMatch: true,
    params: wsId({ characterId: uuid }),
    body: z.object({ reason: reason.optional() }),
    response: characterDetail,
  }),
  restore: endpoint({
    id: 'characters.restore',
    method: 'POST',
    path: '/workspaces/{workspaceId}/characters/{characterId}/restore',
    summary: 'Restore an archived character (not as primary).',
    tags: ['Characters'],
    auth: 'workspace',
    permission: 'characters.write',
    idempotent: true,
    ifMatch: true,
    params: wsId({ characterId: uuid }),
    body: z.object({}),
    response: characterDetail,
  }),
};

// ——— Series structure (S17) ———

export const sceneDeliverable = z.object({ label: z.string().trim().min(1).max(200), format: z.enum(CONTENT_FORMATS).optional(), done: z.boolean().optional() });

export const sceneView = z.object({
  id: uuid,
  episodeId: uuid,
  orderNo: z.number().int(),
  title: z.string(),
  script: z.string().nullable(),
  deliverables: z.array(sceneDeliverable),
  characters: z.array(z.object({ characterVersionId: uuid, characterId: uuid, name: z.string(), versionNo: z.number().int(), state: z.enum(CHARACTER_VERSION_STATES) })),
  thumbnailUrl: z.string().nullable(),
  thumbnailAssetId: uuid.nullable(),
  archivedAt: isoDateTime.nullable(),
  rowVersion: z.number().int(),
});
export type SceneView = z.infer<typeof sceneView>;

export const episodeView = z.object({
  id: uuid,
  seasonId: uuid,
  projectId: uuid,
  number: z.number().int(),
  title: z.string(),
  synopsis: z.string().nullable(),
  targetDurationSeconds: z.number().int().nullable(),
  language: z.string(),
  contentItem: z.object({ id: uuid, title: z.string(), stage: z.enum(CONTENT_STAGES) }).nullable(),
  thumbnailUrl: z.string().nullable(),
  thumbnailAssetId: uuid.nullable(),
  sceneCount: z.number().int(),
  archivedAt: isoDateTime.nullable(),
  rowVersion: z.number().int(),
});
export type EpisodeView = z.infer<typeof episodeView>;

export const episodeDetail = episodeView.extend({ scenes: z.array(sceneView), permissions: z.object({ write: z.boolean() }) });
export type EpisodeDetail = z.infer<typeof episodeDetail>;

export const seasonView = z.object({
  id: uuid,
  projectId: uuid,
  name: z.string(),
  orderNo: z.number().int(),
  archivedAt: isoDateTime.nullable(),
  rowVersion: z.number().int(),
  episodes: z.array(episodeView),
});
export type SeasonView = z.infer<typeof seasonView>;

export const seriesStructure = z.object({
  project: z.object({ id: uuid, name: z.string(), type: z.enum(PROJECT_TYPES), status: z.string() }),
  seasons: z.array(seasonView),
  permissions: z.object({ write: z.boolean() }),
});
export type SeriesStructure = z.infer<typeof seriesStructure>;

const episodeFields = {
  number: z.number().int().min(0).max(100_000),
  title: shortName,
  synopsis: z.string().max(LIMITS.noteMax).nullable().optional(),
  targetDurationSeconds: z.number().int().min(1).max(86_400).nullable().optional(),
  language: z.string().trim().min(2).max(20).optional(),
  contentItemId: uuid.nullable().optional(),
  thumbnailAssetId: uuid.nullable().optional(),
};

const sceneFields = {
  title: shortName,
  script: z.string().max(LIMITS.richTextMax).nullable().optional(),
  deliverables: z.array(sceneDeliverable).max(50).optional(),
  characterVersionIds: z.array(uuid).max(50).optional(),
  thumbnailAssetId: uuid.nullable().optional(),
};

const moveBody = z.object({ direction: z.enum(['up', 'down']) });

export const seriesEndpoints = {
  structure: endpoint({
    id: 'series.structure',
    method: 'GET',
    path: '/workspaces/{workspaceId}/projects/{projectId}/series',
    summary: 'Seasons and episodes of a series project (scenes are loaded per episode).',
    tags: ['Series'],
    auth: 'workspace',
    permission: 'series.read',
    params: wsId({ projectId: uuid }),
    query: z.object({ includeArchived: boolQuery.optional() }),
    response: seriesStructure,
  }),
  listSeasons: endpoint({
    id: 'series.listSeasons',
    method: 'GET',
    path: '/workspaces/{workspaceId}/projects/{projectId}/seasons',
    summary: 'Seasons of a project in order.',
    tags: ['Series'],
    auth: 'workspace',
    permission: 'series.read',
    params: wsId({ projectId: uuid }),
    query: z.object({ includeArchived: boolQuery.optional() }),
    response: z.array(seasonView),
  }),
  createSeason: endpoint({
    id: 'series.createSeason',
    method: 'POST',
    path: '/workspaces/{workspaceId}/projects/{projectId}/seasons',
    summary: 'Add a season (series projects only). Order is unique within the project.',
    tags: ['Series'],
    auth: 'workspace',
    permission: 'series.write',
    idempotent: true,
    params: wsId({ projectId: uuid }),
    body: z.object({ name: shortName, orderNo: z.number().int().min(1).max(10_000).optional() }),
    response: seasonView,
    successStatus: 201,
  }),
  getSeason: endpoint({
    id: 'series.getSeason',
    method: 'GET',
    path: '/workspaces/{workspaceId}/seasons/{seasonId}',
    summary: 'One season with its episodes.',
    tags: ['Series'],
    auth: 'workspace',
    permission: 'series.read',
    params: wsId({ seasonId: uuid }),
    response: seasonView,
  }),
  updateSeason: endpoint({
    id: 'series.updateSeason',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/seasons/{seasonId}',
    summary: 'Rename a season.',
    tags: ['Series'],
    auth: 'workspace',
    permission: 'series.write',
    ifMatch: true,
    params: wsId({ seasonId: uuid }),
    body: z.object({ name: shortName }),
    response: seasonView,
  }),
  moveSeason: endpoint({
    id: 'series.moveSeason',
    method: 'POST',
    path: '/workspaces/{workspaceId}/seasons/{seasonId}/move',
    summary: 'Move a season up or down (keyboard-accessible reorder; ids never change).',
    tags: ['Series'],
    auth: 'workspace',
    permission: 'series.write',
    idempotent: true,
    ifMatch: true,
    params: wsId({ seasonId: uuid }),
    body: moveBody,
    response: z.array(seasonView),
  }),
  archiveSeason: endpoint({
    id: 'series.archiveSeason',
    method: 'POST',
    path: '/workspaces/{workspaceId}/seasons/{seasonId}/archive',
    summary: 'Archive a season together with its episodes and scenes (history kept).',
    tags: ['Series'],
    auth: 'workspace',
    permission: 'series.write',
    idempotent: true,
    ifMatch: true,
    params: wsId({ seasonId: uuid }),
    body: z.object({ reason: reason.optional() }),
    response: okResponse,
  }),
  restoreSeason: endpoint({
    id: 'series.restoreSeason',
    method: 'POST',
    path: '/workspaces/{workspaceId}/seasons/{seasonId}/restore',
    summary: 'Restore an archived season at the end of the order (its episodes stay archived until restored).',
    tags: ['Series'],
    auth: 'workspace',
    permission: 'series.write',
    idempotent: true,
    ifMatch: true,
    params: wsId({ seasonId: uuid }),
    body: z.object({}),
    response: seasonView,
  }),
  listEpisodes: endpoint({
    id: 'series.listEpisodes',
    method: 'GET',
    path: '/workspaces/{workspaceId}/seasons/{seasonId}/episodes',
    summary: 'Episodes of a season ordered by number and language.',
    tags: ['Series'],
    auth: 'workspace',
    permission: 'series.read',
    params: wsId({ seasonId: uuid }),
    query: z.object({ includeArchived: boolQuery.optional() }),
    response: z.array(episodeView),
  }),
  createEpisode: endpoint({
    id: 'series.createEpisode',
    method: 'POST',
    path: '/workspaces/{workspaceId}/seasons/{seasonId}/episodes',
    summary: 'Add an episode. Number is unique within the season and language (T026).',
    tags: ['Series'],
    auth: 'workspace',
    permission: 'series.write',
    idempotent: true,
    params: wsId({ seasonId: uuid }),
    body: z.object(episodeFields),
    response: episodeDetail,
    successStatus: 201,
  }),
  getEpisode: endpoint({
    id: 'series.getEpisode',
    method: 'GET',
    path: '/workspaces/{workspaceId}/episodes/{episodeId}',
    summary: 'Episode with its ordered scenes.',
    tags: ['Series'],
    auth: 'workspace',
    permission: 'series.read',
    params: wsId({ episodeId: uuid }),
    query: z.object({ includeArchived: boolQuery.optional() }),
    response: episodeDetail,
  }),
  updateEpisode: endpoint({
    id: 'series.updateEpisode',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/episodes/{episodeId}',
    summary: 'Update episode fields; number/language uniqueness is enforced by the database.',
    tags: ['Series'],
    auth: 'workspace',
    permission: 'series.write',
    ifMatch: true,
    params: wsId({ episodeId: uuid }),
    body: z.object(episodeFields).partial(),
    response: episodeDetail,
  }),
  archiveEpisode: endpoint({
    id: 'series.archiveEpisode',
    method: 'POST',
    path: '/workspaces/{workspaceId}/episodes/{episodeId}/archive',
    summary: 'Archive an episode instead of deleting it (publications keep their links).',
    tags: ['Series'],
    auth: 'workspace',
    permission: 'series.write',
    idempotent: true,
    ifMatch: true,
    params: wsId({ episodeId: uuid }),
    body: z.object({ reason: reason.optional() }),
    response: episodeDetail,
  }),
  restoreEpisode: endpoint({
    id: 'series.restoreEpisode',
    method: 'POST',
    path: '/workspaces/{workspaceId}/episodes/{episodeId}/restore',
    summary: 'Restore an archived episode (fails with a duplicate conflict if its number is now taken).',
    tags: ['Series'],
    auth: 'workspace',
    permission: 'series.write',
    idempotent: true,
    ifMatch: true,
    params: wsId({ episodeId: uuid }),
    body: z.object({}),
    response: episodeDetail,
  }),
  listScenes: endpoint({
    id: 'series.listScenes',
    method: 'GET',
    path: '/workspaces/{workspaceId}/episodes/{episodeId}/scenes',
    summary: 'Scenes of an episode in order.',
    tags: ['Series'],
    auth: 'workspace',
    permission: 'series.read',
    params: wsId({ episodeId: uuid }),
    query: z.object({ includeArchived: boolQuery.optional() }),
    response: z.array(sceneView),
  }),
  createScene: endpoint({
    id: 'series.createScene',
    method: 'POST',
    path: '/workspaces/{workspaceId}/episodes/{episodeId}/scenes',
    summary: 'Add a scene at the end of the episode. Characters are linked by frozen character versions.',
    tags: ['Series'],
    auth: 'workspace',
    permission: 'series.write',
    idempotent: true,
    params: wsId({ episodeId: uuid }),
    body: z.object(sceneFields),
    response: sceneView,
    successStatus: 201,
  }),
  getScene: endpoint({
    id: 'series.getScene',
    method: 'GET',
    path: '/workspaces/{workspaceId}/scenes/{sceneId}',
    summary: 'One scene.',
    tags: ['Series'],
    auth: 'workspace',
    permission: 'series.read',
    params: wsId({ sceneId: uuid }),
    response: sceneView,
  }),
  updateScene: endpoint({
    id: 'series.updateScene',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/scenes/{sceneId}',
    summary: 'Update scene fields and character version links.',
    tags: ['Series'],
    auth: 'workspace',
    permission: 'series.write',
    ifMatch: true,
    params: wsId({ sceneId: uuid }),
    body: z.object(sceneFields).partial(),
    response: sceneView,
  }),
  moveScene: endpoint({
    id: 'series.moveScene',
    method: 'POST',
    path: '/workspaces/{workspaceId}/scenes/{sceneId}/move',
    summary: 'Move a scene up or down within its episode; stable ids and links never change (T027).',
    tags: ['Series'],
    auth: 'workspace',
    permission: 'series.write',
    idempotent: true,
    ifMatch: true,
    params: wsId({ sceneId: uuid }),
    body: moveBody,
    response: z.array(sceneView),
  }),
  archiveScene: endpoint({
    id: 'series.archiveScene',
    method: 'POST',
    path: '/workspaces/{workspaceId}/scenes/{sceneId}/archive',
    summary: 'Archive a scene (its links and history are kept).',
    tags: ['Series'],
    auth: 'workspace',
    permission: 'series.write',
    idempotent: true,
    ifMatch: true,
    params: wsId({ sceneId: uuid }),
    body: z.object({ reason: reason.optional() }),
    response: okResponse,
  }),
};

// ——— References (S21) ———

export const REFERENCE_LINK_TARGETS = ['project', 'content_item', 'character'] as const;

export const referenceRow = z.object({
  id: uuid,
  title: z.string(),
  sourceUrl: z.string().nullable(),
  sourceAsset: z.object({ id: uuid, name: z.string(), kind: z.string(), restricted: z.boolean() }).nullable(),
  previewUrl: z.string().nullable(),
  previewAssetId: uuid.nullable(),
  whatToReuse: z.string(),
  notes: z.string().nullable(),
  tags: z.array(z.enum(REFERENCE_TAGS)),
  project: z.object({ id: uuid, name: z.string() }).nullable(),
  author: memberRef,
  usage: z.object({ projects: z.number().int(), characters: z.number().int(), content: z.number().int() }),
  archivedAt: isoDateTime.nullable(),
  createdAt: isoDateTime,
  updatedAt: isoDateTime,
  rowVersion: z.number().int(),
});
export type ReferenceRow = z.infer<typeof referenceRow>;

export const referenceLinkView = z.object({
  id: uuid,
  targetType: z.enum(REFERENCE_LINK_TARGETS),
  targetId: uuid,
  kind: z.enum(['link', 'idea']),
  label: z.string(),
  sublabel: z.string().nullable(),
  href: z.string(),
  createdAt: isoDateTime,
});

export const referenceDetail = referenceRow.extend({
  links: z.array(referenceLinkView),
  /** Links to records the actor cannot read are counted, never named. */
  hiddenLinkCount: z.number().int(),
  idea: z.object({ contentItemId: uuid, title: z.string(), stage: z.enum(CONTENT_STAGES) }).nullable(),
  permissions: z.object({ update: z.boolean(), archive: z.boolean(), createIdea: z.boolean() }),
});
export type ReferenceDetail = z.infer<typeof referenceDetail>;

const referenceFields = {
  title: shortName,
  sourceUrl: z.string().trim().max(LIMITS.urlMax).nullable().optional(),
  sourceAssetId: uuid.nullable().optional(),
  previewAssetId: uuid.nullable().optional(),
  whatToReuse: z.string().trim().min(3).max(LIMITS.noteMax),
  notes: z.string().max(LIMITS.noteMax).nullable().optional(),
  tags: z.array(z.enum(REFERENCE_TAGS)).max(REFERENCE_TAGS.length).optional(),
  projectId: uuid.nullable().optional(),
};

export const referenceEndpoints = {
  list: endpoint({
    id: 'references.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/references',
    summary: 'References visible to the actor (workspace-wide ones and those of projects in scope).',
    tags: ['References'],
    auth: 'workspace',
    permission: 'references.read',
    params: wsId({}),
    query: pageQuery.extend({
      q: z.string().trim().max(120).optional(),
      tag: csv(z.enum(REFERENCE_TAGS)).optional(),
      projectId: uuid.optional(),
      characterId: uuid.optional(),
      ownerMembershipId: uuid.optional(),
      includeArchived: boolQuery.optional(),
      sort: z.enum(['updatedAt', 'title', 'createdAt']).default('updatedAt'),
      direction: z.enum(['asc', 'desc']).default('desc'),
    }),
    response: page(referenceRow),
  }),
  get: endpoint({
    id: 'references.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/references/{referenceId}',
    summary: 'Reference with permitted usage links and its idea draft.',
    tags: ['References'],
    auth: 'workspace',
    permission: 'references.read',
    params: wsId({ referenceId: uuid }),
    response: referenceDetail,
  }),
  create: endpoint({
    id: 'references.create',
    method: 'POST',
    path: '/workspaces/{workspaceId}/references',
    summary: 'Add a reference from a link (kept as a note — never downloaded) or an uploaded file.',
    tags: ['References'],
    auth: 'workspace',
    permission: 'references.write',
    idempotent: true,
    params: wsId({}),
    body: z.object(referenceFields),
    response: referenceDetail,
    successStatus: 201,
  }),
  update: endpoint({
    id: 'references.update',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/references/{referenceId}',
    summary: 'Edit a reference.',
    tags: ['References'],
    auth: 'workspace',
    permission: 'references.write',
    ifMatch: true,
    params: wsId({ referenceId: uuid }),
    body: z.object(referenceFields).partial(),
    response: referenceDetail,
  }),
  link: endpoint({
    id: 'references.link',
    method: 'POST',
    path: '/workspaces/{workspaceId}/references/{referenceId}/links',
    summary: 'Link the reference to a project, character or content item the actor can read.',
    tags: ['References'],
    auth: 'workspace',
    permission: 'references.write',
    idempotent: true,
    params: wsId({ referenceId: uuid }),
    body: z.object({ targetType: z.enum(REFERENCE_LINK_TARGETS), targetId: uuid }),
    response: referenceDetail,
  }),
  unlink: endpoint({
    id: 'references.unlink',
    method: 'POST',
    path: '/workspaces/{workspaceId}/references/{referenceId}/links/{linkId}/remove',
    summary: 'Remove one usage link (the idea link of a created draft is kept).',
    tags: ['References'],
    auth: 'workspace',
    permission: 'references.write',
    idempotent: true,
    params: wsId({ referenceId: uuid, linkId: uuid }),
    body: z.object({}),
    response: referenceDetail,
  }),
  useAsIdea: endpoint({
    id: 'references.useAsIdea',
    method: 'POST',
    path: '/workspaces/{workspaceId}/references/{referenceId}/use-as-idea',
    summary: 'Create one linked content draft in stage Idea (repeat calls return the same draft, T035).',
    tags: ['References'],
    auth: 'workspace',
    permission: 'references.write',
    idempotent: true,
    params: wsId({ referenceId: uuid }),
    body: z.object({ projectId: uuid, format: z.enum(CONTENT_FORMATS), title: shortName.optional() }),
    response: z.object({ contentItemId: uuid, created: z.boolean(), reference: referenceDetail }),
  }),
  archive: endpoint({
    id: 'references.archive',
    method: 'POST',
    path: '/workspaces/{workspaceId}/references/{referenceId}/archive',
    summary: 'Archive a reference; linked content keeps the reference id.',
    tags: ['References'],
    auth: 'workspace',
    permission: 'references.write',
    idempotent: true,
    ifMatch: true,
    params: wsId({ referenceId: uuid }),
    body: z.object({ reason: reason.optional() }),
    response: referenceDetail,
  }),
  restore: endpoint({
    id: 'references.restore',
    method: 'POST',
    path: '/workspaces/{workspaceId}/references/{referenceId}/restore',
    summary: 'Restore an archived reference.',
    tags: ['References'],
    auth: 'workspace',
    permission: 'references.write',
    idempotent: true,
    ifMatch: true,
    params: wsId({ referenceId: uuid }),
    body: z.object({}),
    response: referenceDetail,
  }),
};
