import { z } from 'zod';
import {
  ACCOUNTING_CLASSES,
  BUDGET_VERSION_STATES,
  COMMITMENT_STATES,
  COMPENSATION_RULE_STATES,
  COMPENSATION_RULE_TYPES,
  COMPENSATION_RUN_STATES,
  FINANCE_ENTRY_STATES,
  FINANCE_ENTRY_TYPES,
  HOURLY_SOURCES,
  LIMITS,
  PRORATION_POLICIES,
  REVENUE_SHARE_BASES,
  SALE_CANDIDATE_STATES,
  SETTLEMENT_DIRECTIONS,
  SETTLEMENT_STATES,
} from '@castlane/domain';
import { endpoint } from './core';
import {
  boolQuery,
  csv,
  currencyCode,
  decimalString,
  isoDate,
  isoDateTime,
  memberRef,
  money,
  page,
  pageQuery,
  percent,
  reason,
  shortName,
  uuid,
  wsId,
} from './common';

/**
 * Finance (spec §18, S55–S60). Amounts are decimal strings with a currency; minor units never
 * travel as floats. Amount fields are omitted (not null) when the caller lacks the finance
 * permission for them. Posted records are immutable: corrections are reversals/replacements.
 */

const T = ['Finance'];
const noteText = z.string().max(LIMITS.noteMax);
const ref = z.object({ id: uuid, name: z.string() });
export type FinanceRef = z.infer<typeof ref>;
const signedMoney = money; // amount may be negative ("-12.50")

// ——— Categories ———

export const financeCategory = z.object({
  id: uuid,
  key: z.string(),
  name: z.string(),
  accountingClass: z.enum(ACCOUNTING_CLASSES),
  isSystem: z.boolean(),
  sortOrder: z.number().int(),
  archivedAt: isoDateTime.nullable(),
  rowVersion: z.number().int(),
});
export type FinanceCategory = z.infer<typeof financeCategory>;

// ——— FX rates ———

export const fxRate = z.object({
  id: uuid,
  fromCurrency: z.string(),
  toCurrency: z.string(),
  rate: z.string(),
  effectiveDate: isoDate,
  source: z.string(),
  firstUsedAt: isoDateTime.nullable(),
  /** Used by posted records: frozen, create a new rate instead of editing. */
  locked: z.boolean(),
  createdAt: isoDateTime,
  createdBy: memberRef.nullable(),
  rowVersion: z.number().int(),
});
export type FxRate = z.infer<typeof fxRate>;

const rateString = z.string().refine((v) => /^\d+(\.\d{1,10})?$/.test(v.trim()) && Number(v) > 0, 'Enter a positive rate with at most 10 decimals.');

// ——— Allocation ———

export const allocationSpec = z.object({
  mode: z.enum(['exact', 'percent', 'weights']),
  rows: z
    .array(
      z.object({
        /** null = explicit Unallocated remainder. */
        projectId: uuid.nullable(),
        campaignId: uuid.nullable().optional(),
        contentItemId: uuid.nullable().optional(),
        value: decimalString,
      }),
    )
    .min(1)
    .max(200),
});
export type AllocationSpecInput = z.infer<typeof allocationSpec>;

export const allocationView = z.object({
  id: uuid,
  project: ref.nullable(),
  campaign: ref.nullable(),
  contentItem: ref.nullable(),
  amount: signedMoney,
  baseAmount: signedMoney.nullable(),
  sharePercent: z.string().nullable(),
  effectiveDate: isoDate,
  /** Set on adjustment rows created by a posted re-allocation. */
  adjustmentOfId: uuid.nullable(),
});

// ——— Entries ———

export const entryLineInput = z.object({
  categoryId: uuid,
  amount: decimalString,
  currency: currencyCode,
  description: z.string().trim().max(500).nullable().optional(),
  transactionRef: z.string().trim().min(1).max(200).nullable().optional(),
  componentsUnknown: z.boolean().optional(),
  commitmentId: uuid.nullable().optional(),
  /** Pin a specific FX rate; otherwise the latest rate on or before the recognition date is used at posting. */
  fxRateId: uuid.nullable().optional(),
  fxEffect: z.enum(['gain', 'loss']).nullable().optional(),
  allocation: allocationSpec.nullable().optional(),
});
export type EntryLineInput = z.infer<typeof entryLineInput>;

const entryFields = {
  type: z.enum(FINANCE_ENTRY_TYPES),
  title: shortName,
  recognitionDate: isoDate,
  counterparty: z.string().trim().max(200).nullable().optional(),
  sourceNamespace: z.string().trim().min(2).max(60).regex(/^[a-z0-9_.:-]+$/i, 'Use letters, digits and . _ : -').nullable().optional(),
  sourceExternalId: z.string().trim().min(1).max(200).nullable().optional(),
  accountId: uuid.nullable().optional(),
  campaignId: uuid.nullable().optional(),
  shiftId: uuid.nullable().optional(),
  dealId: uuid.nullable().optional(),
  refundOfEntryId: uuid.nullable().optional(),
  note: noteText.nullable().optional(),
  netOnly: z.boolean().optional(),
  controlTotal: money.nullable().optional(),
  lines: z.array(entryLineInput).min(1).max(200),
  /** Default allocation for lines without their own (percent/weights). */
  allocation: allocationSpec.nullable().optional(),
};

export const entryLineView = z.object({
  id: uuid,
  lineNo: z.number().int(),
  category: z.object({ id: uuid, key: z.string(), name: z.string(), accountingClass: z.enum(ACCOUNTING_CLASSES) }),
  accountingClass: z.enum(ACCOUNTING_CLASSES),
  amount: money,
  fx: z.object({ rate: z.string(), rateId: uuid.nullable(), source: z.string().nullable(), effectiveDate: isoDate.nullable() }).nullable(),
  baseAmount: money.nullable(),
  description: z.string().nullable(),
  transactionRef: z.string().nullable(),
  componentsUnknown: z.boolean(),
  isReversal: z.boolean(),
  fxEffect: z.enum(['gain', 'loss']).nullable(),
  commitment: ref.nullable(),
  allocations: z.array(allocationView),
});
export type EntryLineView = z.infer<typeof entryLineView>;

export const evidenceItem = z.object({
  assetId: uuid,
  linkId: uuid.nullable(),
  name: z.string(),
  mime: z.string().nullable(),
  status: z.string().nullable(),
  thumbnailUrl: z.string().nullable(),
});

export const attributionView = z.object({
  id: uuid,
  member: memberRef,
  sharePercent: z.string(),
  basis: z.enum(['source_assignment', 'manual']),
  reason: z.string().nullable(),
  createdAt: isoDateTime,
});

export const entryDisplayState = z.enum(['draft', 'submitted', 'posted', 'rejected', 'reversed']);

export const entryRow = z.object({
  id: uuid,
  type: z.enum(FINANCE_ENTRY_TYPES),
  state: z.enum(FINANCE_ENTRY_STATES),
  displayState: entryDisplayState,
  recognitionDate: isoDate,
  title: z.string(),
  counterparty: z.string().nullable(),
  source: z.object({ namespace: z.string(), externalId: z.string() }).nullable(),
  /** Signed economic effect in the base currency (null while an FX rate is missing on a draft). */
  netBase: money.nullable().optional(),
  /** Document balance per currency: positive = receivable, negative = payable. */
  balances: z.array(signedMoney).optional(),
  projects: z.array(ref),
  unallocated: z.boolean(),
  netOnly: z.boolean(),
  isReversal: z.boolean(),
  lineCount: z.number().int(),
  createdAt: isoDateTime,
  updatedAt: isoDateTime,
  rowVersion: z.number().int(),
});
export type EntryRow = z.infer<typeof entryRow>;

export const entryDetail = entryRow.extend({
  baseCurrency: z.string(),
  account: ref.nullable(),
  campaign: ref.nullable(),
  deal: ref.nullable(),
  shiftId: uuid.nullable(),
  saleCandidateId: uuid.nullable(),
  compensationRunId: uuid.nullable(),
  note: z.string().nullable(),
  controlTotal: money.nullable(),
  controlCheck: z.object({ status: z.enum(['match', 'mismatch', 'not_applicable']), difference: signedMoney.nullable() }),
  lines: z.array(entryLineView),
  summary: z
    .object({
      grossRevenue: money,
      refunds: money,
      fees: money,
      netRevenue: money,
      operatingExpenses: money,
      compensationExpense: money,
      result: signedMoney,
      grossIncomplete: z.boolean(),
    })
    .nullable(),
  missingFx: z.array(z.object({ currency: z.string(), date: isoDate })),
  /** Present only with finance.documents.read. */
  evidence: z.array(evidenceItem).optional(),
  attributions: z.array(attributionView),
  settlements: z.array(
    z.object({
      allocationId: uuid,
      settlementId: uuid,
      direction: z.enum(SETTLEMENT_DIRECTIONS),
      paidAt: isoDateTime,
      documentAmount: money,
      cashAmount: money,
      reversed: z.boolean(),
    }),
  ),
  outstanding: z.array(signedMoney),
  submittedAt: isoDateTime.nullable(),
  submittedBy: memberRef.nullable(),
  postedAt: isoDateTime.nullable(),
  postedBy: memberRef.nullable(),
  selfApprovalReason: z.string().nullable(),
  rejectedAt: isoDateTime.nullable(),
  rejectedReason: z.string().nullable(),
  reversesEntryId: uuid.nullable(),
  reversedByEntryId: uuid.nullable(),
  replacementOfEntryId: uuid.nullable(),
  refundOfEntryId: uuid.nullable(),
  reversalReason: z.string().nullable(),
  createdBy: memberRef.nullable(),
  permissions: z.object({
    update: z.boolean(),
    submit: z.boolean(),
    post: z.boolean(),
    reject: z.boolean(),
    reverse: z.boolean(),
    allocate: z.boolean(),
    attribute: z.boolean(),
    addSettlement: z.boolean(),
    /** The actor submitted this entry: posting needs the single-owner exception with a reason. */
    selfApprovalRequired: z.boolean(),
    viewEvidence: z.boolean(),
    attachEvidence: z.boolean(),
  }),
});
export type EntryDetail = z.infer<typeof entryDetail>;

const entryListQuery = pageQuery.extend({
  q: z.string().trim().max(120).optional(),
  state: csv(entryDisplayState).optional(),
  type: csv(z.enum(FINANCE_ENTRY_TYPES)).optional(),
  from: isoDate.optional(),
  to: isoDate.optional(),
  projectId: uuid.optional(),
  unallocated: boolQuery.optional(),
  categoryId: uuid.optional(),
  accountId: uuid.optional(),
  campaignId: uuid.optional(),
  dealId: uuid.optional(),
  sourceNamespace: z.string().max(60).optional(),
  sort: z.enum(['recognitionDate', 'updatedAt', 'title']).default('recognitionDate'),
  direction: z.enum(['asc', 'desc']).default('desc'),
});

// ——— Settlements ———

export const settlementAllocationInput = z
  .object({
    targetType: z.enum(['entry', 'compensation_run']),
    targetEntryId: uuid.optional(),
    targetRunId: uuid.optional(),
    recipientMembershipId: uuid.optional(),
    /** Amount in the settlement currency. */
    amount: decimalString,
    /** Amount settled in the document currency (required when currencies differ). */
    documentAmount: decimalString.optional(),
    documentCurrency: currencyCode.optional(),
  })
  .refine((v) => (v.targetType === 'entry' ? !!v.targetEntryId : !!v.targetRunId && !!v.recipientMembershipId), 'Choose the entry, or the run and recipient.');
export type SettlementAllocationInput = z.infer<typeof settlementAllocationInput>;

export const settlementAllocationView = z.object({
  id: uuid,
  targetType: z.enum(['entry', 'compensation_run']),
  entry: z.object({ id: uuid, title: z.string(), recognitionDate: isoDate }).nullable(),
  run: z.object({ id: uuid, periodStart: isoDate, periodEnd: isoDate }).nullable(),
  recipient: memberRef.nullable(),
  amount: money,
  documentAmount: money,
  effectiveFxRate: z.string().nullable(),
  realizedDifferenceEntryId: uuid.nullable(),
  reversedAt: isoDateTime.nullable(),
  reversalReason: z.string().nullable(),
});

export const settlementRow = z.object({
  id: uuid,
  direction: z.enum(SETTLEMENT_DIRECTIONS),
  state: z.enum(SETTLEMENT_STATES),
  amount: money,
  allocated: money,
  unallocated: money,
  remainderPolicy: z.enum(['none', 'advance', 'unallocated']),
  paidAt: isoDateTime,
  paymentReference: z.string().nullable(),
  paymentSourceNamespace: z.string(),
  manualReference: z.boolean(),
  counterparty: z.string().nullable(),
  compensationRunId: uuid.nullable(),
  createdAt: isoDateTime,
  rowVersion: z.number().int(),
});
export type SettlementRow = z.infer<typeof settlementRow>;

export const settlementDetail = settlementRow.extend({
  note: z.string().nullable(),
  duplicateAckReason: z.string().nullable(),
  confirmedAt: isoDateTime.nullable(),
  confirmedBy: memberRef.nullable(),
  reversedAt: isoDateTime.nullable(),
  reversalReason: z.string().nullable(),
  reversalEffectiveDate: isoDate.nullable(),
  allocations: z.array(settlementAllocationView),
  evidence: z.array(evidenceItem).optional(),
  createdBy: memberRef.nullable(),
  permissions: z.object({ update: z.boolean(), confirm: z.boolean(), match: z.boolean(), reverse: z.boolean(), attachEvidence: z.boolean() }),
});
export type SettlementDetail = z.infer<typeof settlementDetail>;

const settlementFields = {
  direction: z.enum(SETTLEMENT_DIRECTIONS),
  amount: decimalString,
  currency: currencyCode,
  paidAt: isoDateTime,
  paymentSourceNamespace: z.string().trim().min(2).max(60).regex(/^[a-z0-9_.:-]+$/i).optional(),
  paymentReference: z.string().trim().min(1).max(200).nullable().optional(),
  counterparty: z.string().trim().max(200).nullable().optional(),
  note: noteText.nullable().optional(),
  /** Required when the duplicate heuristic finds a similar payment (same counterparty/amount/currency/date). */
  duplicateAckReason: reason.nullable().optional(),
};

export const openItem = z.object({
  targetType: z.enum(['entry', 'compensation_run']),
  entryId: uuid.nullable(),
  runId: uuid.nullable(),
  recipient: memberRef.nullable(),
  title: z.string(),
  date: isoDate,
  outstanding: signedMoney,
});

// ——— Budgets & commitments ———

const budgetScopeType = z.enum(['workspace', 'direction', 'project', 'campaign']);

export const budgetLineView = z.object({
  id: uuid,
  category: ref.extend({ accountingClass: z.enum(ACCOUNTING_CLASSES) }),
  planned: money,
  note: z.string().nullable(),
});

export const budgetFiguresView = z.object({
  planned: money,
  actual: money,
  committed: money,
  remaining: signedMoney,
  consumedPercent: z.string().nullable(),
});

export const budgetVersionView = z.object({
  id: uuid,
  versionNo: z.number().int(),
  state: z.enum(BUDGET_VERSION_STATES),
  reason: z.string().nullable(),
  submittedAt: isoDateTime.nullable(),
  approvedAt: isoDateTime.nullable(),
  approvedBy: memberRef.nullable(),
  createdAt: isoDateTime,
  lines: z.array(budgetLineView),
  total: money,
});

export const budgetRow = z.object({
  id: uuid,
  name: z.string(),
  scopeType: budgetScopeType,
  scope: ref.nullable(),
  periodStart: isoDate,
  periodEnd: isoDate,
  currency: z.string(),
  owner: memberRef,
  approvedVersionNo: z.number().int().nullable(),
  draftVersionNo: z.number().int().nullable(),
  figures: budgetFiguresView.nullable(),
  archivedAt: isoDateTime.nullable(),
  rowVersion: z.number().int(),
});
export type BudgetRow = z.infer<typeof budgetRow>;

export const budgetDetail = budgetRow.extend({
  alertThresholds: z.array(z.number().int()),
  copiedFromId: uuid.nullable(),
  versions: z.array(budgetVersionView),
  lineFigures: z.array(z.object({ category: ref.extend({ accountingClass: z.enum(ACCOUNTING_CLASSES) }), figures: budgetFiguresView })),
  alerts: z.array(z.object({ id: uuid, versionId: uuid, threshold: z.number().int(), crossedAt: isoDateTime, resetAt: isoDateTime.nullable() })),
  /** Actual amounts in other currencies that cannot be compared with this budget. */
  excludedCurrencies: z.array(money),
  permissions: z.object({ update: z.boolean(), submit: z.boolean(), approve: z.boolean(), revise: z.boolean(), archive: z.boolean() }),
});
export type BudgetDetail = z.infer<typeof budgetDetail>;

const budgetLineInput = z.object({ categoryId: uuid, planned: decimalString, note: z.string().max(500).nullable().optional() });

export const commitmentView = z.object({
  id: uuid,
  project: ref,
  budget: ref.nullable(),
  category: ref,
  amount: money,
  consumed: money,
  remaining: money,
  dueDate: isoDate.nullable(),
  counterparty: z.string().nullable(),
  description: z.string(),
  state: z.enum(COMMITMENT_STATES),
  cancelReason: z.string().nullable(),
  consumptions: z.array(z.object({ id: uuid, entryId: uuid, entryTitle: z.string(), amount: money, reversedAt: isoDateTime.nullable(), createdAt: isoDateTime })),
  createdAt: isoDateTime,
  rowVersion: z.number().int(),
});
export type CommitmentView = z.infer<typeof commitmentView>;

const commitmentFields = {
  projectId: uuid,
  budgetId: uuid.nullable().optional(),
  categoryId: uuid,
  amount: decimalString,
  currency: currencyCode,
  dueDate: isoDate.nullable().optional(),
  counterparty: z.string().trim().max(200).nullable().optional(),
  description: z.string().trim().min(3).max(500),
};

// ——— Compensation rules ———

export const ruleVersionInput = z.object({
  type: z.enum(COMPENSATION_RULE_TYPES),
  effectiveFrom: isoDate,
  effectiveTo: isoDate.nullable().optional(),
  /** Fixed monthly amount, hourly rate or per-unit rate. */
  rate: decimalString.nullable().optional(),
  ratePercent: percent.nullable().optional(),
  currency: currencyCode,
  revenueBasis: z.enum(REVENUE_SHARE_BASES).nullable().optional(),
  hourlySource: z.enum(HOURLY_SOURCES).nullable().optional(),
  proration: z.enum(PRORATION_POLICIES).optional(),
  eligibleProjectIds: z.array(uuid).max(200).optional(),
  contributorResponsibility: z.string().max(60).nullable().optional(),
});
export type RuleVersionInput = z.infer<typeof ruleVersionInput>;

export const ruleVersionView = z.object({
  id: uuid,
  versionNo: z.number().int(),
  state: z.enum(COMPENSATION_RULE_STATES),
  type: z.enum(COMPENSATION_RULE_TYPES),
  effectiveFrom: isoDate,
  effectiveTo: isoDate.nullable(),
  rate: money.nullable(),
  ratePercent: z.string().nullable(),
  currency: z.string(),
  revenueBasis: z.enum(REVENUE_SHARE_BASES).nullable(),
  hourlySource: z.enum(HOURLY_SOURCES).nullable(),
  proration: z.enum(PRORATION_POLICIES),
  eligibleProjects: z.array(ref),
  contributorResponsibility: z.string().nullable(),
  refundPolicy: z.string(),
  approvedAt: isoDateTime.nullable(),
  approvedBy: memberRef.nullable(),
  endedAt: isoDateTime.nullable(),
  createdAt: isoDateTime,
  createdBy: memberRef.nullable(),
});
export type RuleVersionView = z.infer<typeof ruleVersionView>;

export const ruleRow = z.object({
  id: uuid,
  name: z.string(),
  recipientScopeType: z.enum(['member', 'role']),
  recipient: memberRef.nullable(),
  role: ref.nullable(),
  componentKey: z.string(),
  stackGroup: z.string().nullable(),
  currentVersion: ruleVersionView.nullable(),
  draftVersion: ruleVersionView.nullable(),
  archivedAt: isoDateTime.nullable(),
  rowVersion: z.number().int(),
});
export type RuleRow = z.infer<typeof ruleRow>;

export const ruleDetail = ruleRow.extend({
  versions: z.array(ruleVersionView),
  affectedRuns: z.array(z.object({ id: uuid, periodStart: isoDate, periodEnd: isoDate, state: z.enum(COMPENSATION_RUN_STATES) })),
  permissions: z.object({ createVersion: z.boolean(), approve: z.boolean(), end: z.boolean(), simulate: z.boolean(), archive: z.boolean() }),
});
export type RuleDetail = z.infer<typeof ruleDetail>;

// ——— Compensation runs ———

export const runLineView = z.object({
  id: uuid,
  recipient: memberRef,
  ruleVersionId: uuid.nullable(),
  ruleName: z.string().nullable(),
  adjustmentId: uuid.nullable(),
  sourceType: z.string(),
  sourceId: z.string(),
  sourceLabel: z.string().nullable(),
  component: z.string(),
  entitlementKey: z.string(),
  quantity: z.string().nullable(),
  rate: z.string().nullable(),
  amount: signedMoney,
  excluded: z.boolean(),
  exclusionReason: z.string().nullable(),
  explanation: z.record(z.string(), z.unknown()),
});
export type RunLineView = z.infer<typeof runLineView>;

export const runRecipientTotal = z.object({
  recipient: memberRef,
  currency: z.string(),
  total: signedMoney,
  payable: money,
  carryForward: signedMoney,
  paid: money,
  outstanding: money,
});

export const adjustmentView = z.object({
  id: uuid,
  recipient: memberRef,
  amount: signedMoney,
  kind: z.enum(['manual_bonus', 'manual_adjustment', 'refund', 'reallocation', 'reversal', 'carry_forward']),
  reason: z.string(),
  state: z.enum(['draft', 'approved', 'reversed']),
  originalEntitlementKey: z.string().nullable(),
  sourceRunId: uuid.nullable(),
  appliedRunId: uuid.nullable(),
  reversesAdjustmentId: uuid.nullable(),
  createdBy: memberRef.nullable(),
  approvedBy: memberRef.nullable(),
  approvedAt: isoDateTime.nullable(),
  createdAt: isoDateTime,
});
export type AdjustmentView = z.infer<typeof adjustmentView>;

export const runRow = z.object({
  id: uuid,
  periodStart: isoDate,
  periodEnd: isoDate,
  state: z.enum(COMPENSATION_RUN_STATES),
  participants: z.array(memberRef),
  calculationVersion: z.number().int(),
  totals: z.array(z.object({ currency: z.string(), amount: signedMoney, paid: money })),
  calculatedAt: isoDateTime.nullable(),
  approvedAt: isoDateTime.nullable(),
  createdAt: isoDateTime,
  rowVersion: z.number().int(),
});
export type RunRow = z.infer<typeof runRow>;

export const runDetail = runRow.extend({
  sourceDigest: z.string().nullable(),
  submittedAt: isoDateTime.nullable(),
  submittedBy: memberRef.nullable(),
  approvedBy: memberRef.nullable(),
  expenseEntryId: uuid.nullable(),
  cancelReason: z.string().nullable(),
  returnReason: z.string().nullable(),
  lines: z.array(runLineView),
  recipientTotals: z.array(runRecipientTotal),
  diff: z
    .object({
      previousVersion: z.number().int(),
      added: z.array(z.object({ entitlementKey: z.string(), amount: signedMoney })),
      removed: z.array(z.object({ entitlementKey: z.string(), amount: signedMoney })),
      changed: z.array(z.object({ entitlementKey: z.string(), from: signedMoney, to: signedMoney })),
    })
    .nullable(),
  adjustments: z.array(adjustmentView),
  payments: z.array(
    z.object({ settlementId: uuid, allocationId: uuid, recipient: memberRef, amount: money, paidAt: isoDateTime, paymentReference: z.string().nullable(), reversed: z.boolean() }),
  ),
  warnings: z.array(z.object({ code: z.string(), message: z.string(), details: z.record(z.string(), z.unknown()).optional() })),
  ruleVersions: z.array(z.object({ id: uuid, ruleId: uuid, name: z.string(), type: z.enum(COMPENSATION_RULE_TYPES), versionNo: z.number().int() })),
  permissions: z.object({
    update: z.boolean(),
    calculate: z.boolean(),
    submit: z.boolean(),
    returnToDraft: z.boolean(),
    approve: z.boolean(),
    cancel: z.boolean(),
    addAdjustment: z.boolean(),
    recordPayment: z.boolean(),
    selfApprovalRequired: z.boolean(),
  }),
});
export type RunDetail = z.infer<typeof runDetail>;

// ——— Periods ———

export const periodIssue = z.object({
  kind: z.enum(['unreviewed_entries', 'unmatched_settlements', 'unallocated_costs', 'compensation_drafts', 'missing_fx']),
  label: z.string(),
  count: z.number().int(),
});

export const periodLockView = z.object({
  id: uuid,
  periodStart: isoDate,
  periodEnd: isoDate,
  state: z.enum(['locked', 'reopened']),
  lockedAt: isoDateTime,
  lockedBy: memberRef.nullable(),
  unresolvedItems: z.array(z.object({ kind: z.string(), count: z.number().int(), note: z.string().optional() })),
  reopenedAt: isoDateTime.nullable(),
  reopenedBy: memberRef.nullable(),
  reopenReason: z.string().nullable(),
  rowVersion: z.number().int(),
});

// ——— Sale candidates (finance reconciliation queue) ———

export const saleCandidateView = z.object({
  id: uuid,
  state: z.enum(SALE_CANDIDATE_STATES),
  account: ref.nullable(),
  project: ref.nullable(),
  sourceNamespace: z.string(),
  sourceTransactionId: z.string(),
  manualReference: z.boolean(),
  occurredAt: isoDateTime,
  gross: money.nullable(),
  refund: money.nullable(),
  fee: money.nullable(),
  net: money.nullable(),
  currency: z.string(),
  sourceNote: z.string().nullable(),
  claimedAllocations: z.array(z.object({ member: memberRef, sharePercent: z.string() })),
  shiftId: uuid.nullable(),
  duplicate: z.object({ entryId: uuid, title: z.string(), state: z.string() }).nullable(),
  reviewNote: z.string().nullable(),
  reviewedAt: isoDateTime.nullable(),
  reviewedBy: memberRef.nullable(),
  financialEntryId: uuid.nullable(),
  createdAt: isoDateTime,
  rowVersion: z.number().int(),
});
export type SaleCandidateView = z.infer<typeof saleCandidateView>;

// ——— Overview ———

const kpis = z.object({
  grossRevenue: money,
  refunds: money,
  fees: money,
  netRevenue: money,
  operatingExpenses: money,
  compensationExpense: money,
  fxDifference: signedMoney,
  operatingResult: signedMoney,
  /** Operating margin % of gross (null = Not Defined when gross ≤ 0). */
  operatingMarginPercent: z.string().nullable(),
  grossIncomplete: z.boolean(),
  netOnlyRevenue: money,
});

export const financeOverview = z.object({
  periodStart: isoDate,
  periodEnd: isoDate,
  baseCurrency: z.string(),
  accrual: kpis,
  cash: z.array(z.object({ currency: z.string(), inflows: money, outflows: money, movement: signedMoney })),
  drafts: z.object({ count: z.number().int(), submitted: z.number().int(), byCurrency: z.array(signedMoney) }),
  receivables: z.array(money),
  payables: z.array(money),
  outstandingCompensation: z.array(money),
  unallocatedCosts: money,
  costAllocationCoverage: z.string().nullable(),
  sourceMatch: z.object({ reconciled: z.number().int(), eligible: z.number().int(), duplicatesRejected: z.number().int(), ratePercent: z.string().nullable() }),
  unmatchedSettlements: z.number().int(),
  periodLock: z.object({ id: uuid, periodStart: isoDate, periodEnd: isoDate }).nullable(),
  byProject: z.array(z.object({ project: ref.nullable(), netRevenue: signedMoney, costs: money, result: signedMoney })),
});
export type FinanceOverview = z.infer<typeof financeOverview>;

export const projectFinanceSummary = z.object({
  project: ref,
  periodStart: isoDate,
  periodEnd: isoDate,
  baseCurrency: z.string(),
  accrual: kpis.optional(),
  recentEntries: z.array(entryRow).optional(),
  budgets: z.array(budgetRow).optional(),
  commitments: z.array(commitmentView).optional(),
  permissions: z.object({ finance: z.boolean(), budgets: z.boolean(), createEntry: z.boolean() }),
});
export type ProjectFinanceSummary = z.infer<typeof projectFinanceSummary>;

export const dealFinanceSummary = z.object({
  dealId: uuid,
  entries: z.array(entryRow),
  /** Posted income linked to the deal in base currency (omitted without finance.read). */
  postedIncome: money.optional(),
  received: z.array(money).optional(),
  explanation: z.string(),
});

export const campaignFinanceSummary = z.object({
  campaignId: uuid,
  budgets: z.array(budgetRow),
  actual: money.optional(),
  entries: z.array(entryRow).optional(),
});

export const memberCompensation = z.object({
  member: memberRef,
  rules: z.array(ruleRow),
  runs: z.array(
    z.object({
      run: z.object({ id: uuid, periodStart: isoDate, periodEnd: isoDate, state: z.enum(COMPENSATION_RUN_STATES) }),
      lines: z.array(runLineView),
      totals: z.array(runRecipientTotal),
    }),
  ),
  outstanding: z.array(money),
  carryForward: z.array(signedMoney),
  pendingAdjustments: z.array(adjustmentView),
});
export type MemberCompensation = z.infer<typeof memberCompensation>;

// ——— Endpoints ———

const cat = { params: wsId({ categoryId: uuid }) };
const ent = { params: wsId({ entryId: uuid }) };
const stl = { params: wsId({ settlementId: uuid }) };
const bud = { params: wsId({ budgetId: uuid }) };
const com = { params: wsId({ commitmentId: uuid }) };
const rul = { params: wsId({ ruleId: uuid }) };
const run = { params: wsId({ runId: uuid }) };

export const financeEndpoints = {
  // Categories
  categoriesList: endpoint({
    id: 'finance.categories.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/finance/categories',
    summary: 'Finance categories with their fixed accounting class.',
    tags: T,
    auth: 'workspace',
    permission: 'finance.read',
    params: wsId({}),
    query: z.object({ includeArchived: boolQuery.optional() }),
    response: z.array(financeCategory),
  }),
  categoriesCreate: endpoint({
    id: 'finance.categories.create',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/categories',
    summary: 'Extend the category catalogue; the accounting class is fixed once created.',
    tags: T,
    auth: 'workspace',
    permission: 'finance.post',
    idempotent: true,
    params: wsId({}),
    body: z.object({ name: shortName, accountingClass: z.enum(ACCOUNTING_CLASSES) }),
    response: financeCategory,
    successStatus: 201,
  }),
  categoriesUpdate: endpoint({
    id: 'finance.categories.update',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/finance/categories/{categoryId}',
    summary: 'Rename a category (its accounting class never changes).',
    tags: T,
    auth: 'workspace',
    permission: 'finance.post',
    ifMatch: true,
    ...cat,
    body: z.object({ name: shortName.optional(), sortOrder: z.number().int().min(0).max(10000).optional() }),
    response: financeCategory,
  }),
  categoriesArchive: endpoint({
    id: 'finance.categories.archive',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/categories/{categoryId}/archive',
    summary: 'Hide a category from new records; history keeps it.',
    tags: T,
    auth: 'workspace',
    permission: 'finance.post',
    idempotent: true,
    ifMatch: true,
    ...cat,
    body: z.object({ reason: reason.optional(), restore: z.boolean().optional() }),
    response: financeCategory,
  }),

  // FX rates
  fxRatesList: endpoint({
    id: 'finance.fxRates.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/finance/fx-rates',
    summary: 'Manually entered or imported FX rates (no automatic rate API).',
    tags: T,
    auth: 'workspace',
    permission: 'finance.read',
    params: wsId({}),
    query: pageQuery.extend({ fromCurrency: currencyCode.optional(), toCurrency: currencyCode.optional() }),
    response: page(fxRate),
  }),
  fxRatesGet: endpoint({
    id: 'finance.fxRates.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/finance/fx-rates/{rateId}',
    summary: 'One FX rate.',
    tags: T,
    auth: 'workspace',
    permission: 'finance.read',
    params: wsId({ rateId: uuid }),
    response: fxRate,
  }),
  fxRatesCreate: endpoint({
    id: 'finance.fxRates.create',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/fx-rates',
    summary: 'Enter an FX rate with its source and effective date.',
    tags: T,
    auth: 'workspace',
    permission: 'finance.post',
    idempotent: true,
    params: wsId({}),
    body: z.object({ fromCurrency: currencyCode, toCurrency: currencyCode, rate: rateString, effectiveDate: isoDate, source: z.string().trim().min(2).max(200) }),
    response: fxRate,
    successStatus: 201,
  }),
  fxRatesUpdate: endpoint({
    id: 'finance.fxRates.update',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/finance/fx-rates/{rateId}',
    summary: 'Correct an unused rate. Used rates are frozen: enter a new rate instead.',
    tags: T,
    auth: 'workspace',
    permission: 'finance.post',
    ifMatch: true,
    params: wsId({ rateId: uuid }),
    body: z.object({ rate: rateString.optional(), source: z.string().trim().min(2).max(200).optional() }),
    response: fxRate,
  }),

  // Entries
  entriesList: endpoint({
    id: 'finance.entries.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/finance/entries',
    summary: 'Ledger documents in the member’s finance scope (filters, cursor pagination).',
    tags: T,
    auth: 'workspace',
    permission: 'finance.read',
    params: wsId({}),
    query: entryListQuery,
    response: page(entryRow),
  }),
  entriesGet: endpoint({
    id: 'finance.entries.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/finance/entries/{entryId}',
    summary: 'Financial entry with lines, allocations, FX, settlements, attributions and allowed actions.',
    tags: T,
    auth: 'workspace',
    permission: 'finance.read',
    ...ent,
    response: entryDetail,
  }),
  entriesCreate: endpoint({
    id: 'finance.entries.create',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/entries',
    summary: 'Save a draft entry (FX may be missing; posting is a separate command).',
    tags: T,
    auth: 'workspace',
    permission: 'finance.create',
    idempotent: true,
    params: wsId({}),
    body: z.object(entryFields),
    response: entryDetail,
    successStatus: 201,
  }),
  entriesUpdate: endpoint({
    id: 'finance.entries.update',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/finance/entries/{entryId}',
    summary: 'Edit a draft or rejected entry. Posted entries are immutable (reverse / replace instead).',
    tags: T,
    auth: 'workspace',
    permission: 'finance.create',
    ifMatch: true,
    ...ent,
    body: z.object(entryFields).partial(),
    response: entryDetail,
  }),
  entriesSubmit: endpoint({
    id: 'finance.entries.submit',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/entries/{entryId}/submit',
    summary: 'Submit a draft for review by an authorised finance member.',
    tags: T,
    auth: 'workspace',
    permission: 'finance.submit',
    idempotent: true,
    ifMatch: true,
    ...ent,
    body: z.object({ note: z.string().max(2000).optional() }),
    response: entryDetail,
  }),
  entriesPost: endpoint({
    id: 'finance.entries.post',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/entries/{entryId}/post',
    summary: 'Post atomically: period, FX, source uniqueness, allocation sums and attachment checks; recent authentication.',
    tags: T,
    auth: 'workspace',
    permission: 'finance.post',
    idempotent: true,
    ifMatch: true,
    ...ent,
    body: z.object({ approverNote: z.string().max(2000).optional(), exceptionReason: reason.optional() }),
    response: entryDetail,
  }),
  entriesReject: endpoint({
    id: 'finance.entries.reject',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/entries/{entryId}/reject',
    summary: 'Reject a submitted entry with a reason; the author is notified.',
    tags: T,
    auth: 'workspace',
    permission: 'finance.post',
    idempotent: true,
    ifMatch: true,
    ...ent,
    body: z.object({ reason }),
    response: entryDetail,
  }),
  entriesReverse: endpoint({
    id: 'finance.entries.reverse',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/entries/{entryId}/reverse',
    summary: 'Post a linked reversing entry (the original stays in history); optionally open a replacement draft.',
    tags: T,
    auth: 'workspace',
    permission: 'finance.reverse',
    idempotent: true,
    ifMatch: true,
    ...ent,
    body: z.object({ reason, effectiveDate: isoDate, createReplacement: z.boolean().optional() }),
    response: z.object({ original: entryDetail, reversal: entryDetail, replacementId: uuid.nullable() }),
  }),
  entriesAllocationPreview: endpoint({
    id: 'finance.entries.allocationPreview',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/entries/{entryId}/allocation-preview',
    summary: 'Balanced allocation preview (exact minor units) and a token to apply it.',
    tags: T,
    auth: 'workspace',
    permission: 'finance.allocate',
    ...ent,
    body: z.object({ allocation: allocationSpec, lineIds: z.array(uuid).max(200).optional(), effectiveDate: isoDate.optional() }),
    response: z.object({
      previewToken: z.string(),
      expiresAt: isoDateTime,
      mode: z.enum(['draft_edit', 'posted_adjustment']),
      lines: z.array(z.object({ lineId: uuid, amount: money, rows: z.array(z.object({ project: ref.nullable(), campaign: ref.nullable(), amount: money, baseAmount: money.nullable() })) })),
    }),
  }),
  entriesAllocate: endpoint({
    id: 'finance.entries.allocate',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/entries/{entryId}/allocate',
    summary: 'Apply a previewed allocation: draft edit, or an adjustment for posted entries (no copy of the expense).',
    tags: T,
    auth: 'workspace',
    permission: 'finance.allocate',
    idempotent: true,
    ifMatch: true,
    ...ent,
    body: z.object({ previewToken: z.string().max(4000) }),
    response: entryDetail,
  }),
  entriesSetAttributions: endpoint({
    id: 'finance.entries.setAttributions',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/entries/{entryId}/attributions',
    summary: 'Manager attribution of revenue (shares ≤ 100 %, remainder Unassigned). Never set automatically.',
    tags: T,
    auth: 'workspace',
    permission: 'finance.allocate',
    idempotent: true,
    ifMatch: true,
    ...ent,
    body: z.object({ attributions: z.array(z.object({ membershipId: uuid, sharePercent: percent })).max(50), reason: reason.optional() }),
    response: entryDetail,
  }),

  // Settlements
  settlementsList: endpoint({
    id: 'finance.settlements.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/finance/settlements',
    summary: 'Money actually received or paid, with allocation state.',
    tags: T,
    auth: 'workspace',
    permission: 'finance.read',
    params: wsId({}),
    query: pageQuery.extend({
      direction: z.enum(SETTLEMENT_DIRECTIONS).optional(),
      state: csv(z.enum(SETTLEMENT_STATES)).optional(),
      from: isoDate.optional(),
      to: isoDate.optional(),
      unmatched: boolQuery.optional(),
      q: z.string().trim().max(120).optional(),
      entryId: uuid.optional(),
      runId: uuid.optional(),
    }),
    response: page(settlementRow),
  }),
  settlementsGet: endpoint({
    id: 'finance.settlements.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/finance/settlements/{settlementId}',
    summary: 'Settlement with allocations and history.',
    tags: T,
    auth: 'workspace',
    permission: 'finance.read',
    ...stl,
    response: settlementDetail,
  }),
  settlementsCreate: endpoint({
    id: 'finance.settlements.create',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/settlements',
    summary: 'Register a settlement draft. This records a payment already made. It does not transfer money.',
    tags: T,
    auth: 'workspace',
    permission: 'settlements.create',
    idempotent: true,
    params: wsId({}),
    body: z.object(settlementFields),
    response: settlementDetail,
    successStatus: 201,
  }),
  settlementsUpdate: endpoint({
    id: 'finance.settlements.update',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/finance/settlements/{settlementId}',
    summary: 'Edit a draft settlement.',
    tags: T,
    auth: 'workspace',
    permission: 'settlements.create',
    ifMatch: true,
    ...stl,
    body: z.object(settlementFields).partial(),
    response: settlementDetail,
  }),
  settlementsConfirm: endpoint({
    id: 'finance.settlements.confirm',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/settlements/{settlementId}/confirm',
    summary: 'Confirm the cash fact and allocate it; an excess needs an explicit advance/unallocated remainder.',
    tags: T,
    auth: 'workspace',
    permission: 'settlements.confirm',
    idempotent: true,
    ifMatch: true,
    ...stl,
    body: z.object({
      allocationLines: z.array(settlementAllocationInput).max(100),
      remainderPolicy: z.enum(['none', 'advance', 'unallocated']).default('none'),
      remainderNote: z.string().trim().max(500).optional(),
    }),
    response: settlementDetail,
  }),
  settlementsMatch: endpoint({
    id: 'finance.settlements.match',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/settlements/{settlementId}/match',
    summary: 'Allocate the unmatched balance of a confirmed settlement.',
    tags: T,
    auth: 'workspace',
    permission: 'settlements.confirm',
    idempotent: true,
    ifMatch: true,
    ...stl,
    body: z.object({ allocationLines: z.array(settlementAllocationInput).min(1).max(100) }),
    response: settlementDetail,
  }),
  settlementsReverseAllocation: endpoint({
    id: 'finance.settlements.reverseAllocation',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/settlements/{settlementId}/allocations/{allocationId}/reverse',
    summary: 'Reverse one allocation: the outstanding balance is restored, the settlement keeps its history.',
    tags: T,
    auth: 'workspace',
    permission: 'settlements.reverse',
    idempotent: true,
    ifMatch: true,
    params: wsId({ settlementId: uuid, allocationId: uuid }),
    body: z.object({ reason }),
    response: settlementDetail,
  }),
  settlementsReverse: endpoint({
    id: 'finance.settlements.reverse',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/settlements/{settlementId}/reverse',
    summary: 'Reverse a confirmed settlement without deleting it.',
    tags: T,
    auth: 'workspace',
    permission: 'settlements.reverse',
    idempotent: true,
    ifMatch: true,
    ...stl,
    body: z.object({ reason, effectiveDate: isoDate }),
    response: settlementDetail,
  }),
  openItems: endpoint({
    id: 'finance.openItems.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/finance/open-items',
    summary: 'Posted documents and approved runs with an outstanding balance (matching targets).',
    tags: T,
    auth: 'workspace',
    permission: 'finance.read',
    params: wsId({}),
    query: z.object({ direction: z.enum(SETTLEMENT_DIRECTIONS), currency: currencyCode.optional(), q: z.string().trim().max(120).optional(), limit: z.coerce.number().int().min(1).max(200).default(50) }),
    response: z.array(openItem),
  }),

  // Budgets
  budgetsList: endpoint({
    id: 'finance.budgets.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/finance/budgets',
    summary: 'Budgets with planned / committed / actual / remaining of the approved version.',
    tags: T,
    auth: 'workspace',
    permission: 'budgets.read',
    params: wsId({}),
    query: pageQuery.extend({
      q: z.string().trim().max(120).optional(),
      scopeType: budgetScopeType.optional(),
      projectId: uuid.optional(),
      campaignId: uuid.optional(),
      activeOn: isoDate.optional(),
      includeArchived: boolQuery.optional(),
    }),
    response: page(budgetRow),
  }),
  budgetsGet: endpoint({
    id: 'finance.budgets.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/finance/budgets/{budgetId}',
    summary: 'Budget with versions, category figures, alerts.',
    tags: T,
    auth: 'workspace',
    permission: 'budgets.read',
    ...bud,
    response: budgetDetail,
  }),
  budgetsCreate: endpoint({
    id: 'finance.budgets.create',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/budgets',
    summary: 'New budget with a draft version.',
    tags: T,
    auth: 'workspace',
    permission: 'budgets.write',
    idempotent: true,
    params: wsId({}),
    body: z.object({
      name: shortName,
      scopeType: budgetScopeType,
      scopeId: uuid.nullable().optional(),
      periodStart: isoDate,
      periodEnd: isoDate,
      currency: currencyCode,
      ownerMembershipId: uuid,
      alertThresholds: z.array(z.number().int().min(1).max(1000)).max(10).optional(),
      lines: z.array(budgetLineInput).max(100),
    }),
    response: budgetDetail,
    successStatus: 201,
  }),
  budgetsUpdate: endpoint({
    id: 'finance.budgets.update',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/finance/budgets/{budgetId}',
    summary: 'Edit name, owner, alert thresholds and the lines of the draft version (approved versions are immutable).',
    tags: T,
    auth: 'workspace',
    permission: 'budgets.write',
    ifMatch: true,
    ...bud,
    body: z.object({
      name: shortName.optional(),
      ownerMembershipId: uuid.optional(),
      alertThresholds: z.array(z.number().int().min(1).max(1000)).max(10).optional(),
      lines: z.array(budgetLineInput).max(100).optional(),
    }),
    response: budgetDetail,
  }),
  budgetsSubmit: endpoint({
    id: 'finance.budgets.submit',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/budgets/{budgetId}/submit',
    summary: 'Submit the draft version for approval.',
    tags: T,
    auth: 'workspace',
    permission: 'budgets.write',
    idempotent: true,
    ifMatch: true,
    ...bud,
    body: z.object({ versionId: uuid }),
    response: budgetDetail,
  }),
  budgetsApprove: endpoint({
    id: 'finance.budgets.approve',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/budgets/{budgetId}/approve',
    summary: 'Approve a version; it becomes the current budget, the previous approved version is superseded.',
    tags: T,
    auth: 'workspace',
    permission: 'budgets.approve',
    idempotent: true,
    ifMatch: true,
    ...bud,
    body: z.object({ versionId: uuid }),
    response: budgetDetail,
  }),
  budgetsRevise: endpoint({
    id: 'finance.budgets.revise',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/budgets/{budgetId}/versions',
    summary: 'Create a revised draft version (actual costs are not changed by a revision).',
    tags: T,
    auth: 'workspace',
    permission: 'budgets.write',
    idempotent: true,
    ifMatch: true,
    ...bud,
    body: z.object({ lines: z.array(budgetLineInput).max(100), reason }),
    response: budgetDetail,
  }),
  budgetsCopy: endpoint({
    id: 'finance.budgets.copy',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/budgets/{budgetId}/copy',
    summary: 'Copy Budget: a draft for the next period with an explicit carry-over choice (nothing carries over by itself).',
    tags: T,
    auth: 'workspace',
    permission: 'budgets.write',
    idempotent: true,
    ...bud,
    body: z.object({ name: shortName, periodStart: isoDate, periodEnd: isoDate, carryOver: z.enum(['planned', 'add_unused_remaining', 'empty']) }),
    response: budgetDetail,
    successStatus: 201,
  }),
  budgetsResetAlert: endpoint({
    id: 'finance.budgets.resetAlert',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/budgets/{budgetId}/alerts/{alertId}/reset',
    summary: 'Explicitly reset a threshold alert (only when spending is back below the threshold).',
    tags: T,
    auth: 'workspace',
    permission: 'budgets.write',
    idempotent: true,
    params: wsId({ budgetId: uuid, alertId: uuid }),
    body: z.object({ reason }),
    response: budgetDetail,
  }),

  // Commitments
  commitmentsList: endpoint({
    id: 'finance.commitments.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/finance/commitments',
    summary: 'Committed but not yet posted costs, with remaining and consumed amounts.',
    tags: T,
    auth: 'workspace',
    permission: 'budgets.read',
    params: wsId({}),
    query: pageQuery.extend({ projectId: uuid.optional(), budgetId: uuid.optional(), state: csv(z.enum(COMMITMENT_STATES)).optional() }),
    response: page(commitmentView),
  }),
  commitmentsGet: endpoint({
    id: 'finance.commitments.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/finance/commitments/{commitmentId}',
    summary: 'One commitment with its consumption history.',
    tags: T,
    auth: 'workspace',
    permission: 'budgets.read',
    ...com,
    response: commitmentView,
  }),
  commitmentsCreate: endpoint({
    id: 'finance.commitments.create',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/commitments',
    summary: 'Record a confirmed commitment (not an expense).',
    tags: T,
    auth: 'workspace',
    permission: 'budgets.write',
    idempotent: true,
    params: wsId({}),
    body: z.object(commitmentFields),
    response: commitmentView,
    successStatus: 201,
  }),
  commitmentsUpdate: endpoint({
    id: 'finance.commitments.update',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/finance/commitments/{commitmentId}',
    summary: 'Edit an open commitment (the amount cannot drop below the consumed part).',
    tags: T,
    auth: 'workspace',
    permission: 'budgets.write',
    ifMatch: true,
    ...com,
    body: z.object(commitmentFields).partial(),
    response: commitmentView,
  }),
  commitmentsCancel: endpoint({
    id: 'finance.commitments.cancel',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/commitments/{commitmentId}/cancel',
    summary: 'Cancel the remaining commitment with a reason.',
    tags: T,
    auth: 'workspace',
    permission: 'budgets.write',
    idempotent: true,
    ifMatch: true,
    ...com,
    body: z.object({ reason }),
    response: commitmentView,
  }),
  commitmentsConvert: endpoint({
    id: 'finance.commitments.convert',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/commitments/{commitmentId}/convert',
    summary: 'Create a draft expense for the remaining commitment; posting it consumes the commitment.',
    tags: T,
    auth: 'workspace',
    permission: 'finance.create',
    idempotent: true,
    ...com,
    body: z.object({ amount: decimalString.optional(), recognitionDate: isoDate, title: shortName.optional() }),
    response: entryDetail,
    successStatus: 201,
  }),

  // Compensation rules
  rulesList: endpoint({
    id: 'finance.compensationRules.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/finance/compensation-rules',
    summary: 'Compensation rules with current and draft versions.',
    tags: T,
    auth: 'workspace',
    permission: 'compensation.rules.read',
    params: wsId({}),
    query: pageQuery.extend({
      q: z.string().trim().max(120).optional(),
      recipientMembershipId: uuid.optional(),
      type: csv(z.enum(COMPENSATION_RULE_TYPES)).optional(),
      includeArchived: boolQuery.optional(),
    }),
    response: page(ruleRow),
  }),
  rulesGet: endpoint({
    id: 'finance.compensationRules.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/finance/compensation-rules/{ruleId}',
    summary: 'Rule with its version history and affected runs.',
    tags: T,
    auth: 'workspace',
    permission: 'compensation.rules.read',
    ...rul,
    response: ruleDetail,
  }),
  rulesCreate: endpoint({
    id: 'finance.compensationRules.create',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/compensation-rules',
    summary: 'Create a rule with its first draft version.',
    tags: T,
    auth: 'workspace',
    permission: 'compensation.rules.write',
    idempotent: true,
    params: wsId({}),
    body: z.object({
      name: shortName,
      recipientScopeType: z.enum(['member', 'role']),
      recipientMembershipId: uuid.nullable().optional(),
      recipientRoleId: uuid.nullable().optional(),
      componentKey: z.string().trim().min(2).max(60).regex(/^[a-z0-9_]+$/, 'Use lowercase letters, digits and _'),
      stackGroup: z.string().trim().min(2).max(60).nullable().optional(),
      version: ruleVersionInput,
    }),
    response: ruleDetail,
    successStatus: 201,
  }),
  rulesCreateVersion: endpoint({
    id: 'finance.compensationRules.createVersion',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/compensation-rules/{ruleId}/versions',
    summary: 'Create a new draft version (approved versions are never overwritten).',
    tags: T,
    auth: 'workspace',
    permission: 'compensation.rules.write',
    idempotent: true,
    ifMatch: true,
    ...rul,
    body: z.object({ version: ruleVersionInput, stackGroup: z.string().trim().min(2).max(60).nullable().optional(), name: shortName.optional() }),
    response: ruleDetail,
  }),
  rulesApprove: endpoint({
    id: 'finance.compensationRules.approve',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/compensation-rules/{ruleId}/approve',
    summary: 'Approve a version: immutable and effective; overlapping incompatible rules are blocked.',
    tags: T,
    auth: 'workspace',
    permission: 'compensation.rules.approve',
    idempotent: true,
    ifMatch: true,
    ...rul,
    body: z.object({ versionId: uuid }),
    response: ruleDetail,
  }),
  rulesEnd: endpoint({
    id: 'finance.compensationRules.end',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/compensation-rules/{ruleId}/end',
    summary: 'End the approved version at a date (exclusive end).',
    tags: T,
    auth: 'workspace',
    permission: 'compensation.rules.approve',
    idempotent: true,
    ifMatch: true,
    ...rul,
    body: z.object({ versionId: uuid, effectiveTo: isoDate, reason }),
    response: ruleDetail,
  }),
  rulesSimulate: endpoint({
    id: 'finance.compensationRules.simulate',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/compensation-rules/{ruleId}/simulate',
    summary: 'Compute a preview for a period. Nothing is accrued.',
    tags: T,
    auth: 'workspace',
    permission: 'compensation.rules.read',
    ...rul,
    body: z.object({ versionId: uuid, periodStart: isoDate, periodEnd: isoDate }),
    response: z.object({
      lines: z.array(runLineView),
      totals: z.array(z.object({ recipient: memberRef, currency: z.string(), total: signedMoney })),
      conflicts: z.array(z.object({ versionId: uuid, ruleId: uuid, code: z.string(), message: z.string() })),
      stack: z.object({ revenueSharePercent: z.string(), rules: z.array(z.object({ versionId: uuid, ruleId: uuid, ratePercent: z.string().nullable(), type: z.string(), name: z.string().optional() })) }),
    }),
  }),

  // Compensation runs
  runsList: endpoint({
    id: 'finance.compensationRuns.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/finance/compensation-runs',
    summary: 'Compensation runs by period and state.',
    tags: T,
    auth: 'workspace',
    permission: 'compensation.runs.read',
    params: wsId({}),
    query: pageQuery.extend({ state: csv(z.enum(COMPENSATION_RUN_STATES)).optional(), from: isoDate.optional(), to: isoDate.optional() }),
    response: page(runRow),
  }),
  runsGet: endpoint({
    id: 'finance.compensationRuns.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/finance/compensation-runs/{runId}',
    summary: 'Run with source lines, exclusions, adjustments, totals, diff and payout balance.',
    tags: T,
    auth: 'workspace',
    permission: 'compensation.runs.read',
    ...run,
    response: runDetail,
  }),
  runsCreate: endpoint({
    id: 'finance.compensationRuns.create',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/compensation-runs',
    summary: 'Create a draft run for a period and participants.',
    tags: T,
    auth: 'workspace',
    permission: 'compensation.runs.calculate',
    idempotent: true,
    params: wsId({}),
    body: z.object({ periodStart: isoDate, periodEnd: isoDate, participantMembershipIds: z.array(uuid).min(1).max(200) }),
    response: runDetail,
    successStatus: 201,
  }),
  runsUpdate: endpoint({
    id: 'finance.compensationRuns.update',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/finance/compensation-runs/{runId}',
    summary: 'Change period or participants of a draft/calculated run (recalculation required).',
    tags: T,
    auth: 'workspace',
    permission: 'compensation.runs.calculate',
    ifMatch: true,
    ...run,
    body: z.object({ periodStart: isoDate.optional(), periodEnd: isoDate.optional(), participantMembershipIds: z.array(uuid).min(1).max(200).optional() }),
    response: runDetail,
  }),
  runsCalculate: endpoint({
    id: 'finance.compensationRuns.calculate',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/compensation-runs/{runId}/calculate',
    summary: 'Calculate (or recalculate with diff): snapshot inputs, no accrual until approval.',
    tags: T,
    auth: 'workspace',
    permission: 'compensation.runs.calculate',
    idempotent: true,
    ifMatch: true,
    ...run,
    body: z.object({}),
    response: runDetail,
  }),
  runsSubmit: endpoint({
    id: 'finance.compensationRuns.submit',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/compensation-runs/{runId}/submit',
    summary: 'Submit a calculation version for approval.',
    tags: T,
    auth: 'workspace',
    permission: 'compensation.runs.calculate',
    idempotent: true,
    ifMatch: true,
    ...run,
    body: z.object({ calculationVersion: z.number().int().min(1) }),
    response: runDetail,
  }),
  runsReturn: endpoint({
    id: 'finance.compensationRuns.return',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/compensation-runs/{runId}/return',
    summary: 'Return to draft with a reason; the prior calculation is kept.',
    tags: T,
    auth: 'workspace',
    permission: 'compensation.runs.approve',
    idempotent: true,
    ifMatch: true,
    ...run,
    body: z.object({ reason }),
    response: runDetail,
  }),
  runsApprove: endpoint({
    id: 'finance.compensationRuns.approve',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/compensation-runs/{runId}/approve',
    summary: 'Approve: entitlement claims and exactly one linked compensation expense document; recent authentication.',
    tags: T,
    auth: 'workspace',
    permission: 'compensation.runs.approve',
    idempotent: true,
    ifMatch: true,
    ...run,
    body: z.object({
      calculationVersion: z.number().int().min(1),
      sourceDigest: z.string().min(8).max(200),
      exceptionReason: reason.optional(),
      /** Link Existing/Reconcile: a manually recorded compensation expense for exactly this run. */
      linkExistingEntryId: uuid.optional(),
      /** Confirms that manual compensation expenses in the period are unrelated to this run. */
      unrelatedManualEntriesReason: reason.optional(),
    }),
    response: runDetail,
  }),
  runsCancel: endpoint({
    id: 'finance.compensationRuns.cancel',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/compensation-runs/{runId}/cancel',
    summary: 'Cancel a run before approval.',
    tags: T,
    auth: 'workspace',
    permission: 'compensation.runs.calculate',
    idempotent: true,
    ifMatch: true,
    ...run,
    body: z.object({ reason }),
    response: runDetail,
  }),
  runsAddAdjustment: endpoint({
    id: 'finance.compensationRuns.addAdjustment',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/compensation-runs/{runId}/adjustments',
    summary: 'Manual bonus / adjustment as a separate line with reason (never an edit of a calculated total).',
    tags: T,
    auth: 'workspace',
    permission: 'compensation.runs.calculate',
    idempotent: true,
    ...run,
    body: z.object({
      recipientMembershipId: uuid,
      amount: decimalString,
      currency: currencyCode,
      kind: z.enum(['manual_bonus', 'manual_adjustment']),
      reason,
      originalEntitlementKey: z.string().max(400).optional(),
    }),
    response: runDetail,
    successStatus: 201,
  }),
  adjustmentsReverse: endpoint({
    id: 'finance.compensationRuns.reverseAdjustment',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/compensation-adjustments/{adjustmentId}/reverse',
    summary: 'Withdraw a draft adjustment, or reverse an approved one through a new adjustment in the next open run.',
    tags: T,
    auth: 'workspace',
    permission: 'compensation.runs.calculate',
    idempotent: true,
    params: wsId({ adjustmentId: uuid }),
    body: z.object({ reason }),
    response: adjustmentView,
  }),
  runsRecordPayment: endpoint({
    id: 'finance.compensationRuns.recordPayment',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/compensation-runs/{runId}/payments',
    summary: 'Record Payment: This records a payment already made. It does not transfer money.',
    tags: T,
    auth: 'workspace',
    permission: 'payments.record',
    idempotent: true,
    ...run,
    body: z.object({
      recipientMembershipId: uuid,
      amount: decimalString,
      currency: currencyCode,
      paidAt: isoDateTime,
      paymentReference: z.string().trim().min(1).max(200).nullable().optional(),
      note: z.string().max(2000).nullable().optional(),
    }),
    response: runDetail,
    successStatus: 201,
  }),
  memberCompensation: endpoint({
    id: 'finance.memberCompensation.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/finance/members/{membershipId}/compensation',
    summary: 'Pay slips, rules and outstanding balance of one member (own data with compensation.own.read).',
    tags: T,
    auth: 'workspace',
    permission: 'compensation.own.read',
    params: wsId({ membershipId: uuid }),
    response: memberCompensation,
  }),

  // Periods
  periodsList: endpoint({
    id: 'finance.periods.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/finance/periods',
    summary: 'Period locks and reopen history.',
    tags: T,
    auth: 'workspace',
    permission: 'finance.read',
    params: wsId({}),
    response: z.array(periodLockView),
  }),
  periodsClosePreview: endpoint({
    id: 'finance.periods.closePreview',
    method: 'GET',
    path: '/workspaces/{workspaceId}/finance/periods/close-preview',
    summary: 'Issues to resolve or acknowledge before closing a period.',
    tags: T,
    auth: 'workspace',
    permission: 'finance.close-period',
    params: wsId({}),
    query: z.object({ periodStart: isoDate, periodEnd: isoDate }),
    response: z.object({ periodStart: isoDate, periodEnd: isoDate, issues: z.array(periodIssue), overlapsLock: z.boolean() }),
  }),
  periodsClose: endpoint({
    id: 'finance.periods.close',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/periods/close',
    summary: 'Close a period; posting into it is blocked afterwards. Unresolved items must be acknowledged.',
    tags: T,
    auth: 'workspace',
    permission: 'finance.close-period',
    idempotent: true,
    params: wsId({}),
    body: z.object({
      periodStart: isoDate,
      periodEnd: isoDate,
      unresolvedAcknowledgements: z.array(z.object({ kind: periodIssue.shape.kind, note: z.string().trim().min(3).max(500) })).max(10),
    }),
    response: periodLockView,
    successStatus: 201,
  }),
  periodsReopen: endpoint({
    id: 'finance.periods.reopen',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/periods/reopen',
    summary: 'Audited reopen with a reason; reports built on the period are marked stale.',
    tags: T,
    auth: 'workspace',
    permission: 'finance.close-period',
    idempotent: true,
    params: wsId({}),
    body: z.object({ periodId: uuid, reason }),
    response: periodLockView,
  }),

  // Sale candidates reconciliation
  saleCandidatesList: endpoint({
    id: 'finance.saleCandidates.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/finance/sale-candidates',
    summary: 'Reconciliation queue of OFM sale candidates with duplicate detection.',
    tags: T,
    auth: 'workspace',
    permission: 'sale-candidates.review',
    params: wsId({}),
    query: pageQuery.extend({ state: csv(z.enum(SALE_CANDIDATE_STATES)).optional(), projectId: uuid.optional(), accountId: uuid.optional() }),
    response: page(saleCandidateView),
  }),
  saleCandidatesConfirm: endpoint({
    id: 'finance.saleCandidates.confirm',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/sale-candidates/{candidateId}/confirm',
    summary: 'Verify into a Draft revenue entry (never posted automatically); duplicates of an existing source are blocked.',
    tags: T,
    auth: 'workspace',
    permission: 'sale-candidates.review',
    idempotent: true,
    ifMatch: true,
    params: wsId({ candidateId: uuid }),
    body: z.object({
      categoryId: uuid,
      recognitionDate: isoDate.optional(),
      attributions: z.array(z.object({ membershipId: uuid, sharePercent: percent })).max(20),
      note: z.string().max(2000).optional(),
    }),
    response: z.object({ candidate: saleCandidateView, entry: entryDetail }),
  }),
  saleCandidatesReject: endpoint({
    id: 'finance.saleCandidates.reject',
    method: 'POST',
    path: '/workspaces/{workspaceId}/finance/sale-candidates/{candidateId}/reject',
    summary: 'Reject with a reason; the candidate never enters revenue.',
    tags: T,
    auth: 'workspace',
    permission: 'sale-candidates.review',
    idempotent: true,
    ifMatch: true,
    params: wsId({ candidateId: uuid }),
    body: z.object({ reason }),
    response: saleCandidateView,
  }),

  // Read models
  overview: endpoint({
    id: 'finance.overview.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/finance/overview',
    summary: 'Accrual and cash results by posted records (drafts separate), receivables, payables, coverage.',
    tags: T,
    auth: 'workspace',
    permission: 'finance.read',
    params: wsId({}),
    query: z.object({ periodStart: isoDate, periodEnd: isoDate, projectId: uuid.optional() }),
    response: financeOverview,
  }),
  projectSummary: endpoint({
    id: 'finance.projectSummary.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/finance/projects/{projectId}/summary',
    summary: 'Project workspace Finance tab: results, recent entries, budgets and commitments within the member’s rights.',
    tags: T,
    auth: 'workspace',
    permission: 'finance.read',
    params: wsId({ projectId: uuid }),
    query: z.object({ periodStart: isoDate, periodEnd: isoDate }),
    response: projectFinanceSummary,
  }),
  dealSummary: endpoint({
    id: 'finance.dealSummary.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/finance/deals/{dealId}/summary',
    summary: 'Financial entries linked to a deal. A won deal never creates income by itself.',
    tags: T,
    auth: 'workspace',
    permission: 'deals.read',
    params: wsId({ dealId: uuid }),
    response: dealFinanceSummary,
  }),
  campaignSummary: endpoint({
    id: 'finance.campaignSummary.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/finance/campaigns/{campaignId}/summary',
    summary: 'Campaign budget tab: campaign budgets and allocated actual costs.',
    tags: T,
    auth: 'workspace',
    permission: 'budgets.read',
    params: wsId({ campaignId: uuid }),
    response: campaignFinanceSummary,
  }),
};

export type FinanceEndpoints = typeof financeEndpoints;
