import { z } from 'zod';
import { ASSET_KINDS, ASSET_VERSION_STATUSES, SENSITIVITIES } from '@castlane/domain';
import { endpoint } from './core';
import { boolQuery, csv, httpsUrl, isoDateTime, memberRef, okResponse, page, pageQuery, shortName, tags, uuid, wsId, safeUrl } from './common';

export const uploadTarget = z.object({
  entityType: z.string().max(60),
  entityId: uuid,
  role: z.string().max(40).optional(),
});

export const assetVersionView = z.object({
  id: uuid,
  versionNo: z.number().int(),
  status: z.enum(ASSET_VERSION_STATUSES),
  originalFilename: z.string(),
  mime: z.string().nullable(),
  byteSize: z.number().int().nullable(),
  width: z.number().int().nullable(),
  height: z.number().int().nullable(),
  durationMs: z.number().int().nullable(),
  checksumSha256: z.string().nullable(),
  scan: z.object({ engine: z.string(), clean: z.boolean(), devBypass: z.boolean().optional() }).nullable(),
  rejectionReason: z.string().nullable(),
  note: z.string().nullable(),
  createdAt: isoDateTime,
  createdBy: memberRef.nullable(),
  previewAvailable: z.boolean(),
});

export const assetView = z.object({
  id: uuid,
  name: z.string(),
  kind: z.enum(ASSET_KINDS),
  projectId: uuid.nullable(),
  folderId: uuid.nullable(),
  sensitivity: z.enum(SENSITIVITIES),
  tags: z.array(z.string()),
  description: z.string().nullable(),
  externalUrl: z.string().nullable(),
  currentVersion: assetVersionView.nullable(),
  archivedAt: isoDateTime.nullable(),
  updatedAt: isoDateTime,
  rowVersion: z.number().int(),
  /** Thumbnail URL (authorised endpoint, never a public object URL). Null when no derivative exists or media is restricted. */
  thumbnailUrl: z.string().nullable(),
  canDownload: z.boolean(),
  restrictedHidden: z.boolean(),
});
export type AssetView = z.infer<typeof assetView>;

export const assetDetail = assetView.extend({
  versions: z.array(assetVersionView),
  usage: z.array(z.object({ id: uuid, entityType: z.string(), entityId: uuid, role: z.string(), label: z.string().nullable(), href: z.string().nullable() })),
  hiddenUsageCount: z.number().int(),
  permissions: z.object({ update: z.boolean(), upload: z.boolean(), archive: z.boolean(), link: z.boolean() }),
});

const partUrl = z.object({ partNumber: z.number().int(), url: z.string(), method: z.literal('PUT'), headers: z.record(z.string(), z.string()) });

export const mediaEndpoints = {
  initiateUpload: endpoint({
    id: 'uploads.initiate',
    method: 'POST',
    path: '/workspaces/{workspaceId}/uploads/initiate',
    summary: 'Reserve quota and open a resumable upload session into quarantine (new asset or new version).',
    tags: ['Media'],
    auth: 'workspace',
    permission: 'assets.upload',
    idempotent: true,
    params: wsId({}),
    body: z.object({
      filename: z.string().trim().min(1).max(255),
      mimeType: z.string().max(120),
      byteSize: z.number().int().positive(),
      checksumSha256: z.string().regex(/^[0-9a-f]{64}$/).optional(),
      assetId: uuid.optional(),
      projectId: uuid.nullable().optional(),
      folderId: uuid.nullable().optional(),
      sensitivity: z.enum(SENSITIVITIES).optional(),
      purpose: z.enum(['content', 'avatar', 'logo', 'cover', 'reference', 'evidence', 'document', 'import', 'general']).default('general'),
      target: uploadTarget.optional(),
      note: z.string().max(500).optional(),
    }),
    response: z.object({
      uploadId: uuid,
      assetId: uuid,
      assetVersionId: uuid,
      partSize: z.number().int(),
      partCount: z.number().int(),
      parts: z.array(partUrl),
      expiresAt: isoDateTime,
    }),
    successStatus: 201,
  }),
  resumeUpload: endpoint({
    id: 'uploads.resume',
    method: 'GET',
    path: '/workspaces/{workspaceId}/uploads/{uploadId}',
    summary: 'Parts already stored and fresh credentials for the missing ones (resume within 24 h).',
    tags: ['Media'],
    auth: 'workspace',
    permission: 'assets.upload',
    params: wsId({ uploadId: uuid }),
    response: z.object({
      state: z.string(),
      uploaded: z.array(z.object({ partNumber: z.number().int(), etag: z.string(), size: z.number().int() })),
      missing: z.array(partUrl),
      expiresAt: isoDateTime,
    }),
  }),
  completeUpload: endpoint({
    id: 'uploads.complete',
    method: 'POST',
    path: '/workspaces/{workspaceId}/uploads/{uploadId}/complete',
    summary: 'Assemble parts and queue verification (checksum, type, bounds, malware scan, derivatives).',
    tags: ['Media'],
    auth: 'workspace',
    permission: 'assets.upload',
    idempotent: true,
    params: wsId({ uploadId: uuid }),
    body: z.object({ parts: z.array(z.object({ partNumber: z.number().int().min(1).max(10000), etag: z.string().max(200) })).min(1).max(10000) }),
    response: z.object({ assetId: uuid, assetVersionId: uuid, status: z.enum(ASSET_VERSION_STATUSES) }),
  }),
  abortUpload: endpoint({
    id: 'uploads.abort',
    method: 'POST',
    path: '/workspaces/{workspaceId}/uploads/{uploadId}/abort',
    summary: 'Cancel an upload and release its reservation.',
    tags: ['Media'],
    auth: 'workspace',
    permission: 'assets.upload',
    idempotent: true,
    params: wsId({ uploadId: uuid }),
    body: z.object({ reason: z.string().max(500).optional() }),
    response: okResponse,
  }),
  externalLink: endpoint({
    id: 'assets.externalLink',
    method: 'POST',
    path: '/workspaces/{workspaceId}/assets/external-links',
    summary: 'Register an external link as a metadata-only asset (never fetched by the server).',
    tags: ['Media'],
    auth: 'workspace',
    permission: 'assets.upload',
    idempotent: true,
    params: wsId({}),
    body: z.object({ url: safeUrl, title: shortName, projectId: uuid.nullable().optional(), folderId: uuid.nullable().optional(), target: uploadTarget.optional() }),
    response: assetView,
    successStatus: 201,
  }),
  list: endpoint({
    id: 'assets.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/assets',
    summary: 'Library listing within the actor’s scope.',
    tags: ['Media'],
    auth: 'workspace',
    permission: 'assets.read',
    params: wsId({}),
    query: pageQuery.extend({
      q: z.string().max(120).optional(),
      projectId: uuid.optional(),
      folderId: uuid.optional(),
      rootOnly: boolQuery.optional(),
      kind: csv(z.enum(ASSET_KINDS)).optional(),
      tag: z.string().max(40).optional(),
      includeArchived: boolQuery.optional(),
    }),
    response: page(assetView),
  }),
  get: endpoint({
    id: 'assets.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/assets/{assetId}',
    summary: 'Asset with versions and permitted usage links (other usages counted, not named).',
    tags: ['Media'],
    auth: 'workspace',
    permission: 'assets.read',
    params: wsId({ assetId: uuid }),
    response: assetDetail,
  }),
  update: endpoint({
    id: 'assets.update',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/assets/{assetId}',
    summary: 'Update metadata (name, tags, description, sensitivity, folder). The stored file never changes.',
    tags: ['Media'],
    auth: 'workspace',
    permission: 'assets.upload',
    ifMatch: true,
    params: wsId({ assetId: uuid }),
    body: z.object({ name: shortName.optional(), tags: tags.optional(), description: z.string().max(2000).nullable().optional(), sensitivity: z.enum(SENSITIVITIES).optional(), folderId: uuid.nullable().optional() }),
    response: assetView,
  }),
  download: endpoint({
    id: 'assets.download',
    method: 'POST',
    path: '/workspaces/{workspaceId}/assets/{assetId}/download',
    summary: 'Issue a short-lived download credential (≤ 5 min). Restricted files stream through an authorised proxy.',
    tags: ['Media'],
    auth: 'workspace',
    permission: 'assets.download',
    rateLimit: 'download',
    params: wsId({ assetId: uuid }),
    body: z.object({ versionId: uuid.optional() }),
    response: z.object({ url: z.string(), expiresAt: isoDateTime, mode: z.enum(['presigned', 'proxy']) }),
  }),
  link: endpoint({
    id: 'assets.link',
    method: 'POST',
    path: '/workspaces/{workspaceId}/assets/{assetId}/link',
    summary: 'Link an asset (version) to an entity after scope and sensitivity checks.',
    tags: ['Media'],
    auth: 'workspace',
    permission: 'assets.link',
    idempotent: true,
    params: wsId({ assetId: uuid }),
    body: z.object({ versionId: uuid.optional(), target: uploadTarget }),
    response: z.object({ linkId: uuid }),
  }),
  removeLink: endpoint({
    id: 'assets.removeLink',
    method: 'POST',
    path: '/workspaces/{workspaceId}/asset-links/{linkId}/remove',
    summary: 'Remove one usage link (the file itself stays).',
    tags: ['Media'],
    auth: 'workspace',
    permission: 'assets.link',
    idempotent: true,
    params: wsId({ linkId: uuid }),
    body: z.object({ reason: z.string().max(500).optional() }),
    response: okResponse,
  }),
  thumbnail: endpoint({
    id: 'assets.thumbnail',
    method: 'GET',
    path: '/workspaces/{workspaceId}/assets/{assetId}/thumbnail',
    summary: 'Authorised derivative (image bytes). Restricted media only with permission and explicit reveal.',
    tags: ['Media'],
    auth: 'workspace',
    permission: 'assets.read',
    rateLimit: 'none',
    params: wsId({ assetId: uuid }),
    query: z.object({ size: z.coerce.number().int().default(256), versionId: uuid.optional(), reveal: boolQuery.optional() }),
    response: z.any(),
  }),
  content: endpoint({
    id: 'assets.content',
    method: 'GET',
    path: '/workspaces/{workspaceId}/assets/{assetId}/versions/{versionId}/content',
    summary: 'Authorised streaming proxy for originals (restricted media, filesystem driver, inline preview). Supports Range.',
    tags: ['Media'],
    auth: 'workspace',
    permission: 'assets.read',
    rateLimit: 'none',
    params: wsId({ assetId: uuid, versionId: uuid }),
    query: z.object({ token: z.string().max(400), disposition: z.enum(['inline', 'attachment']).default('inline') }),
    response: z.any(),
  }),
  archive: endpoint({
    id: 'assets.archive',
    method: 'POST',
    path: '/workspaces/{workspaceId}/assets/{assetId}/archive',
    summary: 'Hide from browsing; historical references keep working.',
    tags: ['Media'],
    auth: 'workspace',
    permission: 'assets.archive',
    idempotent: true,
    ifMatch: true,
    params: wsId({ assetId: uuid }),
    body: z.object({ reason: z.string().max(500).optional() }),
    response: assetView,
  }),
};
