import { z } from 'zod';
import {
  CONTACT_STAGES,
  COVERAGE_LANES,
  HANDOVER_ITEM_STATES,
  HANDOVER_STATES,
  INTERACTION_TYPES,
  LIMITS,
  OPERATION_STATUSES,
  OPERATION_TYPES,
  PLATFORMS,
  PROJECT_STATUSES,
  PROJECT_TYPES,
  QUALITY_REVIEW_STATES,
  RESPONSIBILITIES,
  SALE_CANDIDATE_STATES,
  SHIFT_LIMITS,
  SHIFT_REPORT_STATES,
  SHIFT_STATES,
  SWAP_REQUEST_STATES,
  TASK_PRIORITIES,
  TASK_STATUSES,
} from '@castlane/domain';
import { endpoint } from './core';
import {
  boolQuery,
  csv,
  currencyCode,
  decimalString,
  isoDate,
  isoDateTime,
  memberRef,
  page,
  pageQuery,
  percent,
  reason,
  timezone,
  uuid,
  wsId,
} from './common';

/**
 * OFM operations (spec §13, S40–S48). Every endpoint id starts with `ofm.` so cache invalidation
 * by prefix works. Sensitive fields (contact aliases/notes, amounts) are omitted — not nulled —
 * when the member lacks the separate permission.
 */

const tag = ['OFM'];
const ts = isoDateTime;
const tsN = isoDateTime.nullable();
const optionalNote = z.string().trim().max(LIMITS.noteMax).nullable().optional();
const title = z.string().trim().min(LIMITS.taskTitleMin).max(LIMITS.taskTitleMax);
const amount = decimalString;

export const ofmAccountRef = z.object({
  id: uuid,
  /** Handle, display name or canonical URL — never an OFM contact. */
  label: z.string(),
  handle: z.string().nullable(),
  platform: z.enum(PLATFORMS),
  projectId: uuid,
  status: z.string(),
});
export type OfmAccountRef = z.infer<typeof ofmAccountRef>;

export const ofmProjectRef = z.object({ id: uuid, name: z.string() });

// ——— Profiles (models with OFM enabled) ———

export const ofmProfileSettings = z.object({
  handoverRequired: z.boolean(),
  maxShiftAccounts: z.number().int(),
  contactStageLabels: z.record(z.enum(CONTACT_STAGES), z.string()),
});

export const ofmProfileRow = z.object({
  projectId: uuid,
  profileId: uuid.nullable(),
  project: z.object({ id: uuid, name: z.string(), type: z.enum(PROJECT_TYPES), status: z.enum(PROJECT_STATUSES), coverUrl: z.string().nullable() }),
  supervisor: memberRef.nullable(),
  settings: ofmProfileSettings,
  accounts: z.array(ofmAccountRef),
  managers: z.array(memberRef),
  activeShifts: z.number().int(),
  scheduledNext7Days: z.number().int(),
  disabled: z.boolean(),
  /** 0 while no profile row exists yet (send If-Match: 0 to create it). */
  rowVersion: z.number().int(),
  permissions: z.object({ update: z.boolean(), manageAssignments: z.boolean(), schedule: z.boolean() }),
});
export type OfmProfileRow = z.infer<typeof ofmProfileRow>;

// ——— Assignments (S41) ———

export const ASSIGNMENT_STATUS = ['upcoming', 'current', 'ended'] as const;

export const ofmShiftBrief = z.object({
  id: uuid,
  scheduledStart: ts,
  scheduledEnd: ts,
  state: z.enum(SHIFT_STATES),
  member: memberRef,
  primaryAccountId: uuid,
});

export const ofmAssignmentRow = z.object({
  id: uuid,
  project: ofmProjectRef,
  account: ofmAccountRef,
  member: memberRef,
  responsibility: z.enum(RESPONSIBILITIES),
  coverageLane: z.enum(COVERAGE_LANES),
  coverageLaneLabel: z.string().nullable(),
  validFrom: ts,
  validTo: tsN,
  supervisor: memberRef.nullable(),
  handoverRequired: z.boolean(),
  endedAt: tsN,
  endedReason: z.string().nullable(),
  transferredFromId: uuid.nullable(),
  status: z.enum(ASSIGNMENT_STATUS),
  createdAt: ts,
  rowVersion: z.number().int(),
});
export type OfmAssignmentRow = z.infer<typeof ofmAssignmentRow>;

export const ofmAssignmentDetail = ofmAssignmentRow.extend({
  upcomingShifts: z.array(ofmShiftBrief),
  history: z.array(ofmAssignmentRow),
  permissions: z.object({ update: z.boolean(), end: z.boolean(), transfer: z.boolean() }),
});
export type OfmAssignmentDetail = z.infer<typeof ofmAssignmentDetail>;

const laneFields = {
  coverageLane: z.enum(COVERAGE_LANES).default('primary'),
  coverageLaneLabel: z.string().trim().min(2).max(40).nullable().optional(),
};

export const ofmAssignmentImpact = z.object({
  member: memberRef,
  account: ofmAccountRef,
  /** Accounts the member will (or will no longer) see through OFM assignments. */
  gainsAccountAccess: z.boolean(),
  losesAccountAccess: z.boolean(),
  financeAccess: z.literal(false),
  notes: z.array(z.string()),
  /** Scheduled shifts of the member on this account outside the (new) validity interval. */
  shiftsOutsideInterval: z.array(ofmShiftBrief),
});

// ——— Shifts (S42, S43) ———

export const ofmShiftAccount = z.object({
  account: ofmAccountRef,
  isPrimary: z.boolean(),
  coverageLane: z.enum(COVERAGE_LANES),
  coverageLaneLabel: z.string().nullable(),
  /** Confirmed time allocation share (percent) or null (whole-shift only). */
  timeAllocationShare: z.string().nullable(),
});

export const ofmShiftSummary = z.object({
  id: uuid,
  project: ofmProjectRef,
  member: memberRef,
  supervisor: memberRef.nullable(),
  accounts: z.array(ofmShiftAccount),
  primaryAccount: ofmAccountRef,
  scheduledStart: ts,
  scheduledEnd: ts,
  timezone: z.string(),
  state: z.enum(SHIFT_STATES),
  reportState: z.enum(SHIFT_REPORT_STATES),
  actualStart: tsN,
  actualEnd: tsN,
  /** Net seconds (actual − closed breaks); null = Pending (no actual end). */
  netSeconds: z.number().int().nullable(),
  lateMinutes: z.number().int().nullable(),
  /** Why the shift needs supervisor review (forgotten end, not started, overlapping actual time). */
  needsReview: z.string().nullable(),
  parallelCoverage: z.boolean(),
  /** The member has approved leave on the shift's local date (highlight only; nothing is cancelled). */
  onLeave: z.boolean(),
  cancelReason: z.string().nullable(),
  repeatGroupId: uuid.nullable(),
  rowVersion: z.number().int(),
});
export type OfmShiftSummary = z.infer<typeof ofmShiftSummary>;

export const ofmBreak = z.object({ id: uuid, startedAt: ts, endedAt: tsN, reason: z.string().nullable() });

export const ofmReportVersion = z.object({
  id: uuid,
  versionNo: z.number().int(),
  state: z.enum(['draft', 'submitted', 'changes_requested', 'approved']),
  summary: z.string(),
  completedWork: z.string().nullable(),
  issues: z.string().nullable(),
  nextActions: z.string().nullable(),
  accountSections: z.array(z.object({ accountId: uuid, notes: z.string() })),
  /** Manual Report provenance; null = not provided (never 0). */
  counts: z.object({
    conversationsHandled: z.number().int().nullable(),
    followUpsCompleted: z.number().int().nullable(),
    contentRequests: z.number().int().nullable(),
    conversionEvents: z.number().int().nullable(),
  }),
  sourceRefs: z.array(z.object({ label: z.string(), assetId: uuid.optional(), note: z.string().optional() })),
  noOpenItems: z.boolean(),
  handoverId: uuid.nullable(),
  reviewSummary: z.string().nullable(),
  submittedAt: tsN,
  createdAt: ts,
  createdBy: memberRef.nullable(),
  rowVersion: z.number().int(),
});
export type OfmReportVersion = z.infer<typeof ofmReportVersion>;

export const ofmReportDetail = z.object({
  id: uuid,
  shiftId: uuid,
  state: z.enum(SHIFT_REPORT_STATES),
  reviewer: memberRef.nullable(),
  submittedAt: tsN,
  approvedAt: tsN,
  approvedVersionId: uuid.nullable(),
  currentVersion: ofmReportVersion,
  versions: z.array(ofmReportVersion.pick({ id: true, versionNo: true, state: true, submittedAt: true, reviewSummary: true, createdAt: true })),
  /** Sales linked to the shift: Pending Verification separate from confirmed (posted finance). Present only with the right permissions. */
  sales: z
    .object({
      pendingVerification: z.object({ count: z.number().int(), amounts: z.array(z.object({ amount, currency: currencyCode })).optional() }),
      confirmed: z.array(z.object({ amount, currency: currencyCode })).optional(),
    })
    .optional(),
  rowVersion: z.number().int(),
});
export type OfmReportDetail = z.infer<typeof ofmReportDetail>;

export const ofmHandoverSummary = z.object({
  id: uuid,
  fromShift: z.object({ id: uuid, scheduledStart: ts, scheduledEnd: ts, member: memberRef }),
  toShift: z.object({ id: uuid, scheduledStart: ts, member: memberRef }).nullable(),
  recipient: memberRef.nullable(),
  account: ofmAccountRef,
  summary: z.string(),
  state: z.enum(HANDOVER_STATES),
  noOpenItems: z.boolean(),
  submittedAt: tsN,
  acknowledgedAt: tsN,
  acknowledgedBy: memberRef.nullable(),
  itemCounts: z.object({ open: z.number().int(), accepted: z.number().int(), resolved: z.number().int() }),
  highestPriority: z.enum(TASK_PRIORITIES).nullable(),
  createdBy: memberRef.nullable(),
  createdAt: ts,
  rowVersion: z.number().int(),
});
export type OfmHandoverSummary = z.infer<typeof ofmHandoverSummary>;

export const ofmOperationRef = z.object({ id: uuid, title: z.string(), type: z.enum(OPERATION_TYPES), status: z.enum(OPERATION_STATUSES) });
export const ofmTaskRef = z.object({ id: uuid, title: z.string(), status: z.enum(TASK_STATUSES), dueAt: tsN });

export const ofmHandoverItem = z.object({
  id: uuid,
  title: z.string(),
  businessExplanation: z.string().nullable(),
  priority: z.enum(TASK_PRIORITIES),
  dueAt: tsN,
  state: z.enum(HANDOVER_ITEM_STATES),
  acceptedAt: tsN,
  resolvedAt: tsN,
  task: ofmTaskRef.nullable(),
  operation: ofmOperationRef.nullable(),
  carriedFromItemId: uuid.nullable(),
  rowVersion: z.number().int(),
});

export const ofmHandoverDetail = ofmHandoverSummary.extend({
  items: z.array(ofmHandoverItem),
  permissions: z.object({
    edit: z.boolean(),
    submit: z.boolean(),
    acknowledge: z.boolean(),
    assignRecipient: z.boolean(),
    resolveItems: z.boolean(),
    convertToTask: z.boolean(),
  }),
});
export type OfmHandoverDetail = z.infer<typeof ofmHandoverDetail>;

export const ofmContactRef = z.union([
  z.object({ id: uuid, alias: z.string(), restricted: z.literal(false) }),
  /** The member may not read OFM contacts: only the fact that a contact is linked is shown. */
  z.object({ id: uuid, restricted: z.literal(true) }),
]);

export const ofmOperationSummary = z.object({
  id: uuid,
  type: z.enum(OPERATION_TYPES),
  title: z.string(),
  account: ofmAccountRef,
  project: ofmProjectRef,
  contact: ofmContactRef.nullable(),
  owner: memberRef,
  dueAt: tsN,
  priority: z.enum(TASK_PRIORITIES),
  status: z.enum(OPERATION_STATUSES),
  waitingFor: z.string().nullable(),
  nextCheckAt: tsN,
  outcome: z.string().nullable(),
  cancelReason: z.string().nullable(),
  shift: z.object({ id: uuid, scheduledStart: ts }).nullable(),
  task: ofmTaskRef.nullable(),
  contentItemId: uuid.nullable(),
  promisedDeliverable: z.string().nullable(),
  evidenceAssetIds: z.array(uuid),
  completedAt: tsN,
  overdue: z.boolean(),
  archivedAt: tsN,
  createdAt: ts,
  updatedAt: ts,
  rowVersion: z.number().int(),
});
export type OfmOperationSummary = z.infer<typeof ofmOperationSummary>;

export const ofmOperationDetail = ofmOperationSummary.extend({
  details: z.string().nullable(),
  createdBy: memberRef.nullable(),
  permissions: z.object({
    update: z.boolean(),
    transition: z.boolean(),
    createContentBrief: z.boolean(),
    linkContent: z.boolean(),
    registerSale: z.boolean(),
  }),
  allowedTransitions: z.array(z.enum(OPERATION_STATUSES)),
});
export type OfmOperationDetail = z.infer<typeof ofmOperationDetail>;

export const ofmMoneyParts = z.object({
  gross: amount.nullable(),
  refund: amount.nullable(),
  fee: amount.nullable(),
  net: amount.nullable(),
  currency: currencyCode,
});

/**
 * Sale candidate states consumed by Finance (reconciliation): `pending` (awaiting review, never in
 * revenue), `verified` (a Draft financial entry was created — `financialEntryId`), `rejected`
 * (excluded with `reviewNote`). OFM never posts finance.
 */
export const ofmSaleCandidate = z.object({
  id: uuid,
  account: ofmAccountRef,
  project: ofmProjectRef,
  sourceNamespace: z.string(),
  sourceTransactionId: z.string(),
  manualReference: z.boolean(),
  contact: ofmContactRef.nullable(),
  shift: z.object({ id: uuid, scheduledStart: ts, member: memberRef }).nullable(),
  operationId: uuid.nullable(),
  occurredAt: ts,
  /** Amounts: present only with sale-candidates or finance permissions in scope. */
  money: ofmMoneyParts.optional(),
  currency: currencyCode,
  sourceNote: z.string().nullable(),
  evidenceAssetIds: z.array(uuid),
  claimedAllocations: z.array(z.object({ member: memberRef, sharePercent: z.string() })),
  unassignedPercent: z.string(),
  attributionStatus: z.enum(['unassigned', 'partial', 'full']),
  state: z.enum(SALE_CANDIDATE_STATES),
  reviewNote: z.string().nullable(),
  reviewedBy: memberRef.nullable(),
  reviewedAt: tsN,
  financialEntryId: uuid.nullable(),
  duplicateWarning: z.record(z.string(), z.unknown()).nullable(),
  createdBy: memberRef.nullable(),
  createdAt: ts,
  rowVersion: z.number().int(),
  permissions: z.object({ update: z.boolean() }),
});
export type OfmSaleCandidate = z.infer<typeof ofmSaleCandidate>;

export const ofmSwapRequest = z.object({
  id: uuid,
  shift: ofmShiftBrief,
  from: memberRef,
  proposed: memberRef,
  reason: z.string(),
  state: z.enum(SWAP_REQUEST_STATES),
  acceptedAt: tsN,
  decidedAt: tsN,
  decidedBy: memberRef.nullable(),
  decisionNote: z.string().nullable(),
  createdAt: ts,
  rowVersion: z.number().int(),
  permissions: z.object({ accept: z.boolean(), decline: z.boolean(), approve: z.boolean(), cancel: z.boolean() }),
});
export type OfmSwapRequest = z.infer<typeof ofmSwapRequest>;

export const ofmShiftDetail = ofmShiftSummary.extend({
  breaks: z.array(ofmBreak),
  openBreakId: uuid.nullable(),
  /** Server time when the response was built — the UI timer counts from actual start with this offset. */
  serverNow: ts,
  memberTimezone: z.string(),
  workspaceTimezone: z.string(),
  dst: z.object({ offsetChanges: z.boolean(), elapsedMinutes: z.number().int(), wallClockMinutes: z.number().int() }),
  startOverrideReason: z.string().nullable(),
  noHandoverReason: z.string().nullable(),
  acknowledgedHandoverId: uuid.nullable(),
  endNote: z.string().nullable(),
  aborted: z.boolean(),
  missedConfirmedAt: tsN,
  forgotEndAlertedAt: tsN,
  correctedAt: tsN,
  correctionReason: z.string().nullable(),
  corrections: z.array(z.object({ id: uuid, before: z.record(z.string(), z.unknown()), after: z.record(z.string(), z.unknown()), reason: z.string(), createdAt: ts, by: memberRef.nullable() })),
  incomingHandovers: z.array(ofmHandoverSummary),
  outgoingHandover: ofmHandoverSummary.nullable(),
  tasks: z.array(ofmTaskRef).optional(),
  operations: z.array(ofmOperationSummary),
  interactionsCount: z.number().int().optional(),
  saleCandidates: z.array(ofmSaleCandidate).optional(),
  report: ofmReportDetail.nullable(),
  swapRequests: z.array(ofmSwapRequest),
  earlyStartAllowed: z.boolean(),
  permissions: z.object({
    start: z.boolean(),
    pause: z.boolean(),
    resume: z.boolean(),
    end: z.boolean(),
    cancel: z.boolean(),
    editSchedule: z.boolean(),
    correct: z.boolean(),
    markMissed: z.boolean(),
    allowEarlyStart: z.boolean(),
    requestSwap: z.boolean(),
    editReport: z.boolean(),
    submitReport: z.boolean(),
    approveReport: z.boolean(),
    writeHandover: z.boolean(),
    addOperation: z.boolean(),
    registerSale: z.boolean(),
    logInteraction: z.boolean(),
    setTimeAllocation: z.boolean(),
  }),
});
export type OfmShiftDetail = z.infer<typeof ofmShiftDetail>;

export const ofmScheduleIssue = z.object({
  code: z.string(),
  message: z.string(),
  shiftId: uuid.nullable().optional(),
  accountId: uuid.nullable().optional(),
});

export const ofmShiftValidation = z.object({
  ok: z.boolean(),
  durationMinutes: z.number().int(),
  conflicts: z.array(ofmScheduleIssue),
  assignmentIssues: z.array(ofmScheduleIssue),
  warnings: z.array(ofmScheduleIssue),
  dst: z.object({ offsetChanges: z.boolean(), elapsedMinutes: z.number().int(), wallClockMinutes: z.number().int(), localStart: z.string(), localEnd: z.string() }),
});

const scheduleFields = {
  membershipId: uuid,
  primaryAccountId: uuid,
  additionalAccountIds: z.array(uuid).max(SHIFT_LIMITS.maxAccounts - 1).default([]),
  scheduledStart: ts,
  scheduledEnd: ts,
  timezone,
  supervisorMembershipId: uuid.nullable().optional(),
  /** An extra shift in the same coverage lane of an account must be marked as parallel coverage. */
  parallelCoverage: z.boolean().default(false),
};

export const ofmRepeatPattern = z.object({
  startDate: isoDate,
  weeks: z.number().int().min(1).max(SHIFT_LIMITS.repeatMaxWeeks),
  weekdays: z.array(z.number().int().min(1).max(7)).min(1).max(7),
  startTime: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/, 'Use HH:mm.'),
  endTime: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/, 'Use HH:mm.'),
  timezone,
});

// ——— Contacts (S45, S46) ———

export const ofmContactSummary = z.object({
  id: uuid,
  account: ofmAccountRef,
  project: ofmProjectRef,
  externalIdentifier: z.string(),
  alias: z.string(),
  manager: memberRef.nullable(),
  stage: z.enum(CONTACT_STAGES),
  stageLabel: z.string(),
  lastActivityAt: tsN,
  nextFollowUpAt: tsN,
  restricted: z.boolean(),
  archivedAt: tsN,
  mergedIntoId: uuid.nullable(),
  erasedAt: tsN,
  /** Confirmed spend from posted finance linked through verified sale candidates; only with finance.read. */
  confirmedSpend: z.array(z.object({ amount, currency: currencyCode })).optional(),
  updatedAt: ts,
  rowVersion: z.number().int(),
});
export type OfmContactSummary = z.infer<typeof ofmContactSummary>;

export const ofmInteraction = z.object({
  id: uuid,
  contactId: uuid,
  type: z.enum(INTERACTION_TYPES),
  occurredAt: ts,
  businessNote: z.string(),
  member: memberRef,
  shiftId: uuid.nullable(),
  erasedAt: tsN,
  createdAt: ts,
  updatedAt: ts,
  edited: z.boolean(),
  rowVersion: z.number().int(),
  canEdit: z.boolean(),
});
export type OfmInteraction = z.infer<typeof ofmInteraction>;

export const ofmContactDetail = ofmContactSummary.extend({
  businessNotes: z.string().nullable(),
  operations: z.array(ofmOperationSummary),
  saleCandidates: z.array(ofmSaleCandidate).optional(),
  relations: z.array(
    z.object({
      id: uuid,
      contact: ofmContactRef,
      account: ofmAccountRef.nullable(),
      reason: z.string(),
      createdAt: ts,
    }),
  ),
  erasureRequests: z.array(z.object({ id: uuid, state: z.string(), reason: z.string(), createdAt: ts, completedAt: tsN, result: z.record(z.string(), z.unknown()).nullable() })),
  retentionDeleteAfter: tsN,
  permissions: z.object({
    edit: z.boolean(),
    changeStage: z.boolean(),
    merge: z.boolean(),
    relate: z.boolean(),
    erase: z.boolean(),
    archive: z.boolean(),
    restrict: z.boolean(),
    logInteraction: z.boolean(),
    createOperation: z.boolean(),
    linkSale: z.boolean(),
  }),
});
export type OfmContactDetail = z.infer<typeof ofmContactDetail>;

export const ofmMergePreview = z.object({
  previewToken: z.string(),
  expiresAt: ts,
  source: ofmContactSummary,
  target: ofmContactSummary,
  fields: z.array(z.object({ field: z.enum(['alias', 'managerMembershipId', 'stage', 'nextFollowUpAt', 'businessNotes']), source: z.string().nullable(), target: z.string().nullable(), differs: z.boolean() })),
  moves: z.object({ interactions: z.number().int(), operations: z.number().int(), saleCandidates: z.number().int(), relations: z.number().int() }),
  /** Source transaction ids stay unique: merging never sums amounts or duplicates sales. */
  saleTransactionRefs: z.array(z.object({ sourceNamespace: z.string(), sourceTransactionId: z.string(), state: z.enum(SALE_CANDIDATE_STATES) })),
});

// ——— Quality (S48) ———

export const ofmRubricCriterion = z.object({
  key: z.string().regex(/^[a-z][a-z0-9_]{1,59}$/),
  label: z.string().trim().min(2).max(80),
  weight: percent,
  description: z.string().max(500).optional(),
});

export const ofmRubricVersion = z.object({
  id: uuid,
  name: z.string(),
  rubricKey: z.string(),
  versionNo: z.number().int(),
  criteria: z.array(ofmRubricCriterion),
  state: z.enum(['draft', 'published', 'retired']),
  publishedAt: tsN,
  rowVersion: z.number().int(),
});
export type OfmRubricVersion = z.infer<typeof ofmRubricVersion>;

export const ofmScore = z.object({
  key: z.string(),
  score: z.number().int().min(0).max(4).nullable(),
  note: z.string().max(2000).optional(),
  evidenceAssetIds: z.array(uuid).max(20).optional(),
});

export const ofmQualityDispute = z.object({
  id: uuid,
  raisedBy: memberRef,
  reason: z.string(),
  state: z.enum(['open', 'resolved']),
  decision: z.enum(['upheld', 'revised', 'withdrawn']).nullable(),
  resolution: z.string().nullable(),
  resolvedBy: memberRef.nullable(),
  resolvedAt: tsN,
  replacementReviewId: uuid.nullable(),
  createdAt: ts,
});

export const ofmQualityReview = z.object({
  id: uuid,
  subjectType: z.enum(['shift', 'operation']),
  subject: z.object({ id: uuid, label: z.string(), at: tsN }),
  subjectMember: memberRef,
  reviewer: memberRef,
  project: ofmProjectRef,
  rubric: ofmRubricVersion,
  scores: z.array(ofmScore),
  factualNotes: z.string().nullable(),
  improvements: z.string().nullable(),
  /** Percentage (2 decimals) or null = No Score (all criteria Not Applicable). */
  totalScore: z.string().nullable(),
  applicableCriteria: z.number().int(),
  state: z.enum(QUALITY_REVIEW_STATES),
  publishedAt: tsN,
  acknowledgedAt: tsN,
  employeeResponse: z.string().nullable(),
  revisionOfId: uuid.nullable(),
  supersededAt: tsN,
  replacedById: uuid.nullable(),
  disputes: z.array(ofmQualityDispute),
  createdAt: ts,
  rowVersion: z.number().int(),
  permissions: z.object({
    edit: z.boolean(),
    publish: z.boolean(),
    acknowledge: z.boolean(),
    dispute: z.boolean(),
    resolveDispute: z.boolean(),
    createImprovementTask: z.boolean(),
  }),
});
export type OfmQualityReview = z.infer<typeof ofmQualityReview>;

// ——— Overview (S40) and My Shifts ———

export const ofmAttentionItem = z.object({
  kind: z.enum(['forgotten_end', 'not_started', 'actual_overlap', 'unacknowledged_handover', 'report_pending', 'report_to_review', 'dispute_open', 'operation_overdue', 'swap_pending']),
  title: z.string(),
  entityType: z.enum(['shift', 'handover', 'quality_review', 'operation', 'swap']),
  entityId: uuid,
  at: tsN,
  member: memberRef.nullable(),
});

export const ofmOverview = z.object({
  period: z.object({ from: ts, to: ts }),
  kpis: z.object({
    assignedModels: z.number().int(),
    activeShifts: z.number().int(),
    /** Ended shifts in the period that required a handover but have neither a submitted handover nor "No Open Items". */
    missingHandover: z.object({ count: z.number().int(), requiredShifts: z.number().int() }),
    reportsToReview: z.number().int(),
    openFollowUps: z.number().int(),
    netHours: z.object({ value: z.string().nullable(), endedShifts: z.number().int(), pendingShifts: z.number().int() }),
    handoverCompletion: z.object({ percent: z.string().nullable(), acknowledged: z.number().int(), required: z.number().int() }),
    quality: z.object({ average: z.string().nullable(), sample: z.number().int(), noScore: z.number().int() }),
  }),
  revenue: z
    .object({
      source: z.string(),
      confirmed: z.array(z.object({ amount, currency: currencyCode })),
      pendingVerification: z.object({ count: z.number().int(), amounts: z.array(z.object({ amount, currency: currencyCode })) }),
    })
    .optional(),
  models: z.array(ofmProfileRow),
  attention: z.array(ofmAttentionItem),
});
export type OfmOverview = z.infer<typeof ofmOverview>;

export const ofmMyShifts = z.object({
  active: ofmShiftSummary.nullable(),
  upcoming: z.array(ofmShiftSummary),
  reportsPending: z.array(ofmShiftSummary),
  handoversToAcknowledge: z.array(ofmHandoverSummary),
  swapRequests: z.array(ofmSwapRequest),
});
export type OfmMyShifts = z.infer<typeof ofmMyShifts>;

const shiftParams = wsId({ shiftId: uuid });
const reportCounts = z.object({
  conversationsHandled: z.number().int().min(0).max(1_000_000).nullable(),
  followUpsCompleted: z.number().int().min(0).max(1_000_000).nullable(),
  contentRequests: z.number().int().min(0).max(1_000_000).nullable(),
  conversionEvents: z.number().int().min(0).max(1_000_000).nullable(),
});

const handoverItemInput = z.object({
  title,
  businessExplanation: z.string().trim().max(2000).nullable().optional(),
  priority: z.enum(TASK_PRIORITIES).default('normal'),
  dueAt: ts.nullable().optional(),
  taskId: uuid.nullable().optional(),
  operationId: uuid.nullable().optional(),
  carriedFromItemId: uuid.nullable().optional(),
});

const moneyInput = {
  gross: amount.nullable().optional(),
  refund: amount.nullable().optional(),
  fee: amount.nullable().optional(),
  net: amount.nullable().optional(),
};
const allocationInput = z.array(z.object({ membershipId: uuid, sharePercent: percent })).max(10);

export const ofmEndpoints = {
  // ——— Overview / profiles ———
  overview: endpoint({
    id: 'ofm.overview',
    method: 'GET',
    path: '/workspaces/{workspaceId}/ofm/overview',
    summary: 'OFM overview: KPIs from real records with coverage, models and the attention list (scope applied before aggregation).',
    tags: tag,
    auth: 'workspace',
    permission: 'ofm.overview.read',
    params: wsId({}),
    query: z.object({ projectId: uuid.optional(), from: ts.optional(), to: ts.optional() }),
    response: ofmOverview,
  }),
  myShifts: endpoint({
    id: 'ofm.myShifts',
    method: 'GET',
    path: '/workspaces/{workspaceId}/ofm/my-shifts',
    summary: 'My Shifts: the active shift, upcoming shifts, reports to finish, handovers to acknowledge and swap requests.',
    tags: tag,
    auth: 'workspace',
    params: wsId({}),
    response: ofmMyShifts,
  }),
  profiles: endpoint({
    id: 'ofm.profiles.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/ofm/profiles',
    summary: 'Model projects with OFM enabled (one project per model — no duplicate model records).',
    tags: tag,
    auth: 'workspace',
    permission: 'ofm.overview.read',
    params: wsId({}),
    query: z.object({ q: z.string().trim().max(120).optional(), projectId: uuid.optional() }),
    response: z.array(ofmProfileRow),
  }),
  updateProfile: endpoint({
    id: 'ofm.profiles.update',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/ofm/profiles/{projectId}',
    summary: 'Update the OFM profile of a model (supervisor, handover default, contact stage labels).',
    tags: tag,
    auth: 'workspace',
    permission: 'ofm.assignments.manage',
    ifMatch: true,
    params: wsId({ projectId: uuid }),
    body: z.object({
      supervisorMembershipId: uuid.nullable().optional(),
      handoverRequired: z.boolean().optional(),
      contactStageLabels: z.partialRecord(z.enum(CONTACT_STAGES), z.string().trim().min(2).max(40)).optional(),
    }),
    response: ofmProfileRow,
  }),

  // ——— Assignments ———
  listAssignments: endpoint({
    id: 'ofm.assignments.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/ofm/assignments',
    summary: 'OFM assignments in scope (members without assignment management see their own).',
    tags: tag,
    auth: 'workspace',
    params: wsId({}),
    query: pageQuery.extend({
      projectId: uuid.optional(),
      accountId: uuid.optional(),
      membershipId: uuid.optional(),
      status: csv(z.enum(ASSIGNMENT_STATUS)).optional(),
      sort: z.enum(['validFrom', 'member', 'account']).default('validFrom'),
      direction: z.enum(['asc', 'desc']).default('desc'),
    }),
    response: page(ofmAssignmentRow),
  }),
  getAssignment: endpoint({
    id: 'ofm.assignments.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/ofm/assignments/{assignmentId}',
    summary: 'Assignment with upcoming shifts and the account’s assignment history.',
    tags: tag,
    auth: 'workspace',
    params: wsId({ assignmentId: uuid }),
    response: ofmAssignmentDetail,
  }),
  assignmentImpact: endpoint({
    id: 'ofm.assignments.impact',
    method: 'GET',
    path: '/workspaces/{workspaceId}/ofm/assignments/impact',
    summary: 'Access impact preview: account visibility changes and shifts outside the interval. Assignments never grant finance access.',
    tags: tag,
    auth: 'workspace',
    permission: 'ofm.assignments.manage',
    params: wsId({}),
    query: z.object({ membershipId: uuid, accountId: uuid, validFrom: ts.optional(), validTo: ts.optional(), assignmentId: uuid.optional(), action: z.enum(['create', 'update', 'end', 'transfer']).default('create') }),
    response: ofmAssignmentImpact,
  }),
  createAssignment: endpoint({
    id: 'ofm.assignments.create',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/assignments',
    summary: 'Assign a member to a model account for a validity interval and coverage lane.',
    tags: tag,
    auth: 'workspace',
    permission: 'ofm.assignments.manage',
    idempotent: true,
    params: wsId({}),
    body: z.object({
      accountId: uuid,
      membershipId: uuid,
      responsibility: z.enum(RESPONSIBILITIES).default('ofm_operations'),
      ...laneFields,
      validFrom: ts,
      validTo: ts.nullable().optional(),
      supervisorMembershipId: uuid.nullable().optional(),
      handoverRequired: z.boolean().optional(),
    }),
    response: ofmAssignmentDetail,
    successStatus: 201,
  }),
  updateAssignment: endpoint({
    id: 'ofm.assignments.update',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/ofm/assignments/{assignmentId}',
    summary: 'Change interval end, lane, supervisor or handover requirement. Shortening is blocked while scheduled shifts fall outside.',
    tags: tag,
    auth: 'workspace',
    permission: 'ofm.assignments.manage',
    ifMatch: true,
    params: wsId({ assignmentId: uuid }),
    body: z.object({
      responsibility: z.enum(RESPONSIBILITIES).optional(),
      coverageLane: z.enum(COVERAGE_LANES).optional(),
      coverageLaneLabel: z.string().trim().min(2).max(40).nullable().optional(),
      validFrom: ts.optional(),
      validTo: ts.nullable().optional(),
      supervisorMembershipId: uuid.nullable().optional(),
      handoverRequired: z.boolean().optional(),
    }),
    response: ofmAssignmentDetail,
  }),
  endAssignment: endpoint({
    id: 'ofm.assignments.end',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/assignments/{assignmentId}/end',
    summary: 'End an assignment (history kept). Scheduled shifts after the end must be cancelled or reassigned first.',
    tags: tag,
    auth: 'workspace',
    permission: 'ofm.assignments.manage',
    idempotent: true,
    ifMatch: true,
    params: wsId({ assignmentId: uuid }),
    body: z.object({ endAt: ts.optional(), reason }),
    response: ofmAssignmentDetail,
  }),
  transferAssignment: endpoint({
    id: 'ofm.assignments.transfer',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/assignments/{assignmentId}/transfer',
    summary: 'Transfer the assignment to another member from an effective time; optionally move future scheduled shifts (re-validated).',
    tags: tag,
    auth: 'workspace',
    permission: 'ofm.assignments.manage',
    idempotent: true,
    ifMatch: true,
    params: wsId({ assignmentId: uuid }),
    body: z.object({ toMembershipId: uuid, effectiveAt: ts.optional(), reason, moveFutureShifts: z.boolean().default(true) }),
    response: ofmAssignmentDetail,
  }),

  // ——— Shifts ———
  listShifts: endpoint({
    id: 'ofm.shifts.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/ofm/shifts',
    summary: 'Shift schedule in scope (own shifts only with shifts.read.own). Filter by period, member, account, state.',
    tags: tag,
    auth: 'workspace',
    params: wsId({}),
    query: pageQuery.extend({
      from: ts.optional(),
      to: ts.optional(),
      membershipId: uuid.optional(),
      accountId: uuid.optional(),
      projectId: uuid.optional(),
      state: csv(z.enum(SHIFT_STATES)).optional(),
      reportState: csv(z.enum(SHIFT_REPORT_STATES)).optional(),
      needsReview: boolQuery.optional(),
      mine: boolQuery.optional(),
      direction: z.enum(['asc', 'desc']).default('asc'),
    }),
    response: page(ofmShiftSummary),
  }),
  getShift: endpoint({
    id: 'ofm.shifts.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/ofm/shifts/{shiftId}',
    summary: 'Shift Workspace: schedule, server timer, breaks, handovers, operations, sale candidates, report and allowed actions.',
    tags: tag,
    auth: 'workspace',
    params: shiftParams,
    response: ofmShiftDetail,
  }),
  validateShift: endpoint({
    id: 'ofm.shifts.validate',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/shifts/validate',
    summary: 'Dry-run schedule checks: member overlap, coverage lanes, assignment intervals, leave and DST (no changes).',
    tags: tag,
    auth: 'workspace',
    permission: 'shifts.schedule',
    params: wsId({}),
    body: z.object({ ...scheduleFields, shiftId: uuid.optional() }),
    response: ofmShiftValidation,
  }),
  createShift: endpoint({
    id: 'ofm.shifts.create',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/shifts',
    summary: 'Schedule a shift (1 primary + up to 9 additional accounts; one timer for all).',
    tags: tag,
    auth: 'workspace',
    permission: 'shifts.schedule',
    idempotent: true,
    params: wsId({}),
    body: z.object(scheduleFields),
    response: ofmShiftDetail,
    successStatus: 201,
  }),
  updateShift: endpoint({
    id: 'ofm.shifts.update',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/ofm/shifts/{shiftId}',
    summary: 'Edit a scheduled shift. Actual times change only through commands.',
    tags: tag,
    auth: 'workspace',
    permission: 'shifts.schedule',
    ifMatch: true,
    params: shiftParams,
    body: z.object({
      membershipId: uuid.optional(),
      primaryAccountId: uuid.optional(),
      additionalAccountIds: z.array(uuid).max(SHIFT_LIMITS.maxAccounts - 1).optional(),
      scheduledStart: ts.optional(),
      scheduledEnd: ts.optional(),
      timezone: timezone.optional(),
      supervisorMembershipId: uuid.nullable().optional(),
      parallelCoverage: z.boolean().optional(),
    }),
    response: ofmShiftDetail,
  }),
  cancelShift: endpoint({
    id: 'ofm.shifts.cancel',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/shifts/{shiftId}/cancel',
    summary: 'Cancel a scheduled shift with a reason (active shifts are ended, not cancelled). Reminders stop.',
    tags: tag,
    auth: 'workspace',
    permission: 'shifts.schedule',
    idempotent: true,
    ifMatch: true,
    params: shiftParams,
    body: z.object({ reason }),
    response: ofmShiftDetail,
  }),
  repeatPreview: endpoint({
    id: 'ofm.shifts.repeatPreview',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/shifts/repeat-preview',
    summary: 'Preview a repeated schedule (≤ 8 weeks) with conflicts and DST notes; returns a token for Apply.',
    tags: tag,
    auth: 'workspace',
    permission: 'shifts.schedule',
    params: wsId({}),
    body: z.object({
      membershipId: uuid,
      primaryAccountId: uuid,
      additionalAccountIds: z.array(uuid).max(SHIFT_LIMITS.maxAccounts - 1).default([]),
      supervisorMembershipId: uuid.nullable().optional(),
      parallelCoverage: z.boolean().default(false),
      pattern: ofmRepeatPattern,
    }),
    response: z.object({
      previewToken: z.string(),
      expiresAt: ts,
      occurrences: z.array(
        z.object({
          date: isoDate,
          start: ts,
          end: ts,
          durationMinutes: z.number().int(),
          dstShifted: z.boolean(),
          offsetChanges: z.boolean(),
          conflicts: z.array(ofmScheduleIssue),
          assignmentIssues: z.array(ofmScheduleIssue),
          warnings: z.array(ofmScheduleIssue),
          ok: z.boolean(),
        }),
      ),
    }),
  }),
  repeatApply: endpoint({
    id: 'ofm.shifts.repeatApply',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/shifts/repeat-apply',
    summary: 'Create the previewed occurrences exactly once (unique occurrence keys); conflicting ones are skipped or block.',
    tags: tag,
    auth: 'workspace',
    permission: 'shifts.schedule',
    idempotent: true,
    params: wsId({}),
    body: z.object({ previewToken: z.string().max(4000), skipConflicting: z.boolean().default(true) }),
    response: z.object({ repeatGroupId: uuid, created: z.array(uuid), skipped: z.array(z.object({ date: isoDate, reason: z.string() })) }),
    successStatus: 201,
  }),
  allowEarlyStart: endpoint({
    id: 'ofm.shifts.allowEarlyStart',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/shifts/{shiftId}/allow-early-start',
    summary: 'Supervisor override allowing a start more than 15 minutes before the scheduled start.',
    tags: tag,
    auth: 'workspace',
    permission: 'shifts.schedule',
    idempotent: true,
    ifMatch: true,
    params: shiftParams,
    body: z.object({ reason }),
    response: ofmShiftDetail,
  }),
  startShift: endpoint({
    id: 'ofm.shifts.start',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/shifts/{shiftId}/start',
    summary: 'Start the shift (server actual start; one active shift per member). Requires the pending handover acknowledged or a reason.',
    tags: tag,
    auth: 'workspace',
    permission: 'shifts.start.own',
    idempotent: true,
    ifMatch: true,
    params: shiftParams,
    body: z.object({ handoverAcknowledgementId: uuid.optional(), noHandoverReason: z.string().trim().min(3).max(500).optional() }),
    response: ofmShiftDetail,
  }),
  pauseShift: endpoint({
    id: 'ofm.shifts.pause',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/shifts/{shiftId}/pause',
    summary: 'Open a break.',
    tags: tag,
    auth: 'workspace',
    permission: 'shifts.start.own',
    idempotent: true,
    ifMatch: true,
    params: shiftParams,
    body: z.object({ reason: z.string().trim().max(500).optional() }),
    response: ofmShiftDetail,
  }),
  resumeShift: endpoint({
    id: 'ofm.shifts.resume',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/shifts/{shiftId}/resume',
    summary: 'Close the open break.',
    tags: tag,
    auth: 'workspace',
    permission: 'shifts.start.own',
    idempotent: true,
    ifMatch: true,
    params: shiftParams,
    body: z.object({ breakId: uuid }),
    response: ofmShiftDetail,
  }),
  endShift: endpoint({
    id: 'ofm.shifts.end',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/shifts/{shiftId}/end',
    summary: 'End the shift: closes an open break at the same instant, records actual end and opens the report draft.',
    tags: tag,
    auth: 'workspace',
    permission: 'shifts.end.own',
    idempotent: true,
    ifMatch: true,
    params: shiftParams,
    body: z.object({ endNote: z.string().trim().max(2000).optional(), aborted: z.boolean().default(false), abortReason: z.string().trim().min(3).max(2000).optional() }),
    response: ofmShiftDetail,
  }),
  correctTime: endpoint({
    id: 'ofm.shifts.correctTime',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/shifts/{shiftId}/correct-time',
    summary: 'Supervisor correction of actual start/end/breaks with reason (audited; flags compensation sources as changed). Ending an active shift here is a forced end.',
    tags: tag,
    auth: 'workspace',
    permission: 'shifts.correct',
    idempotent: true,
    ifMatch: true,
    params: shiftParams,
    body: z.object({
      actualStart: ts.optional(),
      actualEnd: ts.optional(),
      breaks: z.array(z.object({ id: uuid.optional(), startedAt: ts, endedAt: ts })).max(50).optional(),
      reason,
    }),
    response: ofmShiftDetail,
  }),
  markMissed: endpoint({
    id: 'ofm.shifts.markMissed',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/shifts/{shiftId}/mark-missed',
    summary: 'Confirm a scheduled shift as Missed after its scheduled end.',
    tags: tag,
    auth: 'workspace',
    permission: 'shifts.schedule',
    idempotent: true,
    ifMatch: true,
    params: shiftParams,
    body: z.object({ reason }),
    response: ofmShiftDetail,
  }),
  setTimeAllocation: endpoint({
    id: 'ofm.shifts.setTimeAllocation',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/shifts/{shiftId}/time-allocation',
    summary: 'Confirm per-account time allocation shares (sum exactly 100 %) or clear them. The shift time itself is never multiplied.',
    tags: tag,
    auth: 'workspace',
    permission: 'shifts.correct',
    idempotent: true,
    ifMatch: true,
    params: shiftParams,
    body: z.object({ shares: z.array(z.object({ accountId: uuid, sharePercent: percent })).max(SHIFT_LIMITS.maxAccounts).nullable() }),
    response: ofmShiftDetail,
  }),
  requestSwap: endpoint({
    id: 'ofm.shifts.requestSwap',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/shifts/{shiftId}/swap-requests',
    summary: 'Request a swap: the proposed member accepts, then a supervisor approves (collision and assignment re-checked).',
    tags: tag,
    auth: 'workspace',
    idempotent: true,
    params: shiftParams,
    body: z.object({ proposedMembershipId: uuid, reason }),
    response: ofmSwapRequest,
    successStatus: 201,
  }),
  listSwaps: endpoint({
    id: 'ofm.swaps.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/ofm/shift-swaps',
    summary: 'Swap requests visible to the member (own, proposed to them, or to approve in scope).',
    tags: tag,
    auth: 'workspace',
    params: wsId({}),
    query: z.object({ state: csv(z.enum(SWAP_REQUEST_STATES)).optional(), shiftId: uuid.optional() }),
    response: z.array(ofmSwapRequest),
  }),
  acceptSwap: endpoint({
    id: 'ofm.swaps.accept',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/shift-swaps/{swapId}/accept',
    summary: 'Proposed member agrees to take the shift.',
    tags: tag,
    auth: 'workspace',
    idempotent: true,
    ifMatch: true,
    params: wsId({ swapId: uuid }),
    response: ofmSwapRequest,
  }),
  declineSwap: endpoint({
    id: 'ofm.swaps.decline',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/shift-swaps/{swapId}/decline',
    summary: 'Proposed member or supervisor declines the swap.',
    tags: tag,
    auth: 'workspace',
    idempotent: true,
    ifMatch: true,
    params: wsId({ swapId: uuid }),
    body: z.object({ reason }),
    response: ofmSwapRequest,
  }),
  approveSwap: endpoint({
    id: 'ofm.swaps.approve',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/shift-swaps/{swapId}/approve',
    summary: 'Supervisor approval: atomic reassignment after overlap and assignment checks; history keeps the previous member.',
    tags: tag,
    auth: 'workspace',
    permission: 'shifts.schedule',
    idempotent: true,
    ifMatch: true,
    params: wsId({ swapId: uuid }),
    body: z.object({ note: z.string().trim().max(2000).optional() }),
    response: ofmSwapRequest,
  }),
  cancelSwap: endpoint({
    id: 'ofm.swaps.cancel',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/shift-swaps/{swapId}/cancel',
    summary: 'Requester withdraws the swap request.',
    tags: tag,
    auth: 'workspace',
    idempotent: true,
    ifMatch: true,
    params: wsId({ swapId: uuid }),
    response: ofmSwapRequest,
  }),

  // ——— Reports ———
  saveReportDraft: endpoint({
    id: 'ofm.reports.saveDraft',
    method: 'PUT',
    path: '/workspaces/{workspaceId}/ofm/shift-reports/{reportId}/draft',
    summary: 'Save the report draft (after Changes Requested a new version is created; submitted versions are frozen).',
    tags: tag,
    auth: 'workspace',
    ifMatch: true,
    params: wsId({ reportId: uuid }),
    body: z.object({
      summary: z.string().max(LIMITS.noteMax),
      completedWork: optionalNote,
      issues: optionalNote,
      nextActions: optionalNote,
      accountSections: z.array(z.object({ accountId: uuid, notes: z.string().max(LIMITS.noteMax) })).max(SHIFT_LIMITS.maxAccounts).default([]),
      counts: reportCounts,
      sourceRefs: z.array(z.object({ label: z.string().trim().min(2).max(200), assetId: uuid.optional(), note: z.string().max(2000).optional() })).max(30).default([]),
      noOpenItems: z.boolean().default(false),
      handoverId: uuid.nullable().optional(),
    }),
    response: ofmReportDetail,
  }),
  submitReport: endpoint({
    id: 'ofm.reports.submit',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/shifts/{shiftId}/submit-report',
    summary: 'Submit the report: Summary plus handover items or an explicit No Open Items are required.',
    tags: tag,
    auth: 'workspace',
    idempotent: true,
    ifMatch: true,
    params: shiftParams,
    body: z.object({ reportVersionId: uuid, handoverId: uuid.nullable().optional(), noOpenItems: z.boolean().optional() }),
    response: ofmReportDetail,
  }),
  approveReport: endpoint({
    id: 'ofm.reports.approve',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/shift-reports/{reportId}/approve',
    summary: 'Approve the submitted version (frozen). Never posts or changes finance.',
    tags: tag,
    auth: 'workspace',
    permission: 'shifts.approve',
    idempotent: true,
    ifMatch: true,
    params: wsId({ reportId: uuid }),
    body: z.object({ versionId: uuid }),
    response: ofmReportDetail,
  }),
  requestReportChanges: endpoint({
    id: 'ofm.reports.requestChanges',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/shift-reports/{reportId}/request-changes',
    summary: 'Return the report with a summary of the changes needed; a revised draft is required.',
    tags: tag,
    auth: 'workspace',
    permission: 'shifts.approve',
    idempotent: true,
    ifMatch: true,
    params: wsId({ reportId: uuid }),
    body: z.object({ versionId: uuid, summary: reason }),
    response: ofmReportDetail,
  }),

  // ——— Handovers ———
  listHandovers: endpoint({
    id: 'ofm.handovers.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/ofm/handovers',
    summary: 'Handover Desk: incoming, outgoing or all handovers in scope.',
    tags: tag,
    auth: 'workspace',
    params: wsId({}),
    query: pageQuery.extend({
      box: z.enum(['incoming', 'outgoing', 'all', 'unacknowledged']).default('all'),
      state: csv(z.enum(HANDOVER_STATES)).optional(),
      accountId: uuid.optional(),
      projectId: uuid.optional(),
    }),
    response: page(ofmHandoverSummary),
  }),
  getHandover: endpoint({
    id: 'ofm.handovers.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/ofm/handovers/{handoverId}',
    summary: 'Handover with items (tasks and operations linked by id).',
    tags: tag,
    auth: 'workspace',
    params: wsId({ handoverId: uuid }),
    response: ofmHandoverDetail,
  }),
  handoverCandidates: endpoint({
    id: 'ofm.handovers.candidates',
    method: 'GET',
    path: '/workspaces/{workspaceId}/ofm/shifts/{shiftId}/handover-candidates',
    summary: 'Open matters that can be handed over from this shift: accepted unresolved items and open operations (referenced, not copied).',
    tags: tag,
    auth: 'workspace',
    params: shiftParams,
    response: z.object({
      carriedItems: z.array(ofmHandoverItem.extend({ handoverId: uuid })),
      operations: z.array(ofmOperationSummary),
    }),
  }),
  createHandover: endpoint({
    id: 'ofm.handovers.create',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/handovers',
    summary: 'Create a handover draft from a shift (one per shift and account).',
    tags: tag,
    auth: 'workspace',
    permission: 'handovers.write',
    idempotent: true,
    params: wsId({}),
    body: z.object({
      fromShiftId: uuid,
      accountId: uuid.optional(),
      summary: z.string().trim().min(3).max(LIMITS.noteMax),
      recipientMembershipId: uuid.nullable().optional(),
      toShiftId: uuid.nullable().optional(),
      noOpenItems: z.boolean().default(false),
      items: z.array(handoverItemInput).max(50).default([]),
    }),
    response: ofmHandoverDetail,
    successStatus: 201,
  }),
  updateHandover: endpoint({
    id: 'ofm.handovers.update',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/ofm/handovers/{handoverId}',
    summary: 'Edit a handover draft.',
    tags: tag,
    auth: 'workspace',
    permission: 'handovers.write',
    ifMatch: true,
    params: wsId({ handoverId: uuid }),
    body: z.object({
      summary: z.string().trim().min(3).max(LIMITS.noteMax).optional(),
      recipientMembershipId: uuid.nullable().optional(),
      toShiftId: uuid.nullable().optional(),
      noOpenItems: z.boolean().optional(),
    }),
    response: ofmHandoverDetail,
  }),
  addHandoverItem: endpoint({
    id: 'ofm.handovers.addItem',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/handovers/{handoverId}/items',
    summary: 'Add an item to a handover draft (one open item per task/operation).',
    tags: tag,
    auth: 'workspace',
    permission: 'handovers.write',
    idempotent: true,
    params: wsId({ handoverId: uuid }),
    body: handoverItemInput,
    response: ofmHandoverDetail,
    successStatus: 201,
  }),
  removeHandoverItem: endpoint({
    id: 'ofm.handovers.removeItem',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/handovers/{handoverId}/items/{itemId}/remove',
    summary: 'Remove an item from a handover draft.',
    tags: tag,
    auth: 'workspace',
    permission: 'handovers.write',
    idempotent: true,
    params: wsId({ handoverId: uuid, itemId: uuid }),
    response: ofmHandoverDetail,
  }),
  submitHandover: endpoint({
    id: 'ofm.handovers.submit',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/handovers/{handoverId}/submit',
    summary: 'Submit: recipient is the chosen member, else the next shift’s member, else the supervisor.',
    tags: tag,
    auth: 'workspace',
    permission: 'handovers.write',
    idempotent: true,
    ifMatch: true,
    params: wsId({ handoverId: uuid }),
    body: z.object({ recipientMembershipId: uuid.nullable().optional(), toShiftId: uuid.nullable().optional() }),
    response: ofmHandoverDetail,
  }),
  acknowledgeHandover: endpoint({
    id: 'ofm.handovers.acknowledge',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/handovers/{handoverId}/acknowledge',
    summary: 'Acknowledge receipt and accept selected items. Acknowledgement does not resolve, complete or copy anything.',
    tags: tag,
    auth: 'workspace',
    permission: 'handovers.acknowledge',
    idempotent: true,
    ifMatch: true,
    params: wsId({ handoverId: uuid }),
    body: z.object({ acceptedItemIds: z.array(uuid).max(50).default([]) }),
    response: ofmHandoverDetail,
  }),
  assignHandoverRecipient: endpoint({
    id: 'ofm.handovers.assignRecipient',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/handovers/{handoverId}/assign-recipient',
    summary: 'Supervisor re-routes a submitted, unacknowledged handover to another recipient.',
    tags: tag,
    auth: 'workspace',
    permission: 'handovers.write',
    idempotent: true,
    ifMatch: true,
    params: wsId({ handoverId: uuid }),
    body: z.object({ recipientMembershipId: uuid, toShiftId: uuid.nullable().optional(), reason: reason.optional() }),
    response: ofmHandoverDetail,
  }),
  resolveHandoverItem: endpoint({
    id: 'ofm.handoverItems.resolve',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/handover-items/{itemId}/resolve',
    summary: 'Mark one handover item resolved (does not change the linked task or operation).',
    tags: tag,
    auth: 'workspace',
    idempotent: true,
    ifMatch: true,
    params: wsId({ itemId: uuid }),
    body: z.object({ note: z.string().trim().max(2000).optional() }),
    response: ofmHandoverDetail,
  }),
  convertHandoverItem: endpoint({
    id: 'ofm.handoverItems.convertToTask',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/handover-items/{itemId}/convert-to-task',
    summary: 'Create one task for a handover item and link it by id (never re-created on later handovers).',
    tags: tag,
    auth: 'workspace',
    permission: 'tasks.create',
    idempotent: true,
    ifMatch: true,
    params: wsId({ itemId: uuid }),
    body: z.object({ assigneeMembershipId: uuid.nullable().optional(), dueAt: ts.nullable().optional(), title: title.optional() }),
    response: ofmHandoverDetail,
  }),

  // ——— Contacts ———
  listContacts: endpoint({
    id: 'ofm.contacts.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/ofm/contacts',
    summary: 'OFM contacts (sensitive: contacts.read). Search matches alias or external identifier within scope only.',
    tags: tag,
    auth: 'workspace',
    permission: 'contacts.read',
    params: wsId({}),
    query: pageQuery.extend({
      q: z.string().trim().max(120).optional(),
      accountId: uuid.optional(),
      projectId: uuid.optional(),
      stage: csv(z.enum(CONTACT_STAGES)).optional(),
      managerMembershipId: uuid.optional(),
      followUp: z.enum(['due', 'overdue', 'none']).optional(),
      includeArchived: boolQuery.optional(),
      sort: z.enum(['lastActivityAt', 'nextFollowUpAt', 'alias', 'updatedAt']).default('updatedAt'),
      direction: z.enum(['asc', 'desc']).default('desc'),
    }),
    response: page(ofmContactSummary),
  }),
  getContact: endpoint({
    id: 'ofm.contacts.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/ofm/contacts/{contactId}',
    summary: 'Contact Workspace: manual log of business notes, operations, sale links and relations. Merged ids redirect.',
    tags: tag,
    auth: 'workspace',
    permission: 'contacts.read',
    params: wsId({ contactId: uuid }),
    response: ofmContactDetail,
  }),
  createContact: endpoint({
    id: 'ofm.contacts.create',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/contacts',
    summary: 'Add a contact for one platform account (unique account + external identifier). No real names or payment data.',
    tags: tag,
    auth: 'workspace',
    permission: 'contacts.write',
    idempotent: true,
    params: wsId({}),
    body: z.object({
      accountId: uuid,
      externalIdentifier: z.string().trim().min(1).max(200),
      alias: z.string().trim().min(2).max(120),
      managerMembershipId: uuid.nullable().optional(),
      stage: z.enum(CONTACT_STAGES).exclude(['archived']).default('new'),
      businessNotes: z.string().max(LIMITS.noteMax).nullable().optional(),
      nextFollowUpAt: ts.nullable().optional(),
      restricted: z.boolean().optional(),
    }),
    response: ofmContactDetail,
    successStatus: 201,
  }),
  updateContact: endpoint({
    id: 'ofm.contacts.update',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/ofm/contacts/{contactId}',
    summary: 'Edit alias, manager (Assign), business notes, next follow-up or restriction (restriction needs contacts.merge).',
    tags: tag,
    auth: 'workspace',
    permission: 'contacts.write',
    ifMatch: true,
    params: wsId({ contactId: uuid }),
    body: z.object({
      alias: z.string().trim().min(2).max(120).optional(),
      managerMembershipId: uuid.nullable().optional(),
      businessNotes: z.string().max(LIMITS.noteMax).nullable().optional(),
      nextFollowUpAt: ts.nullable().optional(),
      restricted: z.boolean().optional(),
    }),
    response: ofmContactDetail,
  }),
  changeContactStage: endpoint({
    id: 'ofm.contacts.changeStage',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/contacts/{contactId}/stage',
    summary: 'Change the descriptive stage (no computed or psychological scoring).',
    tags: tag,
    auth: 'workspace',
    permission: 'contacts.write',
    idempotent: true,
    ifMatch: true,
    params: wsId({ contactId: uuid }),
    body: z.object({ stage: z.enum(CONTACT_STAGES).exclude(['archived']), reason: z.string().trim().max(2000).optional() }),
    response: ofmContactDetail,
  }),
  mergePreview: endpoint({
    id: 'ofm.contacts.mergePreview',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/contacts/merge-preview',
    summary: 'Safe merge diff for two contacts of the same account (cross-account merge is refused).',
    tags: tag,
    auth: 'workspace',
    permission: 'contacts.merge',
    params: wsId({}),
    body: z.object({ sourceId: uuid, targetId: uuid }),
    response: ofmMergePreview,
  }),
  merge: endpoint({
    id: 'ofm.contacts.merge',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/contacts/merge',
    summary: 'Merge source into target: references move, authors kept, the source id redirects; sales are never duplicated or summed.',
    tags: tag,
    auth: 'workspace',
    permission: 'contacts.merge',
    idempotent: true,
    params: wsId({}),
    body: z.object({
      previewToken: z.string().max(2000),
      fieldResolutions: z
        .object({
          alias: z.enum(['source', 'target']).default('target'),
          managerMembershipId: z.enum(['source', 'target']).default('target'),
          stage: z.enum(['source', 'target']).default('target'),
          nextFollowUpAt: z.enum(['source', 'target']).default('target'),
          businessNotes: z.enum(['source', 'target', 'both']).default('both'),
        })
        .default({ alias: 'target', managerMembershipId: 'target', stage: 'target', nextFollowUpAt: 'target', businessNotes: 'both' }),
    }),
    response: ofmContactDetail,
  }),
  relateContacts: endpoint({
    id: 'ofm.contacts.relate',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/contacts/{contactId}/relations',
    summary: 'Explicit pseudonymous relation to a contact of another account (separate permission; no identity merge).',
    tags: tag,
    auth: 'workspace',
    permission: 'contacts.relate',
    idempotent: true,
    params: wsId({ contactId: uuid }),
    body: z.object({ relatedContactId: uuid, reason }),
    response: ofmContactDetail,
    successStatus: 201,
  }),
  archiveContact: endpoint({
    id: 'ofm.contacts.archive',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/contacts/{contactId}/archive',
    summary: 'Archive the contact; business notes are deleted after the retention period (default 180 days).',
    tags: tag,
    auth: 'workspace',
    permission: 'contacts.write',
    idempotent: true,
    ifMatch: true,
    params: wsId({ contactId: uuid }),
    body: z.object({ reason }),
    response: ofmContactDetail,
  }),
  restoreContact: endpoint({
    id: 'ofm.contacts.restore',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/contacts/{contactId}/restore',
    summary: 'Restore an archived (not erased or merged) contact.',
    tags: tag,
    auth: 'workspace',
    permission: 'contacts.write',
    idempotent: true,
    ifMatch: true,
    params: wsId({ contactId: uuid }),
    response: ofmContactDetail,
  }),
  requestErasure: endpoint({
    id: 'ofm.contacts.requestErasure',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/contacts/{contactId}/erasure-requests',
    summary: 'Queue erasure: personal notes are deleted, financial references stay pseudonymised (retention policy).',
    tags: tag,
    auth: 'workspace',
    permission: 'contacts.erase',
    idempotent: true,
    params: wsId({ contactId: uuid }),
    body: z.object({ reason }),
    response: z.object({ id: uuid, state: z.string(), plan: z.record(z.string(), z.unknown()) }),
    successStatus: 202,
  }),
  listInteractions: endpoint({
    id: 'ofm.interactions.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/ofm/interactions',
    summary: 'Manual interaction log of a contact (entered by people; not a platform inbox).',
    tags: tag,
    auth: 'workspace',
    permission: 'contacts.read',
    params: wsId({}),
    query: pageQuery.extend({ contactId: uuid }),
    response: page(ofmInteraction),
  }),
  createInteraction: endpoint({
    id: 'ofm.interactions.create',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/interactions',
    summary: 'Log an interaction (Message Summary, Request, Issue, Other) with the time it happened.',
    tags: tag,
    auth: 'workspace',
    permission: 'contacts.write',
    idempotent: true,
    params: wsId({}),
    body: z.object({
      contactId: uuid,
      type: z.enum(INTERACTION_TYPES),
      occurredAt: ts,
      businessNote: z.string().trim().min(1).max(LIMITS.noteMax),
      shiftId: uuid.nullable().optional(),
    }),
    response: ofmInteraction,
    successStatus: 201,
  }),
  updateInteraction: endpoint({
    id: 'ofm.interactions.update',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/ofm/interactions/{interactionId}',
    summary: 'Author edits their own interaction (audited without the text).',
    tags: tag,
    auth: 'workspace',
    permission: 'contacts.write',
    ifMatch: true,
    params: wsId({ interactionId: uuid }),
    body: z.object({ type: z.enum(INTERACTION_TYPES).optional(), occurredAt: ts.optional(), businessNote: z.string().trim().min(1).max(LIMITS.noteMax).optional() }),
    response: ofmInteraction,
  }),

  // ——— Operations ———
  listOperations: endpoint({
    id: 'ofm.operations.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/ofm/operations',
    summary: 'Operations Queue in scope.',
    tags: tag,
    auth: 'workspace',
    permission: 'operations.read',
    params: wsId({}),
    query: pageQuery.extend({
      status: csv(z.enum(OPERATION_STATUSES)).optional(),
      type: csv(z.enum(OPERATION_TYPES)).optional(),
      accountId: uuid.optional(),
      projectId: uuid.optional(),
      ownerMembershipId: uuid.optional(),
      contactId: uuid.optional(),
      shiftId: uuid.optional(),
      due: z.enum(['overdue', 'today', 'week']).optional(),
      q: z.string().trim().max(120).optional(),
      includeArchived: boolQuery.optional(),
      sort: z.enum(['dueAt', 'updatedAt', 'priority', 'createdAt']).default('dueAt'),
      direction: z.enum(['asc', 'desc']).default('asc'),
    }),
    response: page(ofmOperationSummary),
  }),
  getOperation: endpoint({
    id: 'ofm.operations.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/ofm/operations/{operationId}',
    summary: 'Operation detail with allowed transitions.',
    tags: tag,
    auth: 'workspace',
    permission: 'operations.read',
    params: wsId({ operationId: uuid }),
    response: ofmOperationDetail,
  }),
  createOperation: endpoint({
    id: 'ofm.operations.create',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/operations',
    summary: 'Create an operation (request, follow-up, payment/account check, issue). Business state only; no payment effect.',
    tags: tag,
    auth: 'workspace',
    permission: 'operations.write',
    idempotent: true,
    params: wsId({}),
    body: z.object({
      type: z.enum(OPERATION_TYPES),
      accountId: uuid,
      contactId: uuid.nullable().optional(),
      ownerMembershipId: uuid,
      title,
      details: z.string().max(LIMITS.noteMax).nullable().optional(),
      dueAt: ts.nullable().optional(),
      priority: z.enum(TASK_PRIORITIES).default('normal'),
      shiftId: uuid.nullable().optional(),
      promisedDeliverable: z.string().trim().max(500).nullable().optional(),
      evidenceAssetIds: z.array(uuid).max(20).default([]),
    }),
    response: ofmOperationDetail,
    successStatus: 201,
  }),
  updateOperation: endpoint({
    id: 'ofm.operations.update',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/ofm/operations/{operationId}',
    summary: 'Edit an open operation (Assign changes the owner).',
    tags: tag,
    auth: 'workspace',
    permission: 'operations.write',
    ifMatch: true,
    params: wsId({ operationId: uuid }),
    body: z.object({
      title: title.optional(),
      details: z.string().max(LIMITS.noteMax).nullable().optional(),
      dueAt: ts.nullable().optional(),
      priority: z.enum(TASK_PRIORITIES).optional(),
      ownerMembershipId: uuid.optional(),
      contactId: uuid.nullable().optional(),
      promisedDeliverable: z.string().trim().max(500).nullable().optional(),
      evidenceAssetIds: z.array(uuid).max(20).optional(),
    }),
    response: ofmOperationDetail,
  }),
  transitionOperation: endpoint({
    id: 'ofm.operations.transition',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/operations/{operationId}/transition',
    summary: 'Start, wait (Waiting For + Next Check At), complete (Outcome) or cancel (Reason). Completion never means payment.',
    tags: tag,
    auth: 'workspace',
    permission: 'operations.write',
    idempotent: true,
    ifMatch: true,
    params: wsId({ operationId: uuid }),
    body: z.object({
      targetState: z.enum(OPERATION_STATUSES),
      outcome: z.string().trim().min(3).max(2000).optional(),
      reason: reason.optional(),
      waitingFor: z.string().trim().min(2).max(500).optional(),
      nextCheckAt: ts.optional(),
    }),
    response: ofmOperationDetail,
  }),
  createContentBrief: endpoint({
    id: 'ofm.operations.createContentBrief',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/operations/{operationId}/content-brief',
    summary: 'Content Request → a task for the creator with the permitted short brief only (no contact notes or history).',
    tags: tag,
    auth: 'workspace',
    permission: 'tasks.create',
    idempotent: true,
    ifMatch: true,
    params: wsId({ operationId: uuid }),
    body: z.object({ creatorMembershipId: uuid, title, brief: z.string().trim().min(3).max(4000), dueAt: ts.nullable().optional() }),
    response: ofmOperationDetail,
  }),
  linkContent: endpoint({
    id: 'ofm.operations.linkContent',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/operations/{operationId}/link-content',
    summary: 'Link (or unlink) an existing content item delivered for the request.',
    tags: tag,
    auth: 'workspace',
    permission: 'operations.write',
    idempotent: true,
    ifMatch: true,
    params: wsId({ operationId: uuid }),
    body: z.object({ contentItemId: uuid.nullable() }),
    response: ofmOperationDetail,
  }),

  // ——— Sale candidates ———
  listSaleCandidates: endpoint({
    id: 'ofm.saleCandidates.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/ofm/sale-candidates',
    summary: 'Registered sale candidates (Pending until Finance verifies or rejects them).',
    tags: tag,
    auth: 'workspace',
    params: wsId({}),
    query: pageQuery.extend({
      state: csv(z.enum(SALE_CANDIDATE_STATES)).optional(),
      accountId: uuid.optional(),
      projectId: uuid.optional(),
      shiftId: uuid.optional(),
      contactId: uuid.optional(),
    }),
    response: page(ofmSaleCandidate),
  }),
  getSaleCandidate: endpoint({
    id: 'ofm.saleCandidates.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/ofm/sale-candidates/{candidateId}',
    summary: 'Sale candidate detail.',
    tags: tag,
    auth: 'workspace',
    params: wsId({ candidateId: uuid }),
    response: ofmSaleCandidate,
  }),
  checkSaleDuplicate: endpoint({
    id: 'ofm.saleCandidates.checkDuplicate',
    method: 'GET',
    path: '/workspaces/{workspaceId}/ofm/sale-candidates/duplicate-check',
    summary: 'Detect an existing candidate or financial entry with the same source transaction before registering.',
    tags: tag,
    auth: 'workspace',
    permission: 'sale-candidates.write',
    params: wsId({}),
    query: z.object({ sourceNamespace: z.string().trim().min(1).max(80), sourceTransactionId: z.string().trim().min(1).max(200) }),
    response: z.object({
      duplicate: z.boolean(),
      recordedInFinance: z.boolean(),
      candidate: z.object({ id: uuid, state: z.enum(SALE_CANDIDATE_STATES) }).nullable(),
      financialEntry: z.object({ id: uuid, state: z.string() }).nullable(),
    }),
  }),
  createSaleCandidate: endpoint({
    id: 'ofm.saleCandidates.create',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/sale-candidates',
    summary: 'Register a sale candidate per source. Duplicates of a source transaction are refused; attribution is never inferred from shift timing.',
    tags: tag,
    auth: 'workspace',
    permission: 'sale-candidates.write',
    idempotent: true,
    params: wsId({}),
    body: z.object({
      accountId: uuid,
      sourceNamespace: z.string().trim().min(1).max(80),
      /** External transaction id; omit with manualReference = true to generate a manual reference (evidence required). */
      sourceTransactionId: z.string().trim().min(1).max(200).optional(),
      manualReference: z.boolean().default(false),
      occurredAt: ts,
      currency: currencyCode,
      ...moneyInput,
      contactId: uuid.nullable().optional(),
      shiftId: uuid.nullable().optional(),
      operationId: uuid.nullable().optional(),
      sourceNote: z.string().trim().max(2000).nullable().optional(),
      evidenceAssetIds: z.array(uuid).max(20).default([]),
      claimedAllocations: allocationInput.default([]),
    }),
    response: ofmSaleCandidate,
    successStatus: 201,
  }),
  updateSaleCandidate: endpoint({
    id: 'ofm.saleCandidates.update',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/ofm/sale-candidates/{candidateId}',
    summary: 'Edit a Pending candidate (source ids are immutable once registered).',
    tags: tag,
    auth: 'workspace',
    permission: 'sale-candidates.write',
    ifMatch: true,
    params: wsId({ candidateId: uuid }),
    body: z.object({
      occurredAt: ts.optional(),
      ...moneyInput,
      contactId: uuid.nullable().optional(),
      shiftId: uuid.nullable().optional(),
      sourceNote: z.string().trim().max(2000).nullable().optional(),
      evidenceAssetIds: z.array(uuid).max(20).optional(),
      claimedAllocations: allocationInput.optional(),
    }),
    response: ofmSaleCandidate,
  }),

  // ——— Quality ———
  listRubrics: endpoint({
    id: 'ofm.rubrics.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/ofm/rubrics',
    summary: 'Quality rubric versions.',
    tags: tag,
    auth: 'workspace',
    params: wsId({}),
    response: z.array(ofmRubricVersion),
  }),
  createRubricVersion: endpoint({
    id: 'ofm.rubrics.create',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/rubrics',
    summary: 'Create a draft rubric version (weights add up to 100 %).',
    tags: tag,
    auth: 'workspace',
    permission: 'quality.publish',
    idempotent: true,
    params: wsId({}),
    body: z.object({ name: z.string().trim().min(2).max(120), rubricKey: z.string().regex(/^[a-z][a-z0-9_]{1,59}$/), criteria: z.array(ofmRubricCriterion).min(1).max(20) }),
    response: ofmRubricVersion,
    successStatus: 201,
  }),
  publishRubricVersion: endpoint({
    id: 'ofm.rubrics.publish',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/rubrics/{rubricVersionId}/publish',
    summary: 'Publish a rubric version (frozen; the previous published version of the same rubric is retired).',
    tags: tag,
    auth: 'workspace',
    permission: 'quality.publish',
    idempotent: true,
    ifMatch: true,
    params: wsId({ rubricVersionId: uuid }),
    response: ofmRubricVersion,
  }),
  listQuality: endpoint({
    id: 'ofm.quality.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/ofm/quality-reviews',
    summary: 'Quality reviews: published reviews of mine, reviews I write, or all in scope. Drafts are visible to reviewers only.',
    tags: tag,
    auth: 'workspace',
    params: wsId({}),
    query: pageQuery.extend({
      view: z.enum(['mine', 'reviewing', 'all']).default('all'),
      state: csv(z.enum(QUALITY_REVIEW_STATES)).optional(),
      subjectMembershipId: uuid.optional(),
      projectId: uuid.optional(),
    }),
    response: page(ofmQualityReview),
  }),
  getQuality: endpoint({
    id: 'ofm.quality.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/ofm/quality-reviews/{reviewId}',
    summary: 'Quality review with rubric version, scores, evidence and dispute history.',
    tags: tag,
    auth: 'workspace',
    params: wsId({ reviewId: uuid }),
    response: ofmQualityReview,
  }),
  createQuality: endpoint({
    id: 'ofm.quality.create',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/quality-reviews',
    summary: 'Draft a review of a shift or operation (never of your own work).',
    tags: tag,
    auth: 'workspace',
    permission: 'quality.write',
    idempotent: true,
    params: wsId({}),
    body: z.object({
      subjectType: z.enum(['shift', 'operation']),
      subjectId: uuid,
      rubricVersionId: uuid,
      scores: z.array(ofmScore).max(20).default([]),
      factualNotes: z.string().max(LIMITS.noteMax).nullable().optional(),
      improvements: z.string().max(LIMITS.noteMax).nullable().optional(),
    }),
    response: ofmQualityReview,
    successStatus: 201,
  }),
  updateQuality: endpoint({
    id: 'ofm.quality.update',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/ofm/quality-reviews/{reviewId}',
    summary: 'Edit a draft review.',
    tags: tag,
    auth: 'workspace',
    permission: 'quality.write',
    ifMatch: true,
    params: wsId({ reviewId: uuid }),
    body: z.object({
      rubricVersionId: uuid.optional(),
      scores: z.array(ofmScore).max(20).optional(),
      factualNotes: z.string().max(LIMITS.noteMax).nullable().optional(),
      improvements: z.string().max(LIMITS.noteMax).nullable().optional(),
    }),
    response: ofmQualityReview,
  }),
  publishQuality: endpoint({
    id: 'ofm.quality.publish',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/quality-reviews/{reviewId}/publish',
    summary: 'Publish (frozen). Every criterion scored 0–4 or Not Applicable; scores 0/1 need evidence.',
    tags: tag,
    auth: 'workspace',
    permission: 'quality.publish',
    idempotent: true,
    ifMatch: true,
    params: wsId({ reviewId: uuid }),
    response: ofmQualityReview,
  }),
  acknowledgeQuality: endpoint({
    id: 'ofm.quality.acknowledge',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/quality-reviews/{reviewId}/acknowledge',
    summary: 'The reviewed member acknowledges the review, optionally with a response.',
    tags: tag,
    auth: 'workspace',
    idempotent: true,
    ifMatch: true,
    params: wsId({ reviewId: uuid }),
    body: z.object({ response: z.string().trim().max(4000).optional() }),
    response: ofmQualityReview,
  }),
  disputeQuality: endpoint({
    id: 'ofm.quality.dispute',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/quality-reviews/{reviewId}/dispute',
    summary: 'The reviewed member disputes the review; the original score is preserved.',
    tags: tag,
    auth: 'workspace',
    idempotent: true,
    ifMatch: true,
    params: wsId({ reviewId: uuid }),
    body: z.object({ reason }),
    response: ofmQualityReview,
  }),
  resolveDispute: endpoint({
    id: 'ofm.quality.resolveDispute',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/quality-disputes/{disputeId}/resolve',
    summary: 'Resolve a dispute: uphold, withdraw, or revise with a replacement review revision (original kept as history).',
    tags: tag,
    auth: 'workspace',
    permission: 'quality.publish',
    idempotent: true,
    params: wsId({ disputeId: uuid }),
    body: z.object({
      decision: z.enum(['upheld', 'revised', 'withdrawn']),
      reason,
      replacementScores: z.array(ofmScore).max(20).optional(),
      replacementFactualNotes: z.string().max(LIMITS.noteMax).nullable().optional(),
    }),
    response: ofmQualityReview,
  }),
  createImprovementTask: endpoint({
    id: 'ofm.quality.createImprovementTask',
    method: 'POST',
    path: '/workspaces/{workspaceId}/ofm/quality-reviews/{reviewId}/improvement-task',
    summary: 'Create an improvement task for the reviewed member (no pay deductions or hidden ratings).',
    tags: tag,
    auth: 'workspace',
    permission: 'tasks.create',
    idempotent: true,
    params: wsId({ reviewId: uuid }),
    body: z.object({ title, description: z.string().trim().max(4000).optional(), dueAt: ts.nullable().optional() }),
    response: z.object({ taskId: uuid }),
    successStatus: 201,
  }),
};

export type OfmEndpoints = typeof ofmEndpoints;
