import { z } from 'zod';
import { DIRECTION_STATUSES, PROJECT_STATUSES, PROJECT_TYPES, RESPONSIBILITIES, LIMITS } from '@castlane/domain';
import { endpoint } from './core';
import {
  boolQuery,
  csv,
  impactItem,
  isoDate,
  isoDateTime,
  memberRef,
  money,
  okResponse,
  page,
  pageQuery,
  reason,
  shortName,
  tags,
  uuid,
  wsId,
} from './common';

// ——— People lookup (used by every member picker) ———

export const personOption = z.object({
  membershipId: uuid,
  displayName: z.string(),
  email: z.string().nullable(),
  avatarUrl: z.string().nullable(),
  status: z.string(),
  title: z.string().nullable(),
});

export const peopleEndpoints = {
  lookup: endpoint({
    id: 'members.lookup',
    method: 'GET',
    path: '/workspaces/{workspaceId}/people',
    summary: 'Member picker: active members (optionally those with access to a project). E-mail only with members.read.',
    tags: ['Team'],
    auth: 'workspace',
    params: wsId({}),
    query: z.object({
      q: z.string().max(100).optional(),
      projectId: uuid.optional(),
      permission: z.string().max(80).optional(),
      includeInactive: boolQuery.optional(),
      limit: z.coerce.number().int().min(1).max(200).default(50),
    }),
    response: z.array(personOption),
  }),
};

// ——— Directions (S12) ———

export const directionRow = z.object({
  id: uuid,
  name: z.string(),
  description: z.string().nullable(),
  status: z.enum(DIRECTION_STATUSES),
  lead: memberRef.nullable(),
  activeProjects: z.number().int(),
  openTasks: z.number().int(),
  updatedAt: isoDateTime,
  rowVersion: z.number().int(),
});
export type DirectionRow = z.infer<typeof directionRow>;

export const directionEndpoints = {
  list: endpoint({
    id: 'directions.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/directions',
    summary: 'List directions with lead and scoped counts.',
    tags: ['Directions'],
    auth: 'workspace',
    permission: 'directions.read',
    params: wsId({}),
    query: z.object({ includeArchived: boolQuery.optional() }),
    response: z.array(directionRow),
  }),
  create: endpoint({
    id: 'directions.create',
    method: 'POST',
    path: '/workspaces/{workspaceId}/directions',
    summary: 'Create a direction.',
    tags: ['Directions'],
    auth: 'workspace',
    permission: 'directions.manage',
    idempotent: true,
    params: wsId({}),
    body: z.object({ name: shortName, description: z.string().max(LIMITS.noteMax).nullable().optional(), leadMembershipId: uuid.nullable().optional() }),
    response: directionRow,
    successStatus: 201,
  }),
  update: endpoint({
    id: 'directions.update',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/directions/{directionId}',
    summary: 'Rename / change description or lead. Lead change shows access impact first (preview endpoint).',
    tags: ['Directions'],
    auth: 'workspace',
    permission: 'directions.manage',
    ifMatch: true,
    params: wsId({ directionId: uuid }),
    body: z.object({ name: shortName.optional(), description: z.string().max(LIMITS.noteMax).nullable().optional(), leadMembershipId: uuid.nullable().optional() }),
    response: directionRow,
  }),
  archive: endpoint({
    id: 'directions.archive',
    method: 'POST',
    path: '/workspaces/{workspaceId}/directions/{directionId}/archive',
    summary: 'Archive a direction; refused while active projects remain (move or archive them first).',
    tags: ['Directions'],
    auth: 'workspace',
    permission: 'directions.manage',
    idempotent: true,
    ifMatch: true,
    params: wsId({ directionId: uuid }),
    body: z.object({ reason: reason.optional() }),
    response: directionRow,
  }),
};

// ——— Projects (S13–S15) ———

export const projectSummary = z.object({
  id: uuid,
  name: z.string(),
  type: z.enum(PROJECT_TYPES),
  status: z.enum(PROJECT_STATUSES),
  direction: z.object({ id: uuid, name: z.string() }),
  owner: memberRef,
  tags: z.array(z.string()),
  ofmEnabled: z.boolean(),
  coverUrl: z.string().nullable(),
  openTasks: z.number().int(),
  nextPublicationAt: isoDateTime.nullable(),
  metricsUpdatedAt: isoDateTime.nullable(),
  /** Present only for members with budgets.read on the project (omitted otherwise, not null). */
  budget: z.object({ planned: money, periodStart: isoDate, periodEnd: isoDate }).nullable().optional(),
  archivedAt: isoDateTime.nullable(),
  updatedAt: isoDateTime,
  rowVersion: z.number().int(),
});
export type ProjectSummary = z.infer<typeof projectSummary>;

export const projectMember = z.object({
  id: uuid,
  member: memberRef,
  responsibility: z.enum(RESPONSIBILITIES).nullable(),
  note: z.string().nullable(),
  validFrom: isoDateTime,
  validTo: isoDateTime.nullable(),
});

export const projectDetail = projectSummary.extend({
  briefSummary: z.string().nullable(),
  description: z.string().nullable(),
  language: z.string().nullable(),
  targetMarkets: z.array(z.string()),
  audience: z.string().nullable(),
  startDate: isoDate.nullable(),
  coverAssetId: uuid.nullable(),
  statusReason: z.string().nullable(),
  completedAt: isoDateTime.nullable(),
  reviewPolicy: z.object({ contentQualityStep: z.boolean(), releaseApprovalStep: z.boolean(), allowSelfReview: z.boolean() }),
  counts: z.object({ accounts: z.number().int(), content: z.number().int(), openTasks: z.number().int(), scheduledPublications: z.number().int(), characters: z.number().int() }),
  team: z.array(projectMember),
  milestones: z.array(z.object({ id: uuid, title: z.string(), dueDate: isoDate.nullable(), completedAt: isoDateTime.nullable() })),
  decisions: z.array(z.object({ id: uuid, title: z.string(), body: z.string(), version: z.number().int(), pinnedAt: isoDateTime.nullable(), decidedAt: isoDateTime })),
  /** Fields that cannot change any more, with the reason (e.g. type after seasons exist). */
  locked: z.object({ type: z.string().nullable() }),
  permissions: z.object({
    update: z.boolean(),
    archive: z.boolean(),
    manageTeam: z.boolean(),
    createContent: z.boolean(),
    createAccount: z.boolean(),
    createTask: z.boolean(),
  }),
});
export type ProjectDetail = z.infer<typeof projectDetail>;

const projectFields = {
  name: shortName,
  directionId: uuid,
  ownerMembershipId: uuid,
  briefSummary: z.string().trim().max(2000).nullable().optional(),
  description: z.string().max(LIMITS.noteMax).nullable().optional(),
  language: z.string().max(20).nullable().optional(),
  targetMarkets: z.array(z.string().trim().min(2).max(40)).max(30).optional(),
  audience: z.string().max(2000).nullable().optional(),
  tags: tags.optional(),
  startDate: isoDate.nullable().optional(),
  coverAssetId: uuid.nullable().optional(),
  ofmEnabled: z.boolean().optional(),
};

export const projectSort = z.enum(['name', 'updatedAt', 'status', 'type']);

export const projectEndpoints = {
  list: endpoint({
    id: 'projects.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/projects',
    summary: 'List projects in the actor’s scope (filters, cursor pagination). Archived hidden by default.',
    tags: ['Projects'],
    auth: 'workspace',
    permission: 'projects.read',
    params: wsId({}),
    query: pageQuery.extend({
      q: z.string().trim().max(120).optional(),
      status: csv(z.enum(PROJECT_STATUSES)).optional(),
      type: csv(z.enum(PROJECT_TYPES)).optional(),
      directionId: uuid.optional(),
      ownerMembershipId: uuid.optional(),
      tag: z.string().max(40).optional(),
      includeArchived: boolQuery.optional(),
      sort: projectSort.default('updatedAt'),
      direction: z.enum(['asc', 'desc']).default('desc'),
    }),
    response: page(projectSummary),
  }),
  get: endpoint({
    id: 'projects.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/projects/{projectId}',
    summary: 'Project workspace: brief, team, counts, milestones, decisions and allowed actions.',
    tags: ['Projects'],
    auth: 'workspace',
    permission: 'projects.read',
    params: wsId({ projectId: uuid }),
    response: projectDetail,
  }),
  create: endpoint({
    id: 'projects.create',
    method: 'POST',
    path: '/workspaces/{workspaceId}/projects',
    summary: 'Create a project (no accounts or statistics are created).',
    tags: ['Projects'],
    auth: 'workspace',
    permission: 'projects.create',
    idempotent: true,
    params: wsId({}),
    body: z.object({ ...projectFields, type: z.enum(PROJECT_TYPES), activate: z.boolean().optional() }),
    response: projectDetail,
    successStatus: 201,
  }),
  update: endpoint({
    id: 'projects.update',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/projects/{projectId}',
    summary: 'Update project fields (type is locked once seasons or OFM operations exist).',
    tags: ['Projects'],
    auth: 'workspace',
    permission: 'projects.update',
    ifMatch: true,
    params: wsId({ projectId: uuid }),
    body: z
      .object({ ...projectFields, type: z.enum(PROJECT_TYPES) })
      .partial()
      .extend({ reviewPolicy: z.object({ contentQualityStep: z.boolean(), releaseApprovalStep: z.boolean(), allowSelfReview: z.boolean() }).optional() }),
    response: projectDetail,
  }),
  transition: endpoint({
    id: 'projects.transition',
    method: 'POST',
    path: '/workspaces/{workspaceId}/projects/{projectId}/transition',
    summary: 'Draft→Active↔Paused→Completed→Archived; Completed→Active (reopen) needs a reason.',
    tags: ['Projects'],
    auth: 'workspace',
    permission: 'projects.update',
    idempotent: true,
    ifMatch: true,
    params: wsId({ projectId: uuid }),
    body: z.object({ targetState: z.enum(PROJECT_STATUSES), reason: reason.optional() }),
    response: projectDetail,
  }),
  archivePreview: endpoint({
    id: 'projects.archivePreview',
    method: 'GET',
    path: '/workspaces/{workspaceId}/projects/{projectId}/archive-preview',
    summary: 'Open obligations that block completing/archiving the project, and non-blocking warnings.',
    tags: ['Projects'],
    auth: 'workspace',
    permission: 'projects.archive',
    params: wsId({ projectId: uuid }),
    response: z.object({ title: z.string(), rowVersion: z.number().int(), items: z.array(impactItem) }),
  }),
  transferDirection: endpoint({
    id: 'projects.transferDirection',
    method: 'POST',
    path: '/workspaces/{workspaceId}/projects/{projectId}/transfer-direction',
    summary: 'Move the project to another direction; historical reports keep direction_at_event.',
    tags: ['Projects'],
    auth: 'workspace',
    permission: 'projects.update',
    idempotent: true,
    ifMatch: true,
    params: wsId({ projectId: uuid }),
    body: z.object({ directionId: uuid, reason }),
    response: projectDetail,
  }),
  addMember: endpoint({
    id: 'projects.addMember',
    method: 'POST',
    path: '/workspaces/{workspaceId}/projects/{projectId}/members',
    summary: 'Assign a member to the project (limits their role scope; grants no sensitive permissions).',
    tags: ['Projects'],
    auth: 'workspace',
    permission: 'project.members.manage',
    idempotent: true,
    params: wsId({ projectId: uuid }),
    body: z.object({ membershipId: uuid, responsibility: z.enum(RESPONSIBILITIES).nullable().optional(), note: z.string().max(500).nullable().optional() }),
    response: projectMember,
    successStatus: 201,
  }),
  endMember: endpoint({
    id: 'projects.endMember',
    method: 'POST',
    path: '/workspaces/{workspaceId}/projects/{projectId}/members/{projectMemberId}/end',
    summary: 'End a project assignment (history is kept).',
    tags: ['Projects'],
    auth: 'workspace',
    permission: 'project.members.manage',
    idempotent: true,
    params: wsId({ projectId: uuid, projectMemberId: uuid }),
    body: z.object({ reason: reason.optional() }),
    response: okResponse,
  }),
  addMilestone: endpoint({
    id: 'projects.addMilestone',
    method: 'POST',
    path: '/workspaces/{workspaceId}/projects/{projectId}/milestones',
    summary: 'Add a milestone.',
    tags: ['Projects'],
    auth: 'workspace',
    permission: 'projects.update',
    idempotent: true,
    params: wsId({ projectId: uuid }),
    body: z.object({ title: shortName, dueDate: isoDate.nullable().optional() }),
    response: okResponse,
    successStatus: 201,
  }),
  pinDecision: endpoint({
    id: 'projects.pinDecision',
    method: 'POST',
    path: '/workspaces/{workspaceId}/projects/{projectId}/decisions',
    summary: 'Record and pin a decision (frozen text version).',
    tags: ['Projects'],
    auth: 'workspace',
    permission: 'projects.update',
    idempotent: true,
    params: wsId({ projectId: uuid }),
    body: z.object({ title: shortName, body: z.string().trim().min(3).max(5000) }),
    response: okResponse,
    successStatus: 201,
  }),
  activity: endpoint({
    id: 'projects.activity',
    method: 'GET',
    path: '/workspaces/{workspaceId}/projects/{projectId}/activity',
    summary: 'Meaningful project history (no sensitive values, masked diffs).',
    tags: ['Projects'],
    auth: 'workspace',
    permission: 'projects.read',
    params: wsId({ projectId: uuid }),
    query: pageQuery,
    response: page(
      z.object({
        id: uuid,
        action: z.string(),
        entityType: z.string().nullable(),
        entityId: uuid.nullable(),
        actorName: z.string().nullable(),
        occurredAt: isoDateTime,
        reason: z.string().nullable(),
        changes: z.array(z.object({ field: z.string(), from: z.unknown().optional(), to: z.unknown().optional() })),
      }),
    ),
  }),
};
