import { z } from 'zod';
import { CONTENT_FORMATS, CONTENT_STAGES, DEAL_STAGES, LIMITS, PARTNER_KINDS, PLATFORMS } from '@castlane/domain';
import { endpoint } from './core';
import { boolQuery, csv, currencyCode, isoDate, isoDateTime, memberRef, money, page, pageQuery, reason, shortName, tags, uuid, wsId } from './common';

/**
 * Partners (S73) and partnership deals (S74). A partner is a business identity, never a system
 * user; the CRM does not e-mail partners. Deal amounts are plans only: a Won deal never creates
 * income or payments (T138). Amount fields are omitted (not null) without finance access.
 */

export const PARTNER_INTERACTION_KINDS = ['call', 'meeting', 'email_summary', 'note', 'other'] as const;
export const DELIVERABLE_STATUSES = ['open', 'delivered', 'accepted', 'cancelled'] as const;

export const partnerRow = z.object({
  id: uuid,
  kind: z.enum(PARTNER_KINDS),
  name: z.string(),
  contactName: z.string().nullable(),
  businessEmail: z.string().nullable(),
  website: z.string().nullable(),
  owner: memberRef,
  tags: z.array(z.string()),
  logoUrl: z.string().nullable(),
  logoAssetId: uuid.nullable(),
  activeDeals: z.number().int(),
  lastInteractionAt: isoDateTime.nullable(),
  mergedInto: z.object({ id: uuid, name: z.string() }).nullable(),
  archivedAt: isoDateTime.nullable(),
  updatedAt: isoDateTime,
  rowVersion: z.number().int(),
});
export type PartnerRow = z.infer<typeof partnerRow>;

export const partnerInteraction = z.object({
  id: uuid,
  partnerId: uuid,
  deal: z.object({ id: uuid, title: z.string() }).nullable(),
  occurredAt: isoDateTime,
  kind: z.enum(PARTNER_INTERACTION_KINDS),
  summary: z.string(),
  author: memberRef.nullable(),
  createdAt: isoDateTime,
});
export type PartnerInteraction = z.infer<typeof partnerInteraction>;

export const dealStageRef = z.enum(DEAL_STAGES);

export const dealSummary = z.object({
  id: uuid,
  title: z.string(),
  partner: z.object({ id: uuid, name: z.string() }),
  owner: memberRef,
  stage: dealStageRef,
  projects: z.array(z.object({ id: uuid, name: z.string() })),
  /** Planned amount; present only for members with finance access to the deal’s projects. */
  amount: money.nullable().optional(),
  expectedCloseDate: isoDate.nullable(),
  campaign: z.object({ id: uuid, name: z.string() }).nullable(),
  deliverables: z.object({ total: z.number().int(), open: z.number().int() }),
  closedAt: isoDateTime.nullable(),
  archivedAt: isoDateTime.nullable(),
  updatedAt: isoDateTime,
  rowVersion: z.number().int(),
});
export type DealSummary = z.infer<typeof dealSummary>;

export const partnerDetail = partnerRow.extend({
  notes: z.string().nullable(),
  deals: z.array(dealSummary),
  hiddenDealCount: z.number().int(),
  permissions: z.object({ update: z.boolean(), archive: z.boolean(), logInteraction: z.boolean(), createDeal: z.boolean(), merge: z.boolean() }),
});
export type PartnerDetail = z.infer<typeof partnerDetail>;

export const deliverableRow = z.object({
  id: uuid,
  dealId: uuid,
  title: z.string(),
  format: z.enum(CONTENT_FORMATS).nullable(),
  project: z.object({ id: uuid, name: z.string() }).nullable(),
  account: z.object({ id: uuid, handle: z.string().nullable(), platform: z.enum(PLATFORMS) }).nullable(),
  dueAt: isoDateTime.nullable(),
  acceptanceCriteria: z.string().nullable(),
  contentItem: z.object({ id: uuid, title: z.string(), stage: z.enum(CONTENT_STAGES) }).nullable(),
  /** Agreed amount; present only with finance access. */
  agreedAmount: money.nullable().optional(),
  status: z.enum(DELIVERABLE_STATUSES),
  archivedAt: isoDateTime.nullable(),
  updatedAt: isoDateTime,
  rowVersion: z.number().int(),
});
export type DeliverableRow = z.infer<typeof deliverableRow>;

export const paymentScheduleItem = z.object({ dueDate: isoDate, amount: z.string(), currency: currencyCode, note: z.string().trim().max(500).optional() });

export const dealDocument = z.object({
  linkId: uuid,
  assetId: uuid,
  name: z.string(),
  restricted: z.boolean(),
  status: z.string().nullable(),
  createdAt: isoDateTime,
  canDownload: z.boolean(),
});

export const dealDetail = dealSummary.extend({
  stageReason: z.string().nullable(),
  outcome: z.string().nullable(),
  /** Planned payment dates and amounts; present only with finance access. Never a payment record. */
  paymentSchedule: z.array(paymentScheduleItem).optional(),
  deliverableItems: z.array(deliverableRow),
  stageEvents: z.array(z.object({ id: uuid, fromStage: dealStageRef.nullable(), toStage: dealStageRef, reason: z.string().nullable(), occurredAt: isoDateTime, actorName: z.string().nullable() })),
  documents: z.array(dealDocument),
  interactions: z.array(partnerInteraction),
  allowedTransitions: z.array(dealStageRef),
  permissions: z.object({
    update: z.boolean(),
    transition: z.boolean(),
    archive: z.boolean(),
    viewAmounts: z.boolean(),
    editAmounts: z.boolean(),
    manageDeliverables: z.boolean(),
    createCampaign: z.boolean(),
    uploadDocuments: z.boolean(),
    logInteraction: z.boolean(),
  }),
});
export type DealDetail = z.infer<typeof dealDetail>;

const partnerFields = {
  kind: z.enum(PARTNER_KINDS),
  name: shortName,
  contactName: z.string().trim().max(LIMITS.shortNameMax).nullable().optional(),
  businessEmail: z.string().trim().max(254).nullable().optional(),
  website: z.string().trim().max(LIMITS.urlMax).nullable().optional(),
  ownerMembershipId: uuid,
  tags: tags.optional(),
  logoAssetId: uuid.nullable().optional(),
  notes: z.string().max(LIMITS.noteMax).nullable().optional(),
};

const dealFields = {
  title: shortName,
  partnerId: uuid,
  ownerMembershipId: uuid,
  projectIds: z.array(uuid).min(1).max(20),
  amount: money.nullable().optional(),
  expectedCloseDate: isoDate.nullable().optional(),
  campaignId: uuid.nullable().optional(),
  paymentSchedule: z.array(paymentScheduleItem).max(50).optional(),
};

const deliverableFields = {
  title: shortName,
  format: z.enum(CONTENT_FORMATS).nullable().optional(),
  projectId: uuid.nullable().optional(),
  accountId: uuid.nullable().optional(),
  dueAt: isoDateTime.nullable().optional(),
  acceptanceCriteria: z.string().max(LIMITS.noteMax).nullable().optional(),
  contentItemId: uuid.nullable().optional(),
  agreedAmount: money.nullable().optional(),
};

export const partnerEndpoints = {
  list: endpoint({
    id: 'partners.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/partners',
    summary: 'Partners visible to the actor with active deals and last interaction.',
    tags: ['Partners'],
    auth: 'workspace',
    permission: 'partners.read',
    params: wsId({}),
    query: pageQuery.extend({
      q: z.string().trim().max(120).optional(),
      kind: csv(z.enum(PARTNER_KINDS)).optional(),
      ownerMembershipId: uuid.optional(),
      tag: z.string().max(40).optional(),
      includeArchived: boolQuery.optional(),
      sort: z.enum(['name', 'updatedAt']).default('name'),
      direction: z.enum(['asc', 'desc']).default('asc'),
    }),
    response: page(partnerRow),
  }),
  get: endpoint({
    id: 'partners.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/partners/{partnerId}',
    summary: 'Partner with its visible deals and allowed actions.',
    tags: ['Partners'],
    auth: 'workspace',
    permission: 'partners.read',
    params: wsId({ partnerId: uuid }),
    response: partnerDetail,
  }),
  create: endpoint({
    id: 'partners.create',
    method: 'POST',
    path: '/workspaces/{workspaceId}/partners',
    summary: 'Add a partner (organization or person). The e-mail is a record only; nothing is sent.',
    tags: ['Partners'],
    auth: 'workspace',
    permission: 'partners.write',
    idempotent: true,
    params: wsId({}),
    body: z.object(partnerFields),
    response: partnerDetail,
    successStatus: 201,
  }),
  update: endpoint({
    id: 'partners.update',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/partners/{partnerId}',
    summary: 'Edit a partner.',
    tags: ['Partners'],
    auth: 'workspace',
    permission: 'partners.write',
    ifMatch: true,
    params: wsId({ partnerId: uuid }),
    body: z.object(partnerFields).partial(),
    response: partnerDetail,
  }),
  archive: endpoint({
    id: 'partners.archive',
    method: 'POST',
    path: '/workspaces/{workspaceId}/partners/{partnerId}/archive',
    summary: 'Archive a partner; blocked while it has open deals.',
    tags: ['Partners'],
    auth: 'workspace',
    permission: 'partners.write',
    idempotent: true,
    ifMatch: true,
    params: wsId({ partnerId: uuid }),
    body: z.object({ reason: reason.optional() }),
    response: partnerDetail,
  }),
  restore: endpoint({
    id: 'partners.restore',
    method: 'POST',
    path: '/workspaces/{workspaceId}/partners/{partnerId}/restore',
    summary: 'Restore an archived partner (merged partners stay merged).',
    tags: ['Partners'],
    auth: 'workspace',
    permission: 'partners.write',
    idempotent: true,
    ifMatch: true,
    params: wsId({ partnerId: uuid }),
    body: z.object({}),
    response: partnerDetail,
  }),
  interactions: endpoint({
    id: 'partners.interactions',
    method: 'GET',
    path: '/workspaces/{workspaceId}/partners/{partnerId}/interactions',
    summary: 'Logged interactions with the partner, newest first.',
    tags: ['Partners'],
    auth: 'workspace',
    permission: 'partners.read',
    params: wsId({ partnerId: uuid }),
    query: pageQuery.extend({ dealId: uuid.optional() }),
    response: page(partnerInteraction),
  }),
  logInteraction: endpoint({
    id: 'partners.logInteraction',
    method: 'POST',
    path: '/workspaces/{workspaceId}/partners/{partnerId}/interactions',
    summary: 'Log an interaction that happened outside the CRM (manual record).',
    tags: ['Partners'],
    auth: 'workspace',
    permission: 'partners.write',
    idempotent: true,
    params: wsId({ partnerId: uuid }),
    body: z.object({
      occurredAt: isoDateTime,
      kind: z.enum(PARTNER_INTERACTION_KINDS),
      summary: z.string().trim().min(3).max(LIMITS.noteMax),
      dealId: uuid.nullable().optional(),
    }),
    response: partnerInteraction,
    successStatus: 201,
  }),
  mergePreview: endpoint({
    id: 'partners.mergePreview',
    method: 'GET',
    path: '/workspaces/{workspaceId}/partners/{partnerId}/merge-preview',
    summary: 'Preview merging this partner into another: moved deals and interactions, field differences, token (10 min).',
    tags: ['Partners'],
    auth: 'workspace',
    permission: 'partners.write',
    params: wsId({ partnerId: uuid }),
    query: z.object({ targetId: uuid }),
    response: z.object({
      source: partnerRow,
      target: partnerRow,
      moves: z.object({ deals: z.number().int(), interactions: z.number().int() }),
      differences: z.array(z.object({ field: z.string(), source: z.string().nullable(), target: z.string().nullable() })),
      previewToken: z.string(),
      expiresAt: isoDateTime,
    }),
  }),
  merge: endpoint({
    id: 'partners.merge',
    method: 'POST',
    path: '/workspaces/{workspaceId}/partners/{partnerId}/merge',
    summary: 'Merge this partner into the target: deals and interactions move, this partner is archived as merged.',
    tags: ['Partners'],
    auth: 'workspace',
    permission: 'partners.write',
    idempotent: true,
    ifMatch: true,
    params: wsId({ partnerId: uuid }),
    body: z.object({ targetId: uuid, previewToken: z.string().min(10).max(400) }),
    response: partnerDetail,
  }),
};

export const dealEndpoints = {
  list: endpoint({
    id: 'deals.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/deals',
    summary: 'Deals in the actor’s scope. Closed stages included unless filtered; archived hidden by default.',
    tags: ['Deals'],
    auth: 'workspace',
    permission: 'deals.read',
    params: wsId({}),
    query: pageQuery.extend({
      q: z.string().trim().max(120).optional(),
      stage: csv(dealStageRef).optional(),
      partnerId: uuid.optional(),
      projectId: uuid.optional(),
      ownerMembershipId: uuid.optional(),
      includeArchived: boolQuery.optional(),
      sort: z.enum(['updatedAt', 'title', 'stage', 'expectedCloseDate']).default('updatedAt'),
      direction: z.enum(['asc', 'desc']).default('desc'),
    }),
    response: page(dealSummary),
  }),
  get: endpoint({
    id: 'deals.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/deals/{dealId}',
    summary: 'Deal workspace: deliverables, stage history, documents, interactions and allowed actions.',
    tags: ['Deals'],
    auth: 'workspace',
    permission: 'deals.read',
    params: wsId({ dealId: uuid }),
    response: dealDetail,
  }),
  create: endpoint({
    id: 'deals.create',
    method: 'POST',
    path: '/workspaces/{workspaceId}/deals',
    summary: 'Create a deal (stage Lead). The amount is a plan, not revenue.',
    tags: ['Deals'],
    auth: 'workspace',
    permission: 'deals.write',
    idempotent: true,
    params: wsId({}),
    body: z.object(dealFields),
    response: dealDetail,
    successStatus: 201,
  }),
  update: endpoint({
    id: 'deals.update',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/deals/{dealId}',
    summary: 'Edit deal fields (the stage changes through the transition command).',
    tags: ['Deals'],
    auth: 'workspace',
    permission: 'deals.write',
    ifMatch: true,
    params: wsId({ dealId: uuid }),
    body: z.object(dealFields).partial(),
    response: dealDetail,
  }),
  transition: endpoint({
    id: 'deals.transition',
    method: 'POST',
    path: '/workspaces/{workspaceId}/deals/{dealId}/transition',
    summary: 'Move the deal stage. Lost/Cancelled need a reason. Won never records income or payment.',
    tags: ['Deals'],
    auth: 'workspace',
    permission: 'deals.write',
    idempotent: true,
    ifMatch: true,
    params: wsId({ dealId: uuid }),
    body: z.object({ targetStage: dealStageRef, reason: reason.optional(), outcome: z.string().trim().max(2000).optional() }),
    response: dealDetail,
  }),
  archive: endpoint({
    id: 'deals.archive',
    method: 'POST',
    path: '/workspaces/{workspaceId}/deals/{dealId}/archive',
    summary: 'Archive a closed deal (fulfilled, lost or cancelled).',
    tags: ['Deals'],
    auth: 'workspace',
    permission: 'deals.write',
    idempotent: true,
    ifMatch: true,
    params: wsId({ dealId: uuid }),
    body: z.object({ reason: reason.optional() }),
    response: dealDetail,
  }),
  restore: endpoint({
    id: 'deals.restore',
    method: 'POST',
    path: '/workspaces/{workspaceId}/deals/{dealId}/restore',
    summary: 'Restore an archived deal.',
    tags: ['Deals'],
    auth: 'workspace',
    permission: 'deals.write',
    idempotent: true,
    ifMatch: true,
    params: wsId({ dealId: uuid }),
    body: z.object({}),
    response: dealDetail,
  }),
  createCampaign: endpoint({
    id: 'deals.createCampaign',
    method: 'POST',
    path: '/workspaces/{workspaceId}/deals/{dealId}/create-campaign',
    summary: 'Create a planned campaign for the deal’s partner and projects and link it (no results are created).',
    tags: ['Deals'],
    auth: 'workspace',
    permission: 'campaigns.write',
    idempotent: true,
    ifMatch: true,
    params: wsId({ dealId: uuid }),
    body: z.object({ name: shortName, objective: z.string().trim().min(3).max(2000), startDate: isoDate, endDate: isoDate, ownerMembershipId: uuid.optional() }),
    response: dealDetail,
  }),
  listDeliverables: endpoint({
    id: 'deals.listDeliverables',
    method: 'GET',
    path: '/workspaces/{workspaceId}/deals/{dealId}/deliverables',
    summary: 'Deliverables of the deal.',
    tags: ['Deals'],
    auth: 'workspace',
    permission: 'deals.read',
    params: wsId({ dealId: uuid }),
    query: z.object({ includeArchived: boolQuery.optional() }),
    response: z.array(deliverableRow),
  }),
  createDeliverable: endpoint({
    id: 'deals.createDeliverable',
    method: 'POST',
    path: '/workspaces/{workspaceId}/deals/{dealId}/deliverables',
    summary: 'Add a deliverable (format, project/account, due, acceptance criteria, linked content).',
    tags: ['Deals'],
    auth: 'workspace',
    permission: 'deals.write',
    idempotent: true,
    params: wsId({ dealId: uuid }),
    body: z.object(deliverableFields),
    response: deliverableRow,
    successStatus: 201,
  }),
  getDeliverable: endpoint({
    id: 'deals.getDeliverable',
    method: 'GET',
    path: '/workspaces/{workspaceId}/deliverables/{deliverableId}',
    summary: 'One deliverable.',
    tags: ['Deals'],
    auth: 'workspace',
    permission: 'deals.read',
    params: wsId({ deliverableId: uuid }),
    response: deliverableRow,
  }),
  updateDeliverable: endpoint({
    id: 'deals.updateDeliverable',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/deliverables/{deliverableId}',
    summary: 'Edit a deliverable.',
    tags: ['Deals'],
    auth: 'workspace',
    permission: 'deals.write',
    ifMatch: true,
    params: wsId({ deliverableId: uuid }),
    body: z.object(deliverableFields).partial(),
    response: deliverableRow,
  }),
  transitionDeliverable: endpoint({
    id: 'deals.transitionDeliverable',
    method: 'POST',
    path: '/workspaces/{workspaceId}/deliverables/{deliverableId}/transition',
    summary: 'Open → Delivered → Accepted; Delivered → Open (rework, reason); Open/Delivered → Cancelled (reason).',
    tags: ['Deals'],
    auth: 'workspace',
    permission: 'deals.write',
    idempotent: true,
    ifMatch: true,
    params: wsId({ deliverableId: uuid }),
    body: z.object({ targetStatus: z.enum(DELIVERABLE_STATUSES), reason: reason.optional() }),
    response: deliverableRow,
  }),
};
