import { z } from 'zod';
import { DUPLICATE_POLICIES, EXPORT_FORMATS, EXPORT_STATES, IMPORT_DATASETS, IMPORT_STATES, LIMITS } from '@castlane/domain';
import { endpoint } from './core';
import { csv, isoDateTime, memberRef, okResponse, page, pageQuery, shortName, timezone, uuid, wsId } from './common';

// ——— Import Center (S66, section 22.1) ———

export const IMPORT_MAX_BYTES = 20 * 1024 * 1024;
export const IMPORT_MAX_ROWS = 20_000;

export const importColumnInfo = z.object({
  key: z.string(),
  label: z.string(),
  type: z.string(),
  required: z.boolean(),
  enumValues: z.array(z.string()).nullable(),
  aliases: z.array(z.string()),
  description: z.string().nullable(),
});

export const importDatasetInfo = z.object({
  key: z.enum(IMPORT_DATASETS),
  label: z.string(),
  columns: z.array(importColumnInfo),
  duplicatePolicies: z.array(z.enum(DUPLICATE_POLICIES)),
  canCommit: z.boolean(),
});
export type ImportDatasetInfo = z.infer<typeof importDatasetInfo>;

export const importOptions = z.object({
  timezone,
  currency: z.string().length(3).optional(),
  dateFormat: z.enum(['iso', 'dd.mm.yyyy', 'mm/dd/yyyy', 'dd/mm/yyyy']).default('iso'),
  decimalSeparator: z.enum(['.', ',']).default('.'),
  duplicatePolicy: z.enum(DUPLICATE_POLICIES),
  /** XLSX only: import the stored (cached) results of formula cells; formulas are never evaluated. */
  acceptCachedFormulaValues: z.boolean().default(false),
});
export type ImportOptionsInput = z.infer<typeof importOptions>;

export const importIssue = z.object({ field: z.string(), code: z.string(), message: z.string() });

export const validationReport = z.object({
  reportNo: z.number().int(),
  validatedAt: isoDateTime,
  validatedBy: z.string(),
  fileHash: z.string(),
  duplicatePolicy: z.enum(DUPLICATE_POLICIES),
  totals: z.object({
    rows: z.number().int(),
    create: z.number().int(),
    update: z.number().int(),
    skip: z.number().int(),
    errorRows: z.number().int(),
    warningRows: z.number().int(),
    errors: z.number().int(),
    warnings: z.number().int(),
    cachedFormulaValues: z.number().int(),
  }),
  byIssue: z.array(z.object({ field: z.string(), code: z.string(), severity: z.enum(['error', 'warning']), count: z.number().int(), message: z.string() })),
});
export type ValidationReport = z.infer<typeof validationReport>;

export const importResult = z.object({
  created: z.number().int(),
  updated: z.number().int(),
  skipped: z.number().int(),
  createdIds: z.array(uuid),
  updatedIds: z.array(uuid),
  undo: z.object({ removed: z.number().int(), kept: z.number().int(), at: isoDateTime }).nullable().optional(),
});

export const importJobSummary = z.object({
  id: uuid,
  dataset: z.enum(IMPORT_DATASETS),
  datasetLabel: z.string(),
  state: z.enum(IMPORT_STATES),
  fileName: z.string(),
  fileKind: z.enum(['csv', 'xlsx']),
  byteSize: z.number().int(),
  rowCount: z.number().int().nullable(),
  requestedBy: memberRef,
  createdAt: isoDateTime,
  updatedAt: isoDateTime,
  committedAt: isoDateTime.nullable(),
  rowVersion: z.number().int(),
});
export type ImportJobSummary = z.infer<typeof importJobSummary>;

export const importJobDetail = importJobSummary.extend({
  fileHash: z.string(),
  headers: z.array(z.string()),
  mapping: z.record(z.string(), z.string().nullable()),
  /** Proposed mapping from header names and aliases (used until the member saves a mapping). */
  suggestedMapping: z.record(z.string(), z.string().nullable()),
  options: importOptions.nullable(),
  delimiter: z.enum([',', ';']).nullable(),
  hasFormulaCells: z.boolean(),
  validationReport: validationReport.nullable(),
  validationToken: z.string().nullable(),
  validatedAt: isoDateTime.nullable(),
  warningsAccepted: z.boolean(),
  result: importResult.nullable(),
  errorMessage: z.string().nullable(),
  undoneAt: isoDateTime.nullable(),
  progress: z.object({ state: z.string(), percent: z.number().int(), note: z.string().nullable() }).nullable(),
  permissions: z.object({ validate: z.boolean(), commit: z.boolean(), cancel: z.boolean(), undo: z.boolean() }),
});
export type ImportJobDetail = z.infer<typeof importJobDetail>;

export const importRowItem = z.object({
  id: uuid,
  rowNo: z.number().int(),
  status: z.enum(['pending', 'valid', 'warning', 'error', 'skipped']),
  action: z.enum(['create', 'update', 'skip']).nullable(),
  raw: z.record(z.string(), z.string()),
  mapped: z.record(z.string(), z.unknown()).nullable(),
  errors: z.array(importIssue),
  warnings: z.array(importIssue),
  targetId: uuid.nullable(),
  createdEntityId: uuid.nullable(),
});
export type ImportRowItem = z.infer<typeof importRowItem>;

const partUrl = z.object({ partNumber: z.number().int(), url: z.string(), method: z.literal('PUT'), headers: z.record(z.string(), z.string()) });

export const importEndpoints = {
  datasets: endpoint({
    id: 'imports.datasets',
    method: 'GET',
    path: '/workspaces/{workspaceId}/imports/datasets',
    summary: 'Datasets the member may import, with column definitions and duplicate policies.',
    tags: ['Imports'],
    auth: 'workspace',
    permission: 'imports.create',
    params: wsId({}),
    response: z.array(importDatasetInfo),
  }),
  template: endpoint({
    id: 'imports.template',
    method: 'GET',
    path: '/workspaces/{workspaceId}/imports/datasets/{dataset}/template',
    summary: 'Download an empty template (header row) for a dataset as CSV or XLSX.',
    tags: ['Imports'],
    auth: 'workspace',
    permission: 'imports.create',
    params: wsId({ dataset: z.enum(IMPORT_DATASETS) }),
    query: z.object({ format: z.enum(['csv', 'xlsx']).default('csv') }),
    response: z.any(),
  }),
  mappings: endpoint({
    id: 'imports.mappings',
    method: 'GET',
    path: '/workspaces/{workspaceId}/imports/datasets/{dataset}/mappings',
    summary: 'Saved column mappings for a dataset (own and shared).',
    tags: ['Imports'],
    auth: 'workspace',
    permission: 'imports.create',
    params: wsId({ dataset: z.enum(IMPORT_DATASETS) }),
    response: z.array(z.object({ id: uuid, name: z.string(), mapping: z.record(z.string(), z.string().nullable()), shared: z.boolean(), own: z.boolean(), rowVersion: z.number().int() })),
  }),
  saveMapping: endpoint({
    id: 'imports.saveMapping',
    method: 'POST',
    path: '/workspaces/{workspaceId}/imports/datasets/{dataset}/mappings',
    summary: 'Save a column mapping for later imports of this dataset.',
    tags: ['Imports'],
    auth: 'workspace',
    permission: 'imports.create',
    idempotent: true,
    params: wsId({ dataset: z.enum(IMPORT_DATASETS) }),
    body: z.object({ name: shortName, mapping: z.record(z.string().max(60), z.string().max(200).nullable()), shared: z.boolean().default(false) }),
    response: okResponse,
    successStatus: 201,
  }),
  initiateUpload: endpoint({
    id: 'imports.initiateUpload',
    method: 'POST',
    path: '/workspaces/{workspaceId}/imports/uploads',
    summary: 'Open a quarantine upload for a CSV/XLSX import file (max 20 MB).',
    tags: ['Imports'],
    auth: 'workspace',
    permission: 'imports.create',
    idempotent: true,
    params: wsId({}),
    body: z.object({ filename: z.string().trim().min(1).max(255), byteSize: z.number().int().positive(), mimeType: z.string().max(120).optional() }),
    response: z.object({ uploadId: uuid, partSize: z.number().int(), partCount: z.number().int(), parts: z.array(partUrl), expiresAt: isoDateTime }),
    successStatus: 201,
  }),
  create: endpoint({
    id: 'imports.create',
    method: 'POST',
    path: '/workspaces/{workspaceId}/imports',
    summary: 'Finish the upload, verify and scan the file, and queue parsing into staging. No domain data changes.',
    tags: ['Imports'],
    auth: 'workspace',
    permission: 'imports.create',
    idempotent: true,
    params: wsId({}),
    body: z.object({
      uploadId: uuid,
      parts: z.array(z.object({ partNumber: z.number().int().min(1).max(100), etag: z.string().max(200) })).min(1).max(100),
      dataset: z.enum(IMPORT_DATASETS),
    }),
    response: importJobDetail,
    successStatus: 201,
  }),
  list: endpoint({
    id: 'imports.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/imports',
    summary: 'Import jobs (own; all for members who can commit imports).',
    tags: ['Imports'],
    auth: 'workspace',
    permission: 'imports.create',
    params: wsId({}),
    query: pageQuery.extend({ state: csv(z.enum(IMPORT_STATES)).optional(), dataset: z.enum(IMPORT_DATASETS).optional() }),
    response: page(importJobSummary),
  }),
  get: endpoint({
    id: 'imports.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/imports/{importId}',
    summary: 'Import job with mapping, immutable validation report, progress and result.',
    tags: ['Imports'],
    auth: 'workspace',
    permission: 'imports.create',
    params: wsId({ importId: uuid }),
    response: importJobDetail,
  }),
  rows: endpoint({
    id: 'imports.rows',
    method: 'GET',
    path: '/workspaces/{workspaceId}/imports/{importId}/rows',
    summary: 'Staged rows with their validation outcome (preview shows the first 100).',
    tags: ['Imports'],
    auth: 'workspace',
    permission: 'imports.create',
    params: wsId({ importId: uuid }),
    query: pageQuery.extend({ status: csv(z.enum(['pending', 'valid', 'warning', 'error', 'skipped'])).optional() }),
    response: page(importRowItem),
  }),
  validate: endpoint({
    id: 'imports.validate',
    method: 'POST',
    path: '/workspaces/{workspaceId}/imports/{importId}/validate',
    summary: 'Save the mapping and options and queue validation (syntax, references, permissions, duplicates).',
    tags: ['Imports'],
    auth: 'workspace',
    permission: 'imports.create',
    idempotent: true,
    ifMatch: true,
    params: wsId({ importId: uuid }),
    body: z.object({ mapping: z.record(z.string().max(60), z.string().max(200).nullable()), options: importOptions }),
    response: importJobDetail,
    successStatus: 202,
  }),
  commit: endpoint({
    id: 'imports.commit',
    method: 'POST',
    path: '/workspaces/{workspaceId}/imports/{importId}/commit',
    summary: 'Confirm Import: atomic application of the validated file (zero blocking errors, warnings acknowledged).',
    tags: ['Imports'],
    auth: 'workspace',
    permission: 'imports.commit',
    idempotent: true,
    ifMatch: true,
    params: wsId({ importId: uuid }),
    body: z.object({ validationToken: z.string().max(100), warningsAccepted: z.boolean().default(false) }),
    response: importJobDetail,
    successStatus: 202,
  }),
  reparse: endpoint({
    id: 'imports.reparse',
    method: 'POST',
    path: '/workspaces/{workspaceId}/imports/{importId}/reparse',
    summary: 'Parse the CSV file again with an explicitly chosen delimiter (comma or semicolon).',
    tags: ['Imports'],
    auth: 'workspace',
    permission: 'imports.create',
    idempotent: true,
    ifMatch: true,
    params: wsId({ importId: uuid }),
    body: z.object({ delimiter: z.enum([',', ';']) }),
    response: importJobDetail,
    successStatus: 202,
  }),
  cancel: endpoint({
    id: 'imports.cancel',
    method: 'POST',
    path: '/workspaces/{workspaceId}/imports/{importId}/cancel',
    summary: 'Cancel an import that has not been committed (staging is discarded).',
    tags: ['Imports'],
    auth: 'workspace',
    permission: 'imports.create',
    idempotent: true,
    ifMatch: true,
    params: wsId({ importId: uuid }),
    body: z.object({ reason: z.string().trim().max(LIMITS.reasonMax).optional() }),
    response: importJobDetail,
  }),
  errorReport: endpoint({
    id: 'imports.errorReport',
    method: 'GET',
    path: '/workspaces/{workspaceId}/imports/{importId}/error-report',
    summary: 'Full error and warning report as CSV (values neutralised against spreadsheet formulas).',
    tags: ['Imports'],
    auth: 'workspace',
    permission: 'imports.create',
    params: wsId({ importId: uuid }),
    response: z.any(),
  }),
  undoPreview: endpoint({
    id: 'imports.undoPreview',
    method: 'POST',
    path: '/workspaces/{workspaceId}/imports/{importId}/undo-preview',
    summary: 'Which records created by this import can still be removed, and which have obstacles.',
    tags: ['Imports'],
    auth: 'workspace',
    permission: 'imports.commit',
    params: wsId({ importId: uuid }),
    body: z.object({ reason: z.string().trim().max(LIMITS.reasonMax).optional() }),
    response: z.object({
      token: z.string(),
      expiresAt: isoDateTime,
      removable: z.array(z.object({ entityId: uuid, title: z.string() })),
      obstacles: z.array(z.object({ entityId: uuid, title: z.string(), reason: z.string() })),
      notReverted: z.number().int(),
    }),
  }),
  undo: endpoint({
    id: 'imports.undo',
    method: 'POST',
    path: '/workspaces/{workspaceId}/imports/{importId}/undo',
    summary: 'Remove the previewed, still untouched records created by this import in one transaction.',
    tags: ['Imports'],
    auth: 'workspace',
    permission: 'imports.commit',
    idempotent: true,
    ifMatch: true,
    params: wsId({ importId: uuid }),
    body: z.object({ previewToken: z.string().max(100) }),
    response: importJobDetail,
  }),
};

// ——— Export Center (S54, section 22.2) ———

export const exportColumnInfo = z.object({
  key: z.string(),
  label: z.string(),
  type: z.string(),
  default: z.boolean(),
  /** Column needs a sensitive permission. */
  sensitive: z.boolean(),
  /** The member currently holds the column's permission. */
  available: z.boolean(),
});

export const exportDatasetInfo = z.object({
  key: z.string(),
  label: z.string(),
  classification: z.enum(['normal', 'private', 'finance', 'ofm']),
  columns: z.array(exportColumnInfo),
  filters: z.array(z.object({ key: z.string(), label: z.string(), type: z.enum(['text', 'enum', 'date', 'reference']), enumValues: z.array(z.string()).nullable(), lookup: z.string().nullable() })),
});
export type ExportDatasetInfo = z.infer<typeof exportDatasetInfo>;

export const exportJobItem = z.object({
  id: uuid,
  dataset: z.string(),
  datasetLabel: z.string(),
  format: z.enum(EXPORT_FORMATS),
  fields: z.array(z.string()),
  filters: z.record(z.string(), z.unknown()),
  classification: z.enum(['normal', 'private', 'finance', 'ofm']),
  state: z.enum(EXPORT_STATES),
  requestedBy: memberRef,
  own: z.boolean(),
  sourceBoundAt: isoDateTime,
  fileName: z.string().nullable(),
  byteSize: z.number().int().nullable(),
  progress: z.number().int(),
  errorMessage: z.string().nullable(),
  createdAt: isoDateTime,
  completedAt: isoDateTime.nullable(),
  expiresAt: isoDateTime.nullable(),
  rowVersion: z.number().int(),
  permissions: z.object({ download: z.boolean(), cancel: z.boolean(), delete: z.boolean(), retry: z.boolean() }),
});
export type ExportJobItem = z.infer<typeof exportJobItem>;

const exportRequest = z.object({
  dataset: z.string().max(60),
  format: z.enum(['csv', 'xlsx']),
  fields: z.array(z.string().max(60)).min(1).max(100),
  filters: z.record(z.string().max(60), z.union([z.string().max(200), z.array(z.string().max(200)).max(200), z.boolean(), z.null()])).default({}),
});

export const exportEndpoints = {
  datasets: endpoint({
    id: 'exports.datasets',
    method: 'GET',
    path: '/workspaces/{workspaceId}/exports/datasets',
    summary: 'Datasets the member may export, with column classification and availability.',
    tags: ['Exports'],
    auth: 'workspace',
    permission: 'exports.create',
    params: wsId({}),
    response: z.array(exportDatasetInfo),
  }),
  preview: endpoint({
    id: 'exports.preview',
    method: 'POST',
    path: '/workspaces/{workspaceId}/exports/preview',
    summary: 'Preview Fields: the selected columns and up to 10 permitted sample rows (neutralised).',
    tags: ['Exports'],
    auth: 'workspace',
    permission: 'exports.create',
    params: wsId({}),
    body: exportRequest.omit({ format: true }),
    response: z.object({
      columns: z.array(z.object({ key: z.string(), label: z.string(), type: z.string() })),
      rows: z.array(z.record(z.string(), z.union([z.string(), z.number(), z.boolean(), z.null()]))),
      classification: z.enum(['normal', 'private', 'finance', 'ofm']),
      warnings: z.array(z.string()),
    }),
  }),
  create: endpoint({
    id: 'exports.create',
    method: 'POST',
    path: '/workspaces/{workspaceId}/exports',
    summary: 'Request an export: fields/filters/requester and a source boundary are fixed; generated in the background.',
    tags: ['Exports'],
    auth: 'workspace',
    permission: 'exports.create',
    idempotent: true,
    params: wsId({}),
    body: exportRequest,
    response: exportJobItem,
    successStatus: 202,
  }),
  list: endpoint({
    id: 'exports.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/exports',
    summary: 'Export jobs (own; administrators also see others’ jobs without download rights).',
    tags: ['Exports'],
    auth: 'workspace',
    permission: 'exports.create',
    params: wsId({}),
    query: pageQuery.extend({ state: csv(z.enum(EXPORT_STATES)).optional(), mine: z.preprocess((v) => (v === 'true' ? true : v === 'false' ? false : v), z.boolean()).optional() }),
    response: page(exportJobItem),
  }),
  get: endpoint({
    id: 'exports.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/exports/{exportId}',
    summary: 'Export job detail.',
    tags: ['Exports'],
    auth: 'workspace',
    permission: 'exports.create',
    params: wsId({ exportId: uuid }),
    response: exportJobItem,
  }),
  download: endpoint({
    id: 'exports.download',
    method: 'POST',
    path: '/workspaces/{workspaceId}/exports/{exportId}/download',
    summary: 'Re-check access and issue a short-lived (5 min) download link bound to the requester.',
    tags: ['Exports'],
    auth: 'workspace',
    permission: 'exports.download',
    rateLimit: 'download',
    params: wsId({ exportId: uuid }),
    response: z.object({ url: z.string(), expiresAt: isoDateTime }),
  }),
  file: endpoint({
    id: 'exports.file',
    method: 'GET',
    path: '/workspaces/{workspaceId}/exports/{exportId}/file',
    summary: 'Authorised file stream (permission re-checked at download time).',
    tags: ['Exports'],
    auth: 'workspace',
    permission: 'exports.download',
    rateLimit: 'download',
    params: wsId({ exportId: uuid }),
    query: z.object({ token: z.string().max(400) }),
    response: z.any(),
  }),
  cancel: endpoint({
    id: 'exports.cancel',
    method: 'POST',
    path: '/workspaces/{workspaceId}/exports/{exportId}/cancel',
    summary: 'Cancel a queued or running export; any partial file is removed.',
    tags: ['Exports'],
    auth: 'workspace',
    permission: 'exports.create',
    idempotent: true,
    ifMatch: true,
    params: wsId({ exportId: uuid }),
    response: exportJobItem,
  }),
  remove: endpoint({
    id: 'exports.remove',
    method: 'POST',
    path: '/workspaces/{workspaceId}/exports/{exportId}/delete',
    summary: 'Delete File: remove a generated export file before it expires.',
    tags: ['Exports'],
    auth: 'workspace',
    permission: 'exports.create',
    idempotent: true,
    ifMatch: true,
    params: wsId({ exportId: uuid }),
    response: exportJobItem,
  }),
  retry: endpoint({
    id: 'exports.retry',
    method: 'POST',
    path: '/workspaces/{workspaceId}/exports/{exportId}/retry',
    summary: 'Retry a failed export with the same fields, filters and source boundary.',
    tags: ['Exports'],
    auth: 'workspace',
    permission: 'exports.create',
    idempotent: true,
    ifMatch: true,
    params: wsId({ exportId: uuid }),
    response: exportJobItem,
    successStatus: 202,
  }),
};
