import { z } from 'zod';
import { CONTENT_FORMATS, CONTENT_SLOTS, CONTENT_STAGES, LIMITS, REVIEW_STATUSES, REVIEW_STEP_KINDS, REVIEW_TARGET_TYPES } from '@castlane/domain';
import { endpoint } from './core';
import { boolQuery, csv, isoDate, isoDateTime, memberRef, page, pageQuery, reason, tag, uuid, wsId } from './common';
import { exportJobItem } from './platform-data';

/**
 * Content production, versions and reviews (S22–S26, §10). Stages change only through commands
 * (transition / submit / review decisions); versions are immutable after submission.
 */

const contentStage = z.enum(CONTENT_STAGES);
const contentFormat = z.enum(CONTENT_FORMATS);
const contentSlot = z.enum(CONTENT_SLOTS);

export const contentBrief = z.object({
  summary: z.string().max(2000).nullable().optional(),
  objective: z.string().max(2000).nullable().optional(),
  audience: z.string().max(2000).nullable().optional(),
  hook: z.string().max(2000).nullable().optional(),
  script: z.string().max(LIMITS.noteMax).nullable().optional(),
  captionDraft: z.string().max(LIMITS.noteMax).nullable().optional(),
  cta: z.string().max(500).nullable().optional(),
  notes: z.string().max(LIMITS.noteMax).nullable().optional(),
});
export type ContentBriefInput = z.infer<typeof contentBrief>;

const briefView = z.object({
  summary: z.string().nullable(),
  objective: z.string().nullable(),
  audience: z.string().nullable(),
  hook: z.string().nullable(),
  script: z.string().nullable(),
  captionDraft: z.string().nullable(),
  cta: z.string().nullable(),
  notes: z.string().nullable(),
});

const versionPointer = z.object({ id: uuid, versionNo: z.number().int() });
const flagView = z.object({ at: isoDateTime, reason: z.string().nullable() });
const missingItem = z.object({ field: z.string(), code: z.string(), message: z.string() });

export const contentSummary = z.object({
  id: uuid,
  title: z.string(),
  project: z.object({ id: uuid, name: z.string() }),
  format: contentFormat,
  stage: contentStage,
  owner: memberRef.nullable(),
  reviewer: memberRef.nullable(),
  dueAt: isoDateTime.nullable(),
  noDeadline: z.boolean(),
  overdue: z.boolean(),
  language: z.string().nullable(),
  tags: z.array(z.string()),
  account: z.object({ id: uuid, label: z.string().nullable() }).nullable(),
  episodeId: uuid.nullable(),
  blocked: flagView.nullable(),
  paused: flagView.nullable(),
  needsConsistencyReview: z.boolean(),
  /** Latest submitted version ("Latest"). */
  currentVersion: versionPointer.nullable(),
  /** Approved version pinned for placements ("Approved"); never the latest automatically. */
  approvedVersion: versionPointer.extend({ revoked: z.boolean() }).nullable(),
  /** A version newer than the approved one is waiting for review. */
  newerVersionAwaitingReview: z.boolean(),
  publicationCount: z.number().int(),
  openTasks: z.number().int(),
  /** Authorised thumbnail of the main file of the latest/approved version (never restricted media). */
  thumbnailUrl: z.string().nullable(),
  /** Stages the member may move this item to with a manual move (keyboard "Move to"). */
  allowedMoves: z.array(contentStage),
  stageEnteredAt: isoDateTime.nullable(),
  archivedAt: isoDateTime.nullable(),
  createdAt: isoDateTime,
  updatedAt: isoDateTime,
  rowVersion: z.number().int(),
});
export type ContentSummary = z.infer<typeof contentSummary>;

export const contentReviewPolicyView = z.object({
  steps: z.array(z.enum(REVIEW_STEP_KINDS)),
  allowSelfReview: z.boolean(),
  /** Echo as `reviewPolicyVersion` on submit; a changed policy is detected. */
  version: z.string(),
});

export const contentDetail = contentSummary.extend({
  brief: briefView,
  characters: z.array(z.object({ characterId: uuid, name: z.string(), versionId: uuid, versionNo: z.number().int(), state: z.string(), isApproved: z.boolean() })),
  references: z.array(z.object({ id: uuid, title: z.string(), linkId: uuid })),
  hiddenReferenceCount: z.number().int(),
  episode: z.object({ id: uuid, label: z.string().nullable() }).nullable(),
  template: z.object({ templateId: uuid, templateVersionId: uuid, name: z.string(), versionNo: z.number().int() }).nullable(),
  duplicatedFrom: z.object({ id: uuid, title: z.string().nullable() }).nullable(),
  deliverableSlots: z.array(z.object({ slot: contentSlot, required: z.boolean() })),
  draftVersion: versionPointer.nullable(),
  activeReview: z
    .object({ id: uuid, status: z.enum(REVIEW_STATUSES), stepKind: z.enum(REVIEW_STEP_KINDS), roundNo: z.number().int(), reviewer: memberRef.nullable(), versionId: uuid, rowVersion: z.number().int() })
    .nullable(),
  reviewPolicy: contentReviewPolicyView,
  stageHistory: z.array(z.object({ id: uuid, from: contentStage.nullable(), to: contentStage, at: isoDateTime, actor: memberRef.nullable(), reason: z.string().nullable() })),
  flagHistory: z.array(z.object({ id: uuid, flag: z.enum(['paused', 'blocked']), reason: z.string(), startedAt: isoDateTime, endedAt: isoDateTime.nullable(), resolution: z.string().nullable() })),
  /** What is missing for each next manual stage (explains a refused move). */
  nextStages: z.array(z.object({ stage: contentStage, missing: z.array(missingItem) })),
  counts: z.object({ versions: z.number().int(), openTasks: z.number().int(), tasks: z.number().int(), publications: z.number().int(), comments: z.number().int() }),
  projectStatus: z.string(),
  permissions: z.object({
    edit: z.boolean(),
    transition: z.boolean(),
    upload: z.boolean(),
    submit: z.boolean(),
    approve: z.boolean(),
    archive: z.boolean(),
    duplicate: z.boolean(),
    applyTemplate: z.boolean(),
    flag: z.boolean(),
    comment: z.boolean(),
    exportPackage: z.boolean(),
    download: z.boolean(),
  }),
});
export type ContentDetail = z.infer<typeof contentDetail>;

const contentFields = {
  title: z.string().trim().min(LIMITS.taskTitleMin).max(LIMITS.taskTitleMax),
  format: contentFormat,
  ownerMembershipId: uuid.nullable().optional(),
  reviewerMembershipId: uuid.nullable().optional(),
  brief: contentBrief.optional(),
  language: z.string().trim().max(20).nullable().optional(),
  dueAt: isoDateTime.nullable().optional(),
  noDeadline: z.boolean().optional(),
  tags: z.array(tag).max(LIMITS.tagsPerObject).optional(),
  accountId: uuid.nullable().optional(),
  episodeId: uuid.nullable().optional(),
  characterVersionIds: z.array(uuid).max(20).optional(),
  referenceIds: z.array(uuid).max(50).optional(),
};

export const contentSort = z.enum(['updatedAt', 'createdAt', 'dueAt', 'title', 'stage']);

const listFilters = {
  q: z.string().trim().max(120).optional(),
  projectId: uuid.optional(),
  accountId: uuid.optional(),
  episodeId: uuid.optional(),
  characterId: uuid.optional(),
  format: csv(contentFormat).optional(),
  stage: csv(contentStage).optional(),
  ownerMembershipId: uuid.optional(),
  reviewerMembershipId: uuid.optional(),
  /** Owner or reviewer is me. */
  mine: boolQuery.optional(),
  dueFrom: isoDateTime.optional(),
  dueTo: isoDateTime.optional(),
  overdue: boolQuery.optional(),
  noDeadline: boolQuery.optional(),
  blocked: boolQuery.optional(),
  tag: z.string().max(40).optional(),
  includeArchived: boolQuery.optional(),
};

export const contentTemplatePlanTask = z.object({
  key: z.string(),
  title: z.string(),
  assignee: memberRef.nullable(),
  reviewer: memberRef.nullable(),
  startDate: isoDate,
  dueDate: isoDate,
  dependsOn: z.array(z.string()),
});

export const contentTemplateDiffTask = z.object({ taskId: uuid, title: z.string(), status: z.string(), templateName: z.string().nullable() });

export const contentTemplatePreviewView = z.object({
  template: z.object({ templateId: uuid, name: z.string(), versionNo: z.number().int(), templateVersionId: uuid }),
  alreadyApplied: z.boolean(),
  /** Tasks the template would add (none when this template version and start date were applied before). */
  add: z.array(contentTemplatePlanTask),
  /** Completed or started tasks of earlier applications: always kept unchanged. */
  keep: z.array(contentTemplateDiffTask),
  /** Not-started tasks of earlier applications: the member may keep or cancel each one. */
  cancelable: z.array(contentTemplateDiffTask),
  unassignedCount: z.number().int(),
  deliverableSlots: z.array(z.object({ slot: contentSlot, required: z.boolean() })),
  checklist: z.array(z.object({ label: z.string(), mandatory: z.boolean() })),
  previewToken: z.string(),
});
export type ContentTemplatePreview = z.infer<typeof contentTemplatePreviewView>;

const bulkAction = z.enum(['assign_owner', 'assign_reviewer', 'add_tag', 'remove_tag', 'move_stage']);

export const contentEndpoints = {
  list: endpoint({
    id: 'content.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/content',
    summary: 'Content items in the actor’s scope (filters, cursor pagination). Archived hidden by default.',
    tags: ['Content'],
    auth: 'workspace',
    permission: 'content.read',
    params: wsId({}),
    query: pageQuery.extend({ ...listFilters, sort: contentSort.default('updatedAt'), direction: z.enum(['asc', 'desc']).default('desc') }),
    response: page(contentSummary),
  }),
  board: endpoint({
    id: 'content.board',
    method: 'GET',
    path: '/workspaces/{workspaceId}/content/board',
    summary: 'Pipeline board: work-in-progress counts per canonical stage and the first cards of each column.',
    tags: ['Content'],
    auth: 'workspace',
    permission: 'content.read',
    params: wsId({}),
    query: z.object({ ...listFilters, perStage: z.coerce.number().int().min(1).max(200).default(50) }),
    response: z.object({
      columns: z.array(z.object({ stage: contentStage, count: z.number().int(), wipLimit: z.number().int().nullable(), items: z.array(contentSummary) })),
      canEditWipLimits: z.boolean(),
    }),
  }),
  setWipLimits: endpoint({
    id: 'content.setWipLimits',
    method: 'PUT',
    path: '/workspaces/{workspaceId}/content/wip-limits',
    summary: 'Work-in-progress limits per stage (a warning, never a hard stop).',
    tags: ['Content'],
    auth: 'workspace',
    permission: 'workspace.update',
    idempotent: true,
    params: wsId({}),
    body: z.object({ limits: z.partialRecord(contentStage, z.number().int().min(1).max(999).nullable()) }),
    response: z.object({ limits: z.record(z.string(), z.number().int()) }),
  }),
  get: endpoint({
    id: 'content.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/content/{contentId}',
    summary: 'Content detail: brief, links, version pointers, active review, stage history and allowed actions.',
    tags: ['Content'],
    auth: 'workspace',
    permission: 'content.read',
    params: wsId({ contentId: uuid }),
    response: contentDetail,
  }),
  create: endpoint({
    id: 'content.create',
    method: 'POST',
    path: '/workspaces/{workspaceId}/content',
    summary: 'Create an Idea draft (Title, Project, Format); optionally apply a content template right away.',
    tags: ['Content'],
    auth: 'workspace',
    permission: 'content.create',
    idempotent: true,
    params: wsId({}),
    body: z.object({
      ...contentFields,
      projectId: uuid,
      applyTemplate: z.object({ templateVersionId: uuid, startDate: isoDate, assignees: z.record(z.string().max(80), uuid).optional() }).optional(),
    }),
    response: contentDetail,
    successStatus: 201,
  }),
  update: endpoint({
    id: 'content.update',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/content/{contentId}',
    summary: 'Edit the brief and links (status changes only through commands; publication facts are never changed).',
    tags: ['Content'],
    auth: 'workspace',
    permission: 'content.edit',
    ifMatch: true,
    params: wsId({ contentId: uuid }),
    body: z.object({ ...contentFields, title: contentFields.title.optional(), format: contentFormat.optional() }),
    response: contentDetail,
  }),
  transition: endpoint({
    id: 'content.transition',
    method: 'POST',
    path: '/workspaces/{workspaceId}/content/{contentId}/transition',
    summary: 'Manual stage change (Idea→Brief→Ready→Production, Changes Requested→Production, Approved→Production as New Revision with reason).',
    tags: ['Content'],
    auth: 'workspace',
    permission: 'content.edit',
    idempotent: true,
    ifMatch: true,
    params: wsId({ contentId: uuid }),
    body: z.object({ targetStage: contentStage, reason: reason.optional() }),
    response: contentDetail.extend({ warnings: z.array(z.string()) }),
  }),
  setFlag: endpoint({
    id: 'content.setFlag',
    method: 'POST',
    path: '/workspaces/{workspaceId}/content/{contentId}/flags',
    summary: 'Set or clear the independent Blocked / Paused flag (reason, actor, start and end are kept).',
    tags: ['Content'],
    auth: 'workspace',
    permission: 'content.edit',
    idempotent: true,
    ifMatch: true,
    params: wsId({ contentId: uuid }),
    body: z.object({ flag: z.enum(['blocked', 'paused']), on: z.boolean(), reason: reason.optional(), resolution: z.string().trim().max(LIMITS.reasonMax).optional() }),
    response: contentDetail,
  }),
  duplicate: endpoint({
    id: 'content.duplicate',
    method: 'POST',
    path: '/workspaces/{workspaceId}/content/{contentId}/duplicate',
    summary: 'Duplicate as New Draft: a new Idea with a link to the source and chosen fields/attachments. No metrics, approvals, payouts or publications are inherited.',
    tags: ['Content'],
    auth: 'workspace',
    permission: 'content.create',
    idempotent: true,
    params: wsId({ contentId: uuid }),
    body: z.object({
      targetProjectId: uuid,
      title: contentFields.title.optional(),
      format: contentFormat.optional(),
      copiedFieldSet: z.array(z.enum(['brief', 'characters', 'references', 'tags', 'language', 'account', 'episode'])).max(10).default(['brief']),
      attachmentAssetVersionIds: z.array(uuid).max(50).optional(),
    }),
    response: contentDetail,
    successStatus: 201,
  }),
  activity: endpoint({
    id: 'content.activity',
    method: 'GET',
    path: '/workspaces/{workspaceId}/content/{contentId}/activity',
    summary: 'Meaningful history: created, assigned, stage changed, version submitted, review decided, archived.',
    tags: ['Content'],
    auth: 'workspace',
    permission: 'content.read',
    params: wsId({ contentId: uuid }),
    query: pageQuery,
    response: page(z.object({ id: uuid, action: z.string(), actorName: z.string().nullable(), occurredAt: isoDateTime, reason: z.string().nullable(), metadata: z.record(z.string(), z.unknown()).nullable(), changes: z.array(z.object({ field: z.string(), from: z.unknown(), to: z.unknown() })) })),
  }),
  templatePreview: endpoint({
    id: 'content.templatePreview',
    method: 'POST',
    path: '/workspaces/{workspaceId}/content/{contentId}/template-preview',
    summary: 'Preview Generated Tasks: names, assignees, dates and the diff against tasks of earlier applications. Changes nothing.',
    tags: ['Content'],
    auth: 'workspace',
    permission: 'tasks.create',
    params: wsId({ contentId: uuid }),
    body: z.object({ templateVersionId: uuid, startDate: isoDate, assignees: z.record(z.string().max(80), uuid).optional() }),
    response: contentTemplatePreviewView,
  }),
  applyTemplate: endpoint({
    id: 'content.applyTemplate',
    method: 'POST',
    path: '/workspaces/{workspaceId}/content/{contentId}/apply-template',
    summary: 'Create the template’s task graph exactly once per application key; never overwrites completed tasks.',
    tags: ['Content'],
    auth: 'workspace',
    permission: 'tasks.create',
    idempotent: true,
    ifMatch: true,
    params: wsId({ contentId: uuid }),
    body: z.object({ templateVersionId: uuid, previewToken: z.string().max(200), startDate: isoDate, assignees: z.record(z.string().max(80), uuid).optional(), cancelTaskIds: z.array(uuid).max(200).optional() }),
    response: z.object({ applicationId: uuid, created: z.boolean(), taskIds: z.array(uuid), cancelledTaskIds: z.array(uuid), coordinationTaskId: uuid.nullable(), content: contentDetail }),
  }),
  bulkPreview: endpoint({
    id: 'content.bulkPreview',
    method: 'POST',
    path: '/workspaces/{workspaceId}/content/bulk-preview',
    summary: 'Dry run of a bulk Assign / Tag / Move: per-item outcome and a 10-minute preview token.',
    tags: ['Content'],
    auth: 'workspace',
    permission: 'content.edit',
    params: wsId({}),
    body: z.object({ action: bulkAction, ids: z.array(uuid).min(1).max(200), value: z.string().max(80) }),
    response: z.object({
      token: z.string(),
      expiresAt: isoDateTime,
      items: z.array(z.object({ id: uuid, title: z.string(), outcome: z.enum(['apply', 'skip', 'denied', 'conflict']), reason: z.string().nullable() })),
      applyCount: z.number().int(),
      missingCount: z.number().int(),
    }),
  }),
  bulkApply: endpoint({
    id: 'content.bulkApply',
    method: 'POST',
    path: '/workspaces/{workspaceId}/content/bulk-apply',
    summary: 'Apply a previewed bulk action per item (targets changed since the preview are reported, not changed).',
    tags: ['Content'],
    auth: 'workspace',
    permission: 'content.edit',
    idempotent: true,
    params: wsId({}),
    body: z.object({ token: z.string().max(100) }),
    response: z.object({ done: z.array(uuid), failed: z.array(z.object({ id: uuid, message: z.string() })), warnings: z.array(z.string()) }),
  }),
  requestPackage: endpoint({
    id: 'content.requestPackage',
    method: 'POST',
    path: '/workspaces/{workspaceId}/content/{contentId}/package',
    summary: 'Export the approved content package (ZIP with manifest.json, files, subtitles and metadata) in the background.',
    tags: ['Content'],
    auth: 'workspace',
    permission: 'exports.create',
    idempotent: true,
    params: wsId({ contentId: uuid }),
    body: z.object({ versionId: uuid.optional() }),
    response: exportJobItem,
    successStatus: 202,
  }),
  requestEpisodePackage: endpoint({
    id: 'content.requestEpisodePackage',
    method: 'POST',
    path: '/workspaces/{workspaceId}/episodes/{episodeId}/content-package',
    summary: 'Export the approved content of an episode as one ZIP package (manifest.json, files, metadata).',
    tags: ['Content'],
    auth: 'workspace',
    permission: 'exports.create',
    idempotent: true,
    params: wsId({ episodeId: uuid }),
    body: z.object({}),
    response: exportJobItem,
    successStatus: 202,
  }),
  packages: endpoint({
    id: 'content.packages',
    method: 'GET',
    path: '/workspaces/{workspaceId}/content/{contentId}/packages',
    summary: 'Your package exports of this content (download through the Export Center endpoints).',
    tags: ['Content'],
    auth: 'workspace',
    permission: 'exports.create',
    params: wsId({ contentId: uuid }),
    response: z.array(exportJobItem),
  }),
  episodeContent: endpoint({
    id: 'content.episodeContent',
    method: 'GET',
    path: '/workspaces/{workspaceId}/episodes/{episodeId}/content',
    summary: 'Content of one episode (linked items and the episode’s main content item) within the actor’s scope.',
    tags: ['Content'],
    auth: 'workspace',
    permission: 'content.read',
    params: wsId({ episodeId: uuid }),
    response: z.object({ items: z.array(contentSummary), hiddenCount: z.number().int(), approvedCount: z.number().int() }),
  }),
};

// ——— Versions ———

export const contentVersionFileView = z.object({
  id: uuid,
  slot: contentSlot,
  position: z.number().int(),
  assetId: uuid,
  assetVersionId: uuid,
  fileName: z.string(),
  mime: z.string().nullable(),
  kind: z.enum(['image', 'video', 'audio', 'other']),
  status: z.string(),
  byteSize: z.number().nullable(),
  width: z.number().int().nullable(),
  height: z.number().int().nullable(),
  durationMs: z.number().int().nullable(),
  checksumSha256: z.string().nullable(),
  rejectionReason: z.string().nullable(),
  restricted: z.boolean(),
  canReveal: z.boolean(),
  previewAvailable: z.boolean(),
  /** Authorised derivative URL (null for restricted media until revealed or when no preview exists). */
  thumbnailUrl: z.string().nullable(),
  canDownload: z.boolean(),
});
export type ContentVersionFile = z.infer<typeof contentVersionFileView>;

export const contentVersionSummaryView = z.object({
  id: uuid,
  contentId: uuid,
  versionNo: z.number().int(),
  note: z.string().nullable(),
  fixesClaimed: z.string().nullable(),
  state: z.enum(['draft', 'submitted', 'approved', 'changes_requested', 'revoked', 'superseded']),
  submittedAt: isoDateTime.nullable(),
  submittedBy: memberRef.nullable(),
  approvedAt: isoDateTime.nullable(),
  approvalRevokedAt: isoDateTime.nullable(),
  approvalRevokedReason: z.string().nullable(),
  isLatest: z.boolean(),
  isApproved: z.boolean(),
  fileCount: z.number().int(),
  thumbnailUrl: z.string().nullable(),
  createdAt: isoDateTime,
  createdBy: memberRef.nullable(),
  rowVersion: z.number().int(),
});
export type ContentVersionSummary = z.infer<typeof contentVersionSummaryView>;

export const contentVersionDetailView = contentVersionSummaryView.extend({
  files: z.array(contentVersionFileView),
  checklist: z.array(z.object({ label: z.string(), done: z.boolean(), mandatory: z.boolean(), fromTemplate: z.boolean() })),
  briefSnapshot: briefView.nullable(),
  characterVersions: z.array(z.object({ versionId: uuid, characterId: uuid.nullable(), name: z.string().nullable(), versionNo: z.number().int().nullable() })),
  deliverableSlots: z.array(z.object({ slot: contentSlot, required: z.boolean(), filled: z.boolean() })),
  /** What still blocks Submit for Review (draft versions only). */
  submitMissing: z.array(missingItem),
  reviews: z.array(z.object({ id: uuid, roundNo: z.number().int(), stepKind: z.enum(REVIEW_STEP_KINDS), status: z.enum(REVIEW_STATUSES), decidedAt: isoDateTime.nullable(), decision: z.object({ kind: z.string(), summary: z.string().nullable(), by: memberRef.nullable(), at: isoDateTime }).nullable() })),
  openBlocking: z.number().int(),
  permissions: z.object({ edit: z.boolean(), upload: z.boolean(), submit: z.boolean(), comment: z.boolean() }),
});
export type ContentVersionDetail = z.infer<typeof contentVersionDetailView>;

const versionParams = wsId({ contentId: uuid, versionId: uuid });

export const contentVersionEndpoints = {
  list: endpoint({
    id: 'content.versions.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/content/{contentId}/versions',
    summary: 'All versions of a content item, newest first (Latest and Approved are separate pointers).',
    tags: ['Content Versions'],
    auth: 'workspace',
    permission: 'content.read',
    params: wsId({ contentId: uuid }),
    response: z.array(contentVersionSummaryView),
  }),
  resolve: endpoint({
    id: 'content.versions.resolve',
    method: 'GET',
    path: '/workspaces/{workspaceId}/content-versions/{versionId}',
    summary: 'Resolve a version link (notifications, audit) to its content item and latest review.',
    tags: ['Content Versions'],
    auth: 'workspace',
    permission: 'content.read',
    params: wsId({ versionId: uuid }),
    response: z.object({ contentId: uuid, versionNo: z.number().int(), reviewId: uuid.nullable() }),
  }),
  get: endpoint({
    id: 'content.versions.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/content/{contentId}/versions/{versionId}',
    summary: 'One version: files per deliverable slot, checklist, frozen brief snapshot, reviews and what blocks submission.',
    tags: ['Content Versions'],
    auth: 'workspace',
    permission: 'content.read',
    params: versionParams,
    response: contentVersionDetailView,
  }),
  create: endpoint({
    id: 'content.versions.create',
    method: 'POST',
    path: '/workspaces/{workspaceId}/content/{contentId}/versions',
    summary: 'Start a new draft version (monotonic number); optionally reuse unchanged files of an earlier version.',
    tags: ['Content Versions'],
    auth: 'workspace',
    permission: 'content.upload',
    idempotent: true,
    params: wsId({ contentId: uuid }),
    body: z.object({ note: z.string().trim().max(2000).optional(), fixesClaimed: z.string().trim().max(LIMITS.noteMax).optional(), copyFilesFromVersionId: uuid.optional() }),
    response: contentVersionDetailView,
    successStatus: 201,
  }),
  update: endpoint({
    id: 'content.versions.update',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/content/{contentId}/versions/{versionId}',
    summary: 'Edit a draft version’s note, claimed fixes and checklist (submitted versions are immutable).',
    tags: ['Content Versions'],
    auth: 'workspace',
    permission: 'content.upload',
    ifMatch: true,
    params: versionParams,
    body: z.object({
      note: z.string().trim().max(2000).nullable().optional(),
      fixesClaimed: z.string().trim().max(LIMITS.noteMax).nullable().optional(),
      checklist: z.array(z.object({ label: z.string().trim().min(2).max(200), done: z.boolean(), mandatory: z.boolean() })).max(50).optional(),
    }),
    response: contentVersionDetailView,
  }),
  attachFile: endpoint({
    id: 'content.versions.attachFile',
    method: 'POST',
    path: '/workspaces/{workspaceId}/content/{contentId}/versions/{versionId}/files',
    summary: 'Put an uploaded (or existing Library) file version into a deliverable slot of a draft version.',
    tags: ['Content Versions'],
    auth: 'workspace',
    permission: 'content.upload',
    idempotent: true,
    params: versionParams,
    body: z.object({ slot: contentSlot, assetVersionId: uuid, replaceFileId: uuid.optional() }),
    response: contentVersionDetailView,
  }),
  removeFile: endpoint({
    id: 'content.versions.removeFile',
    method: 'POST',
    path: '/workspaces/{workspaceId}/content/{contentId}/versions/{versionId}/files/{fileId}/remove',
    summary: 'Remove a file from a draft version (the Library file itself stays).',
    tags: ['Content Versions'],
    auth: 'workspace',
    permission: 'content.upload',
    idempotent: true,
    params: wsId({ contentId: uuid, versionId: uuid, fileId: uuid }),
    body: z.object({}),
    response: contentVersionDetailView,
  }),
  submit: endpoint({
    id: 'content.submit',
    method: 'POST',
    path: '/workspaces/{workspaceId}/content/{contentId}/submit',
    summary: 'Submit for Review: freezes the version (brief snapshot, files, character versions) and opens a review round.',
    tags: ['Content Versions'],
    auth: 'workspace',
    permission: 'content.submit',
    idempotent: true,
    ifMatch: true,
    params: wsId({ contentId: uuid }),
    body: z.object({ versionId: uuid, reviewPolicyVersion: z.string().max(40).optional(), reviewerMembershipId: uuid.optional() }),
    response: contentDetail,
  }),
};

// ——— Reviews ———

export const reviewQueueRow = z.object({
  id: uuid,
  targetType: z.enum(REVIEW_TARGET_TYPES),
  subjectId: uuid,
  title: z.string(),
  href: z.string(),
  project: z.object({ id: uuid, name: z.string() }),
  format: contentFormat.nullable(),
  versionId: uuid,
  versionNo: z.number().int(),
  roundNo: z.number().int(),
  stepKind: z.enum(REVIEW_STEP_KINDS),
  status: z.enum(REVIEW_STATUSES),
  author: memberRef.nullable(),
  reviewer: memberRef.nullable(),
  submittedAt: isoDateTime,
  dueAt: isoDateTime.nullable(),
  overdue: z.boolean(),
  waitingHours: z.number().int(),
  openBlocking: z.number().int(),
  thumbnailUrl: z.string().nullable(),
  decidedAt: isoDateTime.nullable(),
  rowVersion: z.number().int(),
  permissions: z.object({ decide: z.boolean(), assign: z.boolean() }),
});
export type ReviewQueueRow = z.infer<typeof reviewQueueRow>;

export const reviewStudioDetail = z.object({
  id: uuid,
  status: z.enum(REVIEW_STATUSES),
  stepKind: z.enum(REVIEW_STEP_KINDS),
  stepOrder: z.number().int(),
  roundNo: z.number().int(),
  steps: z.array(z.enum(REVIEW_STEP_KINDS)),
  reviewer: memberRef.nullable(),
  author: memberRef.nullable(),
  submittedAt: isoDateTime,
  dueAt: isoDateTime.nullable(),
  overdue: z.boolean(),
  decidedAt: isoDateTime.nullable(),
  selfReviewException: z.boolean(),
  policy: z.object({ allowSelfReview: z.boolean(), steps: z.array(z.enum(REVIEW_STEP_KINDS)) }),
  decisions: z.array(z.object({ id: uuid, decision: z.enum(['approved', 'changes_requested', 'revoked']), summary: z.string().nullable(), by: memberRef.nullable(), at: isoDateTime, versionId: uuid })),
  content: contentSummary.extend({ brief: briefView }),
  /** The exact version under review. */
  version: contentVersionDetailView,
  /** Every version for the version switcher / compare (newest first). */
  versions: z.array(contentVersionSummaryView),
  /** The version this review decides; a newer submitted version supersedes the review. */
  isCurrentTarget: z.boolean(),
  openBlocking: z.number().int(),
  /** Why Approve is not possible now (blockers, self-review, stale target). */
  approveBlockers: z.array(missingItem),
  rowVersion: z.number().int(),
  permissions: z.object({
    approve: z.boolean(),
    requestChanges: z.boolean(),
    revoke: z.boolean(),
    assign: z.boolean(),
    comment: z.boolean(),
    selfReviewException: z.boolean(),
    download: z.boolean(),
  }),
});
export type ReviewStudioDetail = z.infer<typeof reviewStudioDetail>;

const reviewParams = wsId({ reviewId: uuid });

export const reviewEndpoints = {
  list: endpoint({
    id: 'reviews.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/reviews',
    summary: 'Review Queue: content versions and character profiles waiting for a decision (Assigned to Me / All Permitted).',
    tags: ['Reviews'],
    auth: 'workspace',
    params: wsId({}),
    query: pageQuery.extend({
      scope: z.enum(['assigned', 'all']).default('assigned'),
      status: csv(z.enum(REVIEW_STATUSES)).optional(),
      targetType: z.enum(REVIEW_TARGET_TYPES).optional(),
      projectId: uuid.optional(),
      format: csv(contentFormat).optional(),
      reviewerMembershipId: uuid.optional(),
      waitingHoursMin: z.coerce.number().int().min(0).max(24 * 365).optional(),
      overdue: boolQuery.optional(),
      q: z.string().trim().max(120).optional(),
      sort: z.enum(['waiting', 'due', 'decided']).default('waiting'),
    }),
    response: page(reviewQueueRow),
  }),
  get: endpoint({
    id: 'reviews.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/reviews/{reviewId}',
    summary: 'Review Studio: the exact version under review, all versions, decisions and allowed actions.',
    tags: ['Reviews'],
    auth: 'workspace',
    permission: 'content.read',
    params: reviewParams,
    response: reviewStudioDetail,
  }),
  approve: endpoint({
    id: 'reviews.approve',
    method: 'POST',
    path: '/workspaces/{workspaceId}/reviews/{reviewId}/approve',
    summary: 'Approve Version: only the exact submitted version, with blockers resolved and no self-approval (unless an audited exception).',
    tags: ['Reviews'],
    auth: 'workspace',
    permission: 'content.approve',
    idempotent: true,
    ifMatch: true,
    params: reviewParams,
    body: z.object({ versionId: uuid, decisionNote: z.string().trim().max(LIMITS.reasonMax).optional(), selfReviewException: z.object({ reason }).optional() }),
    response: reviewStudioDetail,
  }),
  requestChanges: endpoint({
    id: 'reviews.requestChanges',
    method: 'POST',
    path: '/workspaces/{workspaceId}/reviews/{reviewId}/request-changes',
    summary: 'Request Changes: summary plus at least one concrete comment on the version or an explanation.',
    tags: ['Reviews'],
    auth: 'workspace',
    permission: 'content.approve',
    idempotent: true,
    ifMatch: true,
    params: reviewParams,
    body: z.object({ versionId: uuid, summary: reason, explanation: z.string().trim().max(LIMITS.noteMax).optional() }),
    response: reviewStudioDetail,
  }),
  revoke: endpoint({
    id: 'reviews.revoke',
    method: 'POST',
    path: '/workspaces/{workspaceId}/reviews/{reviewId}/revoke',
    summary: 'Revoke Approval: blocks new placements of the version; published history stays, flagged and with a check task.',
    tags: ['Reviews'],
    auth: 'workspace',
    permission: 'content.approve',
    idempotent: true,
    ifMatch: true,
    params: reviewParams,
    body: z.object({ reason }),
    response: reviewStudioDetail,
  }),
  assign: endpoint({
    id: 'reviews.assign',
    method: 'POST',
    path: '/workspaces/{workspaceId}/reviews/{reviewId}/assign',
    summary: 'Assign Reviewer: an eligible member (approval permission in scope; never the author without policy).',
    tags: ['Reviews'],
    auth: 'workspace',
    permission: 'content.approve',
    idempotent: true,
    ifMatch: true,
    params: reviewParams,
    body: z.object({ reviewerMembershipId: uuid }),
    response: reviewStudioDetail,
  }),
};

