import { z } from 'zod';
import { LIMITS, MONTH_DAY_POLICIES, RECURRENCE_CADENCES, RECURRENCE_MODES } from '@castlane/domain';
import { endpoint } from '../core';
import { boolQuery, csv, isoDate, isoDateTime, memberRef, note, okResponse, page, pageQuery, reason, tags, taskTitle, timezone, uuid, wsId } from '../common';
import { assetView } from '../media';
import { dueInput, dueView, linkedRef, taskPriority, taskRef, taskRow, taskStatus } from './common';

const links = {
  accountId: uuid.nullable().optional(),
  contentItemId: uuid.nullable().optional(),
  publicationId: uuid.nullable().optional(),
  shiftId: uuid.nullable().optional(),
  operationId: uuid.nullable().optional(),
  dealId: uuid.nullable().optional(),
  deliverableId: uuid.nullable().optional(),
  articleId: uuid.nullable().optional(),
};

const estimate = z.number().int().min(0).max(100_000);
const checklistSeed = z.array(z.object({ label: z.string().trim().min(1).max(300), mandatory: z.boolean().default(false) })).max(100);

export const taskCreateBody = z.object({
  title: taskTitle,
  projectId: uuid,
  description: note.nullable().optional(),
  /** Initial planning status; work states are reached through transitions. */
  status: z.enum(['draft', 'backlog', 'ready']).optional(),
  priority: taskPriority.default('normal'),
  assigneeMembershipId: uuid.nullable().optional(),
  reviewerMembershipId: uuid.nullable().optional(),
  startAt: isoDateTime.nullable().optional(),
  due: dueInput.nullable().optional(),
  estimateMinutes: estimate.nullable().optional(),
  parentTaskId: uuid.nullable().optional(),
  requiredForParent: z.boolean().optional(),
  tags: tags.optional(),
  followerMembershipIds: z.array(uuid).max(50).optional(),
  checklist: checklistSeed.optional(),
  ...links,
});
export type TaskCreateBody = z.infer<typeof taskCreateBody>;

export const taskUpdateBody = z
  .object({
    title: taskTitle,
    description: note.nullable(),
    priority: taskPriority,
    assigneeMembershipId: uuid.nullable(),
    reviewerMembershipId: uuid.nullable(),
    startAt: isoDateTime.nullable(),
    /** null clears the deadline explicitly. */
    due: dueInput.nullable(),
    /** Optional explanation stored on the deadline revision. */
    dueReason: z.string().trim().max(LIMITS.reasonMax),
    estimateMinutes: estimate.nullable(),
    requiredForParent: z.boolean(),
    tags,
    followerMembershipIds: z.array(uuid).max(50),
    accountId: uuid.nullable(),
    contentItemId: uuid.nullable(),
    publicationId: uuid.nullable(),
    shiftId: uuid.nullable(),
    operationId: uuid.nullable(),
    dealId: uuid.nullable(),
    deliverableId: uuid.nullable(),
    articleId: uuid.nullable(),
  })
  .partial();
export type TaskUpdateBody = z.infer<typeof taskUpdateBody>;

const historyEvent = z.object({
  id: uuid,
  from: taskStatus.nullable(),
  to: taskStatus,
  at: isoDateTime,
  effectiveAt: isoDateTime.nullable(),
  actor: memberRef.nullable(),
  reason: z.string().nullable(),
  cycle: z.number().int(),
});

export const checklistItem = z.object({
  id: uuid,
  label: z.string(),
  mandatory: z.boolean(),
  done: z.boolean(),
  doneAt: isoDateTime.nullable(),
  doneBy: memberRef.nullable(),
  position: z.number().int(),
  rowVersion: z.number().int(),
});

export const dependencyView = z.object({
  id: uuid,
  task: taskRef,
  kind: z.literal('finish_to_start'),
  overriddenAt: isoDateTime.nullable(),
  overrideReason: z.string().nullable(),
  createdAt: isoDateTime,
});

export const transitionOption = z.object({
  to: taskStatus,
  label: z.string(),
  allowed: z.boolean(),
  /** Why the move is not available now (missing assignee, open checklist, predecessors…). */
  reason: z.string().nullable(),
  needsReason: z.boolean(),
});

export const taskDetail = taskRow.extend({
  description: z.string().nullable(),
  baselineDueAt: isoDateTime.nullable(),
  requiredForParent: z.boolean(),
  completedBy: memberRef.nullable(),
  completionEffectiveAt: isoDateTime.nullable(),
  assigneeAtCompletion: memberRef.nullable(),
  cancelledAt: isoDateTime.nullable(),
  cancelReason: z.string().nullable(),
  cancellationAccepted: z.boolean(),
  reopenCount: z.number().int(),
  cycle: z.number().int(),
  followers: z.array(memberRef),
  checklistItems: z.array(checklistItem),
  predecessors: z.array(dependencyView),
  successors: z.array(dependencyView),
  subtaskList: z.array(taskRow.pick({ id: true, title: true, status: true, assignee: true, due: true, overdue: true, rowVersion: true }).extend({ requiredForParent: z.boolean(), cancellationAccepted: z.boolean() })),
  /** Parent completion policy: required children must be Done or Cancelled with accepted reason. */
  parentPolicy: z.object({ requiredOpen: z.number().int(), unacceptedCancellations: z.number().int() }),
  statusEvents: z.array(historyEvent),
  dueRevisions: z.array(z.object({ id: uuid, from: isoDateTime.nullable(), to: isoDateTime.nullable(), reason: z.string().nullable(), revision: z.number().int(), at: isoDateTime, actor: z.string().nullable() })),
  blockIntervals: z.array(z.object({ id: uuid, reason: z.string(), startedAt: isoDateTime, endedAt: isoDateTime.nullable(), resolution: z.string().nullable() })),
  time: z.object({ loggedSeconds: z.number().int(), myRunningTimerId: uuid.nullable() }),
  recurrenceRuleId: uuid.nullable(),
  templateApplicationId: uuid.nullable(),
  transitions: z.array(transitionOption),
  permissions: z.object({
    edit: z.boolean(),
    assign: z.boolean(),
    complete: z.boolean(),
    reopen: z.boolean(),
    cancel: z.boolean(),
    block: z.boolean(),
    comment: z.boolean(),
    createSubtask: z.boolean(),
    overrideDependencies: z.boolean(),
    trackTime: z.boolean(),
    manageChecklist: z.boolean(),
    attach: z.boolean(),
    archive: z.boolean(),
    trash: z.boolean(),
    duplicate: z.boolean(),
  }),
});
export type TaskDetail = z.infer<typeof taskDetail>;

export const taskListQuery = pageQuery.extend({
  q: z.string().trim().max(200).optional(),
  status: csv(taskStatus).optional(),
  priority: csv(taskPriority).optional(),
  projectId: uuid.optional(),
  /** Member id, `me` or `unassigned`. */
  assignee: z.string().max(40).optional(),
  reviewer: z.string().max(40).optional(),
  following: boolQuery.optional(),
  dueFrom: isoDateTime.optional(),
  dueTo: isoDateTime.optional(),
  overdue: boolQuery.optional(),
  noDue: boolQuery.optional(),
  blocked: boolQuery.optional(),
  tag: z.string().max(40).optional(),
  accountId: uuid.optional(),
  contentItemId: uuid.optional(),
  publicationId: uuid.optional(),
  shiftId: uuid.optional(),
  dealId: uuid.optional(),
  parentTaskId: uuid.optional(),
  /** Include Done and Cancelled tasks (hidden by default). */
  includeClosed: boolQuery.optional(),
  includeArchived: boolQuery.optional(),
  sort: z.enum(['dueAt', 'updatedAt', 'createdAt', 'title']).default('dueAt'),
  direction: z.enum(['asc', 'desc']).default('asc'),
});
export type TaskListQuery = z.infer<typeof taskListQuery>;

const taskFilterSnapshot = taskListQuery.omit({ cursor: true, pageSize: true, sort: true, direction: true });

export const bulkAction = z.discriminatedUnion('action', [
  z.object({ action: z.literal('assign'), assigneeMembershipId: uuid.nullable() }),
  z.object({ action: z.literal('reschedule'), shiftDays: z.number().int().min(-365).max(365).optional(), due: dueInput.nullable().optional() }),
  z.object({ action: z.literal('status'), targetState: taskStatus, reason: reason.optional() }),
  z.object({ action: z.literal('priority'), priority: taskPriority }),
  z.object({ action: z.literal('add_tags'), tags }),
]);
export type BulkAction = z.infer<typeof bulkAction>;

const bulkItem = z.object({ id: uuid, title: z.string().nullable(), status: z.enum(['ok', 'forbidden', 'conflict', 'invalid']), reason: z.string().nullable() });

const reschedulePreviewItem = z.object({
  task: taskRef,
  fromStart: isoDateTime.nullable(),
  toStart: isoDateTime.nullable(),
  fromDue: isoDateTime.nullable(),
  toDue: isoDateTime.nullable(),
  causedBy: uuid.nullable(),
  /** False when the actor may not reschedule that task: it is shown but never moved silently. */
  canApply: z.boolean(),
  rowVersion: z.number().int(),
});

export const templatePreviewNode = z.object({
  key: z.string(),
  title: z.string(),
  assignee: memberRef.nullable(),
  reviewer: memberRef.nullable(),
  startDate: isoDate.nullable(),
  dueDate: isoDate.nullable(),
  estimateMinutes: z.number().int().nullable(),
  dependsOn: z.array(z.string()),
  checklistCount: z.number().int(),
  responsibility: z.string().nullable(),
});

const templateTarget = {
  templateVersionId: uuid,
  targetType: z.enum(['project', 'content_item', 'deal', 'deliverable', 'publication', 'account', 'shift', 'operation', 'article']),
  targetId: uuid,
  projectId: uuid,
  accountId: uuid.nullable().optional(),
  startDate: isoDate,
  timezone: timezone.optional(),
  /** Assignments per template task key, responsibility or role key (`reviewer` for reviewers). */
  assignees: z.record(z.string().max(80), uuid).optional(),
};

export const recurrenceTemplate = z.object({
  title: taskTitle,
  description: note.nullable().optional(),
  assigneeMembershipId: uuid.nullable().optional(),
  reviewerMembershipId: uuid.nullable().optional(),
  priority: taskPriority.optional(),
  estimateMinutes: estimate.nullable().optional(),
  checklist: checklistSeed.optional(),
  dueOffsetMinutes: z.number().int().min(0).max(60 * 24 * 30).optional(),
});

const recurrenceFields = {
  projectId: uuid,
  template: recurrenceTemplate,
  cadence: z.enum(RECURRENCE_CADENCES),
  intervalCount: z.number().int().min(1).max(52).default(1),
  weekdays: z.array(z.number().int().min(1).max(7)).max(7).default([]),
  monthDay: z.number().int().min(1).max(31).nullable().optional(),
  monthDayPolicy: z.enum(MONTH_DAY_POLICIES).default('last_day_of_month'),
  localTime: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/, 'Use HH:MM (24-hour).'),
  timezone,
  mode: z.enum(RECURRENCE_MODES).default('fixed_schedule'),
  startsOn: isoDate,
  endsOn: isoDate.nullable().optional(),
  horizonDays: z.number().int().min(1).max(30).default(30),
  backfillLimit: z.number().int().min(0).max(30).default(0),
};

export const recurrenceRule = z.object({
  id: uuid,
  project: z.object({ id: uuid, name: z.string() }),
  owner: memberRef,
  template: recurrenceTemplate.extend({ assignee: memberRef.nullable(), reviewer: memberRef.nullable() }),
  cadence: z.enum(RECURRENCE_CADENCES),
  intervalCount: z.number().int(),
  weekdays: z.array(z.number().int()),
  monthDay: z.number().int().nullable(),
  monthDayPolicy: z.enum(MONTH_DAY_POLICIES),
  localTime: z.string(),
  timezone: z.string(),
  mode: z.enum(RECURRENCE_MODES),
  startsOn: isoDate,
  endsOn: isoDate.nullable(),
  horizonDays: z.number().int(),
  backfillLimit: z.number().int(),
  ruleVersion: z.number().int(),
  active: z.boolean(),
  lastGeneratedThrough: isoDateTime.nullable(),
  nextOccurrenceAt: isoDateTime.nullable(),
  archivedAt: isoDateTime.nullable(),
  updatedAt: isoDateTime,
  rowVersion: z.number().int(),
  canManage: z.boolean(),
});
export type RecurrenceRuleView = z.infer<typeof recurrenceRule>;

const occurrenceView = z.object({
  id: uuid,
  key: z.string(),
  scheduledFor: isoDateTime,
  state: z.enum(['created', 'missed', 'skipped', 'cancelled']),
  ruleVersion: z.number().int(),
  task: taskRef.nullable(),
  missedDates: z.array(z.string()),
});

const ruleDiff = z.object({
  updated: z.array(taskRef),
  cancelled: z.array(taskRef),
  created: z.array(z.object({ key: z.string(), scheduledFor: isoDateTime })),
  startedUnaffected: z.number().int(),
});

export const reminderView = z.object({
  id: uuid,
  entityType: z.string(),
  entityId: uuid,
  title: z.string().nullable(),
  href: z.string().nullable(),
  source: z.enum(['manual', 'due']),
  threshold: z.string().nullable(),
  remindAt: isoDateTime,
  snoozedUntil: isoDateTime.nullable(),
  /** Effective time: the snooze if set, otherwise the reminder time. */
  effectiveAt: isoDateTime,
  firedAt: isoDateTime.nullable(),
  note: z.string().nullable(),
  /** The deadline this reminder is about (unchanged by snoozing). */
  entityDueAt: isoDateTime.nullable(),
  rowVersion: z.number().int(),
});
export type ReminderView = z.infer<typeof reminderView>;

export const taskSavedView = z.object({ id: uuid, name: z.string(), filters: z.record(z.string(), z.string()), shared: z.boolean(), mine: z.boolean(), owner: memberRef.nullable() });

const P = <S extends z.ZodRawShape = {}>(shape: S = {} as S) => wsId({ taskId: uuid, ...shape });

export const taskEndpoints = {
  list: endpoint({
    id: 'tasks.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/tasks',
    summary: 'Tasks in the actor’s scope (scope applied in SQL before paging). Done/Cancelled and archived hidden by default.',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.read',
    params: wsId({}),
    query: taskListQuery,
    response: page(taskRow),
  }),
  count: endpoint({
    id: 'tasks.count',
    method: 'GET',
    path: '/workspaces/{workspaceId}/tasks/count',
    summary: 'Exact number of tasks matching the filters inside the actor’s scope (for Select All Matching).',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.read',
    params: wsId({}),
    query: taskFilterSnapshot,
    response: z.object({ count: z.number().int() }),
  }),
  get: endpoint({
    id: 'tasks.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/tasks/{taskId}',
    summary: 'Task detail with checklist, dependencies, subtasks, history and allowed actions.',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.read',
    params: P(),
    response: taskDetail,
  }),
  create: endpoint({
    id: 'tasks.create',
    method: 'POST',
    path: '/workspaces/{workspaceId}/tasks',
    summary: 'Create a task (Draft may be unassigned; priority defaults to Normal).',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.create',
    idempotent: true,
    params: wsId({}),
    body: taskCreateBody,
    response: taskDetail,
    successStatus: 201,
  }),
  update: endpoint({
    id: 'tasks.update',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/tasks/{taskId}',
    summary: 'Edit fields. Status changes go through /transition; a deadline change creates a revision, never moves the baseline.',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.edit',
    ifMatch: true,
    params: P(),
    body: taskUpdateBody,
    response: taskDetail,
  }),
  transition: endpoint({
    id: 'tasks.transition',
    method: 'POST',
    path: '/workspaces/{workspaceId}/tasks/{taskId}/transition',
    summary: 'Status change with dependency, checklist, review-policy and parent-completion checks.',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.edit',
    idempotent: true,
    ifMatch: true,
    params: P(),
    body: z.object({
      targetState: taskStatus,
      reason: reason.optional(),
      /** Start despite open predecessors (Lead only; audited with a snapshot). */
      overrideDependencies: z.boolean().optional(),
      /** Backdated completion (Lead only, with reason); the audit timestamp stays the server time. */
      effectiveAt: isoDateTime.optional(),
      /** Required when cancelling a task that other tasks wait for. */
      successorPolicy: z.enum(['remove_dependency', 'keep_blocked', 'replace']).optional(),
      replacementTaskId: uuid.optional(),
    }),
    response: taskDetail,
  }),
  block: endpoint({
    id: 'tasks.block',
    method: 'POST',
    path: '/workspaces/{workspaceId}/tasks/{taskId}/block',
    summary: 'Set the Blocked flag with a reason (the status stays unchanged).',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.edit',
    idempotent: true,
    ifMatch: true,
    params: P(),
    body: z.object({ reason, nextCheckAt: isoDateTime.nullable().optional() }),
    response: taskDetail,
  }),
  unblock: endpoint({
    id: 'tasks.unblock',
    method: 'POST',
    path: '/workspaces/{workspaceId}/tasks/{taskId}/unblock',
    summary: 'Clear the Blocked flag and close the blocker interval.',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.edit',
    idempotent: true,
    ifMatch: true,
    params: P(),
    body: z.object({ resolution: reason }),
    response: taskDetail,
  }),
  acceptCancellation: endpoint({
    id: 'tasks.acceptCancellation',
    method: 'POST',
    path: '/workspaces/{workspaceId}/tasks/{taskId}/accept-cancellation',
    summary: 'Accept the cancellation reason of a required subtask so the parent can complete.',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.assign',
    idempotent: true,
    ifMatch: true,
    params: P(),
    body: z.object({ note: z.string().trim().max(LIMITS.reasonMax).optional() }),
    response: taskDetail,
  }),
  createSubtask: endpoint({
    id: 'tasks.createSubtask',
    method: 'POST',
    path: '/workspaces/{workspaceId}/tasks/{taskId}/subtasks',
    summary: 'Create a child task in the parent’s project (project and access checked on the parent).',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.create',
    idempotent: true,
    params: P(),
    body: taskCreateBody.omit({ projectId: true, parentTaskId: true }),
    response: taskDetail,
    successStatus: 201,
  }),
  duplicate: endpoint({
    id: 'tasks.duplicate',
    method: 'POST',
    path: '/workspaces/{workspaceId}/tasks/{taskId}/duplicate',
    summary: 'Copy selected fields into a new Draft (no status, history, time or comments are copied).',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.create',
    idempotent: true,
    params: P(),
    body: z.object({
      targetProjectId: uuid.optional(),
      title: taskTitle.optional(),
      copiedFields: z.array(z.enum(['description', 'checklist', 'assignee', 'reviewer', 'estimate', 'tags', 'links', 'priority', 'attachments'])).max(20).default([]),
    }),
    response: taskDetail,
    successStatus: 201,
  }),
  follow: endpoint({
    id: 'tasks.follow',
    method: 'POST',
    path: '/workspaces/{workspaceId}/tasks/{taskId}/follow',
    summary: 'Follow or unfollow a task you can read (following never grants access).',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.read',
    idempotent: true,
    params: P(),
    body: z.object({ following: z.boolean() }),
    response: z.object({ following: z.boolean() }),
  }),
  addChecklistItem: endpoint({
    id: 'tasks.addChecklistItem',
    method: 'POST',
    path: '/workspaces/{workspaceId}/tasks/{taskId}/checklist',
    summary: 'Add a checklist item (mandatory items block completion).',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.edit',
    idempotent: true,
    params: P(),
    body: z.object({ label: z.string().trim().min(1).max(300), mandatory: z.boolean().default(false) }),
    response: checklistItem,
    successStatus: 201,
  }),
  updateChecklistItem: endpoint({
    id: 'tasks.updateChecklistItem',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/tasks/{taskId}/checklist/{itemId}',
    summary: 'Tick, rename, reorder or change the mandatory flag of a checklist item.',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.edit',
    ifMatch: true,
    params: P({ itemId: uuid }),
    body: z.object({ label: z.string().trim().min(1).max(300), mandatory: z.boolean(), done: z.boolean(), position: z.number().int().min(0).max(10_000) }).partial(),
    response: checklistItem,
  }),
  removeChecklistItem: endpoint({
    id: 'tasks.removeChecklistItem',
    method: 'POST',
    path: '/workspaces/{workspaceId}/tasks/{taskId}/checklist/{itemId}/remove',
    summary: 'Remove a checklist item (kept in history).',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.edit',
    idempotent: true,
    ifMatch: true,
    params: P({ itemId: uuid }),
    body: z.object({}),
    response: okResponse,
  }),
  dependencies: endpoint({
    id: 'tasks.dependencies',
    method: 'GET',
    path: '/workspaces/{workspaceId}/tasks/{taskId}/dependencies',
    summary: 'Predecessors and successors (Finish-to-Start).',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.read',
    params: P(),
    response: z.object({ predecessors: z.array(dependencyView), successors: z.array(dependencyView) }),
  }),
  addDependency: endpoint({
    id: 'tasks.addDependency',
    method: 'POST',
    path: '/workspaces/{workspaceId}/tasks/{taskId}/dependencies',
    summary: 'Add a predecessor (Finish-to-Start). Self-dependencies and cycles are rejected by the server.',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.edit',
    idempotent: true,
    params: P(),
    body: z.object({ predecessorId: uuid }),
    response: dependencyView,
    successStatus: 201,
  }),
  removeDependency: endpoint({
    id: 'tasks.removeDependency',
    method: 'POST',
    path: '/workspaces/{workspaceId}/tasks/{taskId}/dependencies/{dependencyId}/remove',
    summary: 'Remove a dependency relation with a reason (audited).',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.edit',
    idempotent: true,
    params: P({ dependencyId: uuid }),
    body: z.object({ reason }),
    response: okResponse,
  }),
  reschedulePreview: endpoint({
    id: 'tasks.reschedulePreview',
    method: 'POST',
    path: '/workspaces/{workspaceId}/tasks/{taskId}/reschedule-preview',
    summary: 'Compute new dates and, optionally, the pushed dates of dependent tasks. No changes are made.',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.edit',
    params: P(),
    body: z.object({ startAt: isoDateTime.nullable().optional(), due: dueInput.nullable().optional(), propagate: z.boolean().default(true) }),
    response: z.object({ token: uuid, expiresAt: isoDateTime, changes: z.array(reschedulePreviewItem) }),
  }),
  reschedule: endpoint({
    id: 'tasks.reschedule',
    method: 'POST',
    path: '/workspaces/{workspaceId}/tasks/{taskId}/reschedule',
    summary: 'Apply a reschedule preview atomically (selected dependent tasks only; stale previews are rejected).',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.edit',
    idempotent: true,
    ifMatch: true,
    params: P(),
    body: z.object({ previewToken: uuid, applyTaskIds: z.array(uuid).max(200).optional(), reason: z.string().trim().max(LIMITS.reasonMax).optional() }),
    response: taskDetail,
  }),
  attachments: endpoint({
    id: 'tasks.attachments',
    method: 'GET',
    path: '/workspaces/{workspaceId}/tasks/{taskId}/attachments',
    summary: 'Files linked to the task (authorised projections; restricted media stays hidden).',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.read',
    params: P(),
    response: z.array(z.object({ linkId: uuid, linkedAt: isoDateTime, asset: assetView })),
  }),
  activity: endpoint({
    id: 'tasks.activity',
    method: 'GET',
    path: '/workspaces/{workspaceId}/tasks/{taskId}/activity',
    summary: 'Meaningful task history (audited changes, masked values).',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.read',
    params: P(),
    query: pageQuery,
    response: page(
      z.object({
        id: uuid,
        action: z.string(),
        actorName: z.string().nullable(),
        occurredAt: isoDateTime,
        reason: z.string().nullable(),
        changes: z.array(z.object({ field: z.string(), from: z.unknown().optional(), to: z.unknown().optional() })),
      }),
    ),
  }),
  bulkPreview: endpoint({
    id: 'tasks.bulkPreview',
    method: 'POST',
    path: '/workspaces/{workspaceId}/tasks/bulk-preview',
    summary: 'Dry run of a bulk action over selected ids or all tasks matching a filter snapshot (10 min token).',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.edit',
    params: wsId({}),
    body: z.object({
      selection: z.union([z.object({ ids: z.array(uuid).min(1).max(200) }), z.object({ filter: taskFilterSnapshot, expectedCount: z.number().int().min(1).max(2000) })]),
      change: bulkAction,
    }),
    response: z.object({ token: uuid, expiresAt: isoDateTime, total: z.number().int(), counts: z.object({ ok: z.number().int(), forbidden: z.number().int(), conflict: z.number().int(), invalid: z.number().int() }), items: z.array(bulkItem) }),
  }),
  bulkApply: endpoint({
    id: 'tasks.bulkApply',
    method: 'POST',
    path: '/workspaces/{workspaceId}/tasks/bulk-apply',
    summary: 'Apply a previewed bulk action; each task succeeds or fails on its own (retry failures only).',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.edit',
    idempotent: true,
    params: wsId({}),
    body: z.object({ previewToken: uuid, onlyIds: z.array(uuid).max(2000).optional() }),
    response: z.object({ succeeded: z.number().int(), failed: z.number().int(), results: z.array(z.object({ id: uuid, ok: z.boolean(), code: z.string().nullable(), message: z.string().nullable() })) }),
  }),
  templateOptions: endpoint({
    id: 'tasks.templateOptions',
    method: 'GET',
    path: '/workspaces/{workspaceId}/task-templates',
    summary: 'Published task/content template versions that can be applied (templates are managed in Settings).',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.create',
    params: wsId({}),
    query: z.object({ q: z.string().max(100).optional() }),
    response: z.array(z.object({ templateId: uuid, templateVersionId: uuid, name: z.string(), kind: z.string(), versionNo: z.number().int(), taskCount: z.number().int(), description: z.string().nullable() })),
  }),
  templatePreview: endpoint({
    id: 'tasks.templatePreview',
    method: 'POST',
    path: '/workspaces/{workspaceId}/tasks/template-preview',
    summary: 'Preview names, assignments and dates before a template creates tasks. No changes are made.',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.create',
    params: wsId({}),
    body: z.object(templateTarget),
    response: z.object({
      template: z.object({ name: z.string(), versionNo: z.number().int() }),
      tasks: z.array(templatePreviewNode),
      unassignedCount: z.number().int(),
      existingApplication: z.object({ id: uuid, appliedAt: isoDateTime, taskCount: z.number().int() }).nullable(),
      applicationKey: z.string(),
    }),
  }),
  applyTemplate: endpoint({
    id: 'tasks.applyTemplate',
    method: 'POST',
    path: '/workspaces/{workspaceId}/tasks/apply-template',
    summary: 'Create the template’s task graph exactly once per application key (a repeat returns the first application).',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.create',
    idempotent: true,
    params: wsId({}),
    body: z.object({ ...templateTarget, applicationKey: z.string().min(3).max(300) }),
    response: z.object({ applicationId: uuid, created: z.boolean(), taskIds: z.array(uuid), coordinationTaskId: uuid.nullable() }),
    successStatus: 201,
  }),
  views: endpoint({
    id: 'tasks.views',
    method: 'GET',
    path: '/workspaces/{workspaceId}/task-views',
    summary: 'Saved task views (own and shared).',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.read',
    params: wsId({}),
    response: z.array(taskSavedView),
  }),
  saveView: endpoint({
    id: 'tasks.saveView',
    method: 'POST',
    path: '/workspaces/{workspaceId}/task-views',
    summary: 'Save the current filters as a named view (typed filters only, never SQL).',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.read',
    idempotent: true,
    params: wsId({}),
    body: z.object({ name: z.string().trim().min(2).max(80), filters: z.record(z.string().max(40), z.string().max(400)), shared: z.boolean().default(false) }),
    response: taskSavedView,
    successStatus: 201,
  }),
  deleteView: endpoint({
    id: 'tasks.deleteView',
    method: 'POST',
    path: '/workspaces/{workspaceId}/task-views/{viewId}/delete',
    summary: 'Delete one of your saved views.',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.read',
    idempotent: true,
    params: wsId({ viewId: uuid }),
    body: z.object({}),
    response: okResponse,
  }),
};

export const recurrenceEndpoints = {
  list: endpoint({
    id: 'recurrences.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/recurrences',
    summary: 'Recurring task rules in the actor’s scope.',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.read',
    params: wsId({}),
    query: z.object({ projectId: uuid.optional(), includeArchived: boolQuery.optional() }),
    response: z.array(recurrenceRule),
  }),
  get: endpoint({
    id: 'recurrences.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/recurrences/{ruleId}',
    summary: 'Rule with its upcoming and recent occurrences.',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.read',
    params: wsId({ ruleId: uuid }),
    response: recurrenceRule.extend({ occurrences: z.array(occurrenceView), upcoming: z.array(z.object({ key: z.string(), scheduledFor: isoDateTime, clampedToMonthEnd: z.boolean() })) }),
  }),
  preview: endpoint({
    id: 'recurrences.preview',
    method: 'POST',
    path: '/workspaces/{workspaceId}/recurrences/preview',
    summary: 'Next occurrences of a proposed schedule (no changes).',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.create',
    params: wsId({}),
    body: z.object({ ...recurrenceFields, template: recurrenceTemplate.partial().optional(), projectId: uuid.optional() }),
    response: z.object({ occurrences: z.array(z.object({ key: z.string(), scheduledFor: isoDateTime, clampedToMonthEnd: z.boolean(), dstShifted: z.boolean() })) }),
  }),
  create: endpoint({
    id: 'recurrences.create',
    method: 'POST',
    path: '/workspaces/{workspaceId}/recurrences',
    summary: 'Create a recurring task rule; occurrences within the horizon are generated immediately.',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.create',
    idempotent: true,
    params: wsId({}),
    body: z.object(recurrenceFields),
    response: recurrenceRule,
    successStatus: 201,
  }),
  changePreview: endpoint({
    id: 'recurrences.changePreview',
    method: 'POST',
    path: '/workspaces/{workspaceId}/recurrences/{ruleId}/change-preview',
    summary: 'Diff of a rule change on future not-started instances (started work is never changed).',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.create',
    params: wsId({ ruleId: uuid }),
    body: z.object(recurrenceFields).omit({ projectId: true }).partial(),
    response: ruleDiff,
  }),
  update: endpoint({
    id: 'recurrences.update',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/recurrences/{ruleId}',
    summary: 'Change the rule (new rule version) and apply the previewed diff to future not-started instances.',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.create',
    ifMatch: true,
    params: wsId({ ruleId: uuid }),
    body: z.object(recurrenceFields).omit({ projectId: true }).partial(),
    response: recurrenceRule.extend({ diff: ruleDiff }),
  }),
  setActive: endpoint({
    id: 'recurrences.setActive',
    method: 'POST',
    path: '/workspaces/{workspaceId}/recurrences/{ruleId}/active',
    summary: 'Pause or resume generation (existing tasks are kept).',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.create',
    idempotent: true,
    ifMatch: true,
    params: wsId({ ruleId: uuid }),
    body: z.object({ active: z.boolean() }),
    response: recurrenceRule,
  }),
  archive: endpoint({
    id: 'recurrences.archive',
    method: 'POST',
    path: '/workspaces/{workspaceId}/recurrences/{ruleId}/archive',
    summary: 'Stop the rule for good; future not-started instances can be cancelled with it.',
    tags: ['Tasks'],
    auth: 'workspace',
    permission: 'tasks.create',
    idempotent: true,
    ifMatch: true,
    params: wsId({ ruleId: uuid }),
    body: z.object({ cancelFutureInstances: z.boolean().default(false), reason: reason.optional() }),
    response: recurrenceRule,
  }),
};

export const reminderEndpoints = {
  list: endpoint({
    id: 'reminders.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/personal-reminders',
    summary: 'Your own reminders (due now and upcoming).',
    tags: ['My Work'],
    auth: 'workspace',
    params: wsId({}),
    query: z.object({ entityType: z.string().max(40).optional(), entityId: uuid.optional() }),
    response: z.array(reminderView),
  }),
  create: endpoint({
    id: 'reminders.create',
    method: 'POST',
    path: '/workspaces/{workspaceId}/personal-reminders',
    summary: 'Remind yourself about a task you can read (never changes its deadline).',
    tags: ['My Work'],
    auth: 'workspace',
    idempotent: true,
    params: wsId({}),
    body: z.object({ entityType: z.literal('task'), entityId: uuid, remindAt: isoDateTime, note: z.string().trim().max(500).optional() }),
    response: reminderView,
    successStatus: 201,
  }),
  snooze: endpoint({
    id: 'reminders.snooze',
    method: 'POST',
    path: '/workspaces/{workspaceId}/personal-reminders/{reminderId}/snooze',
    summary: 'Snooze your own reminder. The task deadline is not changed.',
    tags: ['My Work'],
    auth: 'workspace',
    idempotent: true,
    params: wsId({ reminderId: uuid }),
    body: z.object({ until: isoDateTime }),
    response: reminderView,
  }),
  dismiss: endpoint({
    id: 'reminders.dismiss',
    method: 'POST',
    path: '/workspaces/{workspaceId}/personal-reminders/{reminderId}/dismiss',
    summary: 'Dismiss your own reminder.',
    tags: ['My Work'],
    auth: 'workspace',
    idempotent: true,
    params: wsId({ reminderId: uuid }),
    body: z.object({}),
    response: okResponse,
  }),
};

export { linkedRef, dueView };
