import { z } from 'zod';
import { LIMITS, TIME_ENTRY_SOURCES, TIME_ENTRY_STATES } from '@castlane/domain';
import { endpoint } from '../core';
import { csv, isoDate, isoDateTime, memberRef, okResponse, page, pageQuery, reason, uuid, wsId } from '../common';
import { taskRef } from './common';

export const timeEntryView = z.object({
  id: uuid,
  member: memberRef,
  task: taskRef,
  project: z.object({ id: uuid, name: z.string() }),
  source: z.enum(TIME_ENTRY_SOURCES),
  state: z.enum(TIME_ENTRY_STATES),
  startedAt: isoDateTime.nullable(),
  endedAt: isoDateTime.nullable(),
  durationSeconds: z.number().int().nullable(),
  workDate: isoDate,
  note: z.string().nullable(),
  /** Present only for members who may see or set billable flags (time.approve in scope). */
  billable: z.boolean().optional(),
  submissionId: uuid.nullable(),
  approvedAt: isoDateTime.nullable(),
  approvedBy: memberRef.nullable(),
  returnedReason: z.string().nullable(),
  revisionOf: uuid.nullable(),
  supersededAt: isoDateTime.nullable(),
  needsReviewReason: z.string().nullable(),
  closedBy: memberRef.nullable(),
  closeReason: z.string().nullable(),
  /** Ids of this member's other entries whose intervals intersect this one (must be resolved before approval). */
  overlapsWith: z.array(uuid),
  permissions: z.object({ edit: z.boolean(), discard: z.boolean(), revise: z.boolean(), approve: z.boolean(), stop: z.boolean(), close: z.boolean() }),
  createdAt: isoDateTime,
  rowVersion: z.number().int(),
});
export type TimeEntryView = z.infer<typeof timeEntryView>;

export const timerView = z.object({
  id: uuid,
  task: taskRef,
  project: z.object({ id: uuid, name: z.string() }),
  /** Server start time; the browser only displays the elapsed time. */
  startedAt: isoDateTime,
  elapsedSeconds: z.number().int(),
  needsReview: z.boolean(),
  note: z.string().nullable(),
  rowVersion: z.number().int(),
});

export const timeSheetView = z.object({
  id: uuid,
  member: memberRef,
  weekStart: isoDate,
  state: z.enum(['submitted', 'approved', 'returned']),
  submittedAt: isoDateTime,
  decidedAt: isoDateTime.nullable(),
  decidedBy: memberRef.nullable(),
  approver: memberRef.nullable(),
  reason: z.string().nullable(),
  totalSeconds: z.number().int(),
  entryCount: z.number().int(),
  overlapCount: z.number().int(),
  canDecide: z.boolean(),
  rowVersion: z.number().int(),
});
export type TimeSheetView = z.infer<typeof timeSheetView>;

const entryFields = {
  taskId: uuid,
  startedAt: isoDateTime.nullable().optional(),
  endedAt: isoDateTime.nullable().optional(),
  durationMinutes: z.number().int().min(1).max(24 * 60).nullable().optional(),
  workDate: isoDate.optional(),
  note: z.string().trim().max(LIMITS.noteMax).nullable().optional(),
  billable: z.boolean().optional(),
};

export const timeEndpoints = {
  currentTimer: endpoint({
    id: 'time.currentTimer',
    method: 'GET',
    path: '/workspaces/{workspaceId}/timers/current',
    summary: 'Your running timer, if any (kept on the server when the browser closes).',
    tags: ['Time'],
    auth: 'workspace',
    permission: 'time.write.own',
    params: wsId({}),
    response: z.object({ timer: timerView.nullable() }),
  }),
  startTimer: endpoint({
    id: 'time.startTimer',
    method: 'POST',
    path: '/workspaces/{workspaceId}/timers/start',
    summary: 'Start a timer on a task. One running timer per member (database constraint).',
    tags: ['Time'],
    auth: 'workspace',
    permission: 'time.write.own',
    idempotent: true,
    params: wsId({}),
    body: z.object({ taskId: uuid, note: z.string().trim().max(500).optional() }),
    response: timerView,
    successStatus: 201,
  }),
  stopTimer: endpoint({
    id: 'time.stopTimer',
    method: 'POST',
    path: '/workspaces/{workspaceId}/timers/{timerId}/stop',
    summary: 'Stop your timer: exactly one time entry. After 24 h the actual end must be entered (no invented stop).',
    tags: ['Time'],
    auth: 'workspace',
    permission: 'time.write.own',
    idempotent: true,
    params: wsId({ timerId: uuid }),
    body: z.object({ note: z.string().trim().max(LIMITS.noteMax).optional(), endedAt: isoDateTime.optional(), reason: reason.optional() }),
    response: timeEntryView,
  }),
  closeTimer: endpoint({
    id: 'time.closeTimer',
    method: 'POST',
    path: '/workspaces/{workspaceId}/timers/{timerId}/close',
    summary: 'Manager closes another member’s timer with the actual end and a reason (entry goes to Needs Review).',
    tags: ['Time'],
    auth: 'workspace',
    permission: 'time.approve',
    idempotent: true,
    params: wsId({ timerId: uuid }),
    body: z.object({ endedAt: isoDateTime, reason }),
    response: timeEntryView,
  }),
  list: endpoint({
    id: 'time.list',
    method: 'GET',
    path: '/workspaces/{workspaceId}/time-entries',
    summary: 'Time entries you may see: your own, or members’ entries in projects where you hold time.read.scope.',
    tags: ['Time'],
    auth: 'workspace',
    params: wsId({}),
    query: pageQuery.extend({
      from: isoDate.optional(),
      to: isoDate.optional(),
      membershipId: uuid.optional(),
      projectId: uuid.optional(),
      taskId: uuid.optional(),
      state: csv(z.enum(TIME_ENTRY_STATES)).optional(),
      includeSuperseded: z.preprocess((v) => v === 'true', z.boolean()).optional(),
    }),
    response: page(timeEntryView).extend({ totalSeconds: z.number().int() }),
  }),
  get: endpoint({
    id: 'time.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/time-entries/{entryId}',
    summary: 'One time entry.',
    tags: ['Time'],
    auth: 'workspace',
    params: wsId({ entryId: uuid }),
    response: timeEntryView,
  }),
  create: endpoint({
    id: 'time.create',
    method: 'POST',
    path: '/workspaces/{workspaceId}/time-entries',
    summary: 'Manual entry: start/end, or a duration on a date. ≤ 24 h, > 0, not in the future. Overlaps are reported.',
    tags: ['Time'],
    auth: 'workspace',
    permission: 'time.write.own',
    idempotent: true,
    params: wsId({}),
    body: z.object(entryFields),
    response: timeEntryView,
    successStatus: 201,
  }),
  update: endpoint({
    id: 'time.update',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/time-entries/{entryId}',
    summary: 'Edit your unapproved entry (draft, needs review or returned).',
    tags: ['Time'],
    auth: 'workspace',
    permission: 'time.write.own',
    ifMatch: true,
    params: wsId({ entryId: uuid }),
    body: z.object(entryFields).partial(),
    response: timeEntryView,
  }),
  discard: endpoint({
    id: 'time.discard',
    method: 'POST',
    path: '/workspaces/{workspaceId}/time-entries/{entryId}/discard',
    summary: 'Discard your unapproved entry (approved time is corrected by revision instead).',
    tags: ['Time'],
    auth: 'workspace',
    permission: 'time.write.own',
    idempotent: true,
    ifMatch: true,
    params: wsId({ entryId: uuid }),
    body: z.object({}),
    response: okResponse,
  }),
  revise: endpoint({
    id: 'time.revise',
    method: 'POST',
    path: '/workspaces/{workspaceId}/time-entries/{entryId}/revisions',
    summary: 'Correct an approved entry with a new revision; the approved one stays until the revision is approved.',
    tags: ['Time'],
    auth: 'workspace',
    permission: 'time.write.own',
    idempotent: true,
    params: wsId({ entryId: uuid }),
    body: z.object({ ...entryFields, taskId: uuid.optional(), reason }),
    response: timeEntryView,
    successStatus: 201,
  }),
  approve: endpoint({
    id: 'time.approve',
    method: 'POST',
    path: '/workspaces/{workspaceId}/time-entries/{entryId}/approve',
    summary: 'Approve one submitted entry (immutable afterwards). Overlapping entries cannot be approved.',
    tags: ['Time'],
    auth: 'workspace',
    permission: 'time.approve',
    idempotent: true,
    ifMatch: true,
    params: wsId({ entryId: uuid }),
    body: z.object({ reviewerNote: z.string().trim().max(LIMITS.reasonMax).optional() }),
    response: timeEntryView,
  }),
  week: endpoint({
    id: 'time.week',
    method: 'GET',
    path: '/workspaces/{workspaceId}/time-sheets/week',
    summary: 'A member’s week: entries, totals, overlaps and the latest submission.',
    tags: ['Time'],
    auth: 'workspace',
    params: wsId({}),
    query: z.object({ weekStart: isoDate.optional(), membershipId: uuid.optional() }),
    response: z.object({
      member: memberRef,
      weekStart: isoDate,
      weekEnd: isoDate,
      timezone: z.string(),
      entries: z.array(timeEntryView),
      totalSeconds: z.number().int(),
      byDay: z.array(z.object({ date: isoDate, seconds: z.number().int() })),
      submission: timeSheetView.nullable(),
      canSubmit: z.boolean(),
      blockers: z.array(z.string()),
    }),
  }),
  submitWeek: endpoint({
    id: 'time.submitWeek',
    method: 'POST',
    path: '/workspaces/{workspaceId}/time-sheets/submit',
    summary: 'Submit your week: the listed entry versions are frozen for approval.',
    tags: ['Time'],
    auth: 'workspace',
    permission: 'time.write.own',
    idempotent: true,
    params: wsId({}),
    body: z.object({ weekStart: isoDate, entries: z.array(z.object({ id: uuid, rowVersion: z.number().int() })).min(1).max(500) }),
    response: timeSheetView,
    successStatus: 201,
  }),
  sheets: endpoint({
    id: 'time.sheets',
    method: 'GET',
    path: '/workspaces/{workspaceId}/time-sheets',
    summary: 'Submitted time sheets you may decide on or your own.',
    tags: ['Time'],
    auth: 'workspace',
    params: wsId({}),
    query: pageQuery.extend({ state: csv(z.enum(['submitted', 'approved', 'returned'])).optional(), membershipId: uuid.optional(), mine: z.preprocess((v) => v === 'true', z.boolean()).optional() }),
    response: page(timeSheetView),
  }),
  sheet: endpoint({
    id: 'time.sheet',
    method: 'GET',
    path: '/workspaces/{workspaceId}/time-sheets/{sheetId}',
    summary: 'A time sheet with its entries and overlap report.',
    tags: ['Time'],
    auth: 'workspace',
    params: wsId({ sheetId: uuid }),
    response: timeSheetView.extend({ entries: z.array(timeEntryView), changedSinceSubmission: z.array(uuid) }),
  }),
  approveSheet: endpoint({
    id: 'time.approveSheet',
    method: 'POST',
    path: '/workspaces/{workspaceId}/time-sheets/{sheetId}/approve',
    summary: 'Approve all entries of the sheet atomically; refused while entries overlap or changed.',
    tags: ['Time'],
    auth: 'workspace',
    permission: 'time.approve',
    idempotent: true,
    ifMatch: true,
    params: wsId({ sheetId: uuid }),
    body: z.object({ reviewerNote: z.string().trim().max(LIMITS.reasonMax).optional() }),
    response: timeSheetView,
  }),
  returnSheet: endpoint({
    id: 'time.returnSheet',
    method: 'POST',
    path: '/workspaces/{workspaceId}/time-sheets/{sheetId}/return',
    summary: 'Return the sheet with a reason; entries become editable again and the history is kept.',
    tags: ['Time'],
    auth: 'workspace',
    permission: 'time.approve',
    idempotent: true,
    ifMatch: true,
    params: wsId({ sheetId: uuid }),
    body: z.object({ reason }),
    response: timeSheetView,
  }),
};
