import { z } from 'zod';
import { ABSENCE_CATEGORIES, ABSENCE_STATES, LIMITS } from '@castlane/domain';
import { endpoint } from '../core';
import { csv, isoDate, isoDateTime, memberRef, uuid, wsId } from '../common';
import { dueView, taskRef, taskRow } from './common';

const minutes = z.number().int().min(0).max(24 * 60);
export const weekdayMinutes = z.object({
  monday: minutes,
  tuesday: minutes,
  wednesday: minutes,
  thursday: minutes,
  friday: minutes,
  saturday: minutes,
  sunday: minutes,
});

export const capacityView = z.object({
  id: uuid,
  member: memberRef,
  effectiveFrom: isoDate,
  weekdayMinutes,
  weeklyMinutes: z.number().int(),
  confirmedAt: isoDateTime.nullable(),
  confirmedBy: memberRef.nullable(),
  rowVersion: z.number().int(),
});

export const absenceView = z.object({
  id: uuid,
  member: memberRef,
  startDate: isoDate,
  endDate: isoDate,
  category: z.enum(ABSENCE_CATEGORIES),
  state: z.enum(ABSENCE_STATES),
  /** Omitted for colleagues who may not see the private reason. */
  privateReason: z.string().nullable().optional(),
  decidedBy: memberRef.nullable(),
  canDecide: z.boolean(),
  canEdit: z.boolean(),
  rowVersion: z.number().int(),
});
export type AbsenceView = z.infer<typeof absenceView>;

export const workloadMember = z.object({
  member: memberRef,
  capacityCoverage: z.enum(['full', 'partial', 'none']),
  capacityMinutes: z.number().int().nullable(),
  availableMinutes: z.number().int().nullable(),
  plannedMinutes: z.number().int(),
  overloadMinutes: z.number().int().nullable(),
  dailyOverloadMinutes: z.number().int().nullable(),
  /** Open tasks without estimate in the period: an unknown amount, never zero hours. */
  unestimatedCount: z.number().int(),
  unscheduledCount: z.number().int(),
  unscheduledMinutes: z.number().int(),
  overdueCount: z.number().int(),
  overdueMinutes: z.number().int(),
  days: z.array(
    z.object({
      date: isoDate,
      capacityMinutes: z.number().int().nullable(),
      absent: z.boolean(),
      availableMinutes: z.number().int().nullable(),
      plannedMinutes: z.number().int(),
      overloadMinutes: z.number().int().nullable(),
    }),
  ),
  absences: z.array(absenceView),
  tasks: z.array(
    z.object({
      id: uuid,
      title: z.string(),
      project: z.object({ id: uuid, name: z.string() }),
      status: taskRow.shape.status,
      due: dueView.nullable(),
      startAt: isoDateTime.nullable(),
      estimateMinutes: z.number().int().nullable(),
      loggedMinutes: z.number().int(),
      remainingMinutes: z.number().int().nullable(),
      plannedInPeriod: z.number().int().nullable(),
      method: z.enum(['even', 'manual', 'deadline_day', 'overdue', 'unscheduled', 'unestimated']),
      rowVersion: z.number().int(),
    }),
  ),
});
export type WorkloadMember = z.infer<typeof workloadMember>;

export const workloadEndpoints = {
  get: endpoint({
    id: 'workload.get',
    method: 'GET',
    path: '/workspaces/{workspaceId}/workload',
    summary: 'Capacity, absences, planned estimates, unestimated counts and overload per visible member.',
    tags: ['Workload'],
    auth: 'workspace',
    permission: 'workload.read',
    params: wsId({}),
    query: z.object({
      from: isoDate.optional(),
      period: z.enum(['week', 'month']).default('week'),
      membershipIds: csv(uuid).optional(),
      projectId: uuid.optional(),
      directionId: uuid.optional(),
    }),
    response: z.object({
      from: isoDate,
      to: isoDate,
      today: isoDate,
      timezone: z.string(),
      algorithm: z.string(),
      members: z.array(workloadMember),
      permissions: z.object({ manage: z.boolean() }),
    }),
  }),
  reassignPreview: endpoint({
    id: 'workload.reassignPreview',
    method: 'POST',
    path: '/workspaces/{workspaceId}/workload/reassign-preview',
    summary: 'Effect of moving a task to another member on both members’ planned load (no changes).',
    tags: ['Workload'],
    auth: 'workspace',
    permission: 'tasks.assign',
    params: wsId({}),
    body: z.object({ taskId: uuid, toMembershipId: uuid, from: isoDate, period: z.enum(['week', 'month']).default('week') }),
    response: z.object({
      task: taskRef.extend({ rowVersion: z.number().int(), estimateMinutes: z.number().int().nullable() }),
      from: z.object({ member: memberRef.nullable(), plannedBefore: z.number().int(), plannedAfter: z.number().int(), availableMinutes: z.number().int().nullable() }).nullable(),
      to: z.object({ member: memberRef, plannedBefore: z.number().int(), plannedAfter: z.number().int(), availableMinutes: z.number().int().nullable(), canAccessTask: z.boolean() }),
    }),
  }),
  setAllocation: endpoint({
    id: 'workload.setAllocation',
    method: 'POST',
    path: '/workspaces/{workspaceId}/workload/allocations',
    summary: 'Replace the manual daily allocation of a task for its assignee (empty list = back to the even split).',
    tags: ['Workload'],
    auth: 'workspace',
    permission: 'workload.manage',
    idempotent: true,
    params: wsId({}),
    body: z.object({ taskId: uuid, allocations: z.array(z.object({ date: isoDate, minutes: z.number().int().min(1).max(24 * 60) })).max(62) }),
    response: z.object({ taskId: uuid, allocations: z.array(z.object({ date: isoDate, minutes: z.number().int() })) }),
  }),
  capacities: endpoint({
    id: 'workload.capacities',
    method: 'GET',
    path: '/workspaces/{workspaceId}/capacities',
    summary: 'Capacity profiles (weekly schedule versions) of a member.',
    tags: ['Workload'],
    auth: 'workspace',
    params: wsId({}),
    query: z.object({ membershipId: uuid }),
    response: z.object({ items: z.array(capacityView), template: weekdayMinutes, canManage: z.boolean() }),
  }),
  setCapacity: endpoint({
    id: 'workload.setCapacity',
    method: 'POST',
    path: '/workspaces/{workspaceId}/capacities',
    summary: 'Confirm a member’s weekly capacity from a date (8 h Mon–Fri is only a suggested template).',
    tags: ['Workload'],
    auth: 'workspace',
    permission: 'workload.manage',
    idempotent: true,
    params: wsId({}),
    body: z.object({ membershipId: uuid, effectiveFrom: isoDate, weekdayMinutes }),
    response: capacityView,
    successStatus: 201,
  }),
  updateCapacity: endpoint({
    id: 'workload.updateCapacity',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/capacities/{capacityId}',
    summary: 'Adjust a capacity profile.',
    tags: ['Workload'],
    auth: 'workspace',
    permission: 'workload.manage',
    ifMatch: true,
    params: wsId({ capacityId: uuid }),
    body: z.object({ weekdayMinutes }),
    response: capacityView,
  }),
  absences: endpoint({
    id: 'workload.absences',
    method: 'GET',
    path: '/workspaces/{workspaceId}/absences',
    summary: 'Absences you may see (private reasons only for the member, their manager and workload managers).',
    tags: ['Workload'],
    auth: 'workspace',
    params: wsId({}),
    query: z.object({ membershipId: uuid.optional(), from: isoDate.optional(), to: isoDate.optional(), state: csv(z.enum(ABSENCE_STATES)).optional() }),
    response: z.array(absenceView),
  }),
  createAbsence: endpoint({
    id: 'workload.createAbsence',
    method: 'POST',
    path: '/workspaces/{workspaceId}/absences',
    summary: 'Request leave for yourself (Requested) or record it for a member you manage (Approved).',
    tags: ['Workload'],
    auth: 'workspace',
    idempotent: true,
    params: wsId({}),
    body: z.object({
      membershipId: uuid,
      startDate: isoDate,
      endDate: isoDate,
      category: z.enum(ABSENCE_CATEGORIES),
      privateReason: z.string().trim().max(LIMITS.reasonMax).nullable().optional(),
    }),
    response: absenceView.extend({ affected: z.object({ tasksDue: z.number().int(), shiftsScheduled: z.number().int() }) }),
    successStatus: 201,
  }),
  updateAbsence: endpoint({
    id: 'workload.updateAbsence',
    method: 'PATCH',
    path: '/workspaces/{workspaceId}/absences/{absenceId}',
    summary: 'Change dates, category or private reason of a requested absence (or any, for managers).',
    tags: ['Workload'],
    auth: 'workspace',
    ifMatch: true,
    params: wsId({ absenceId: uuid }),
    body: z
      .object({ startDate: isoDate, endDate: isoDate, category: z.enum(ABSENCE_CATEGORIES), privateReason: z.string().trim().max(LIMITS.reasonMax).nullable() })
      .partial(),
    response: absenceView,
  }),
  decideAbsence: endpoint({
    id: 'workload.decideAbsence',
    method: 'POST',
    path: '/workspaces/{workspaceId}/absences/{absenceId}/decide',
    summary: 'Approve or reject a requested absence (workload managers and the member’s manager).',
    tags: ['Workload'],
    auth: 'workspace',
    permission: 'workload.manage',
    idempotent: true,
    ifMatch: true,
    params: wsId({ absenceId: uuid }),
    body: z.object({ decision: z.enum(['approve', 'reject']), reason: z.string().trim().max(LIMITS.reasonMax).optional() }),
    response: absenceView,
  }),
  cancelAbsence: endpoint({
    id: 'workload.cancelAbsence',
    method: 'POST',
    path: '/workspaces/{workspaceId}/absences/{absenceId}/cancel',
    summary: 'Cancel an absence (kept in history).',
    tags: ['Workload'],
    auth: 'workspace',
    idempotent: true,
    ifMatch: true,
    params: wsId({ absenceId: uuid }),
    body: z.object({ reason: z.string().trim().max(LIMITS.reasonMax).optional() }),
    response: absenceView,
  }),
};
