import { registerLabels } from '@/lib/labels';

/** English dictionary for OFM enum values (section 21: system strings in dictionaries). */
registerLabels({
  shiftState: { scheduled: 'Scheduled', active: 'Active', paused: 'Paused', ended: 'Ended', cancelled: 'Cancelled', missed: 'Missed' },
  reportState: { not_started: 'Report Not Started', draft: 'Report Pending', submitted: 'Report Submitted', changes_requested: 'Changes Requested', approved: 'Report Approved' },
  reportVersionState: { draft: 'Draft', submitted: 'Submitted', changes_requested: 'Changes Requested', approved: 'Approved' },
  coverageLane: { primary: 'Primary', support: 'Support', custom: 'Custom' },
  handoverState: { draft: 'Draft', submitted: 'Waiting for Acknowledgement', acknowledged: 'Acknowledged' },
  handoverItemState: { open: 'Open', accepted: 'Accepted', resolved: 'Resolved' },
  contactStage: { new: 'New', active: 'Active', follow_up: 'Follow-up', inactive: 'Inactive', archived: 'Archived' },
  interactionType: { message_summary: 'Message Summary', request: 'Request', issue: 'Issue', other: 'Other' },
  operationType: {
    follow_up: 'Follow-up',
    content_request: 'Content Request',
    payment_check: 'Payment Check',
    account_check: 'Account Check',
    issue_resolution: 'Issue Resolution',
    other: 'Other',
  },
  operationStatus: { open: 'Open', in_progress: 'In Progress', waiting: 'Waiting', completed: 'Completed', cancelled: 'Cancelled' },
  saleState: { pending: 'Pending Verification', verified: 'Verified', rejected: 'Rejected' },
  attribution: { unassigned: 'Unassigned', partial: 'Partly Attributed', full: 'Fully Attributed' },
  qualityState: { draft: 'Draft', published: 'Published', disputed: 'Disputed', resolved: 'Resolved' },
  swapState: { pending_acceptance: 'Waiting for Member', pending_approval: 'Waiting for Approval', approved: 'Approved', declined: 'Declined', cancelled: 'Withdrawn' },
  needsReview: { forgotten_end: 'Not Ended', not_started: 'Not Started', actual_overlap: 'Overlapping Time' },
  assignmentStatus: { upcoming: 'Upcoming', current: 'Current', ended: 'Ended' },
  erasureState: { queued: 'Erasure Queued', running: 'Erasing', completed: 'Erased', failed: 'Erasure Failed' },
  rubricState: { draft: 'Draft', published: 'Published', retired: 'Retired' },
  disputeDecision: { upheld: 'Upheld', revised: 'Revised', withdrawn: 'Withdrawn' },
  priority: { low: 'Low', normal: 'Normal', high: 'High', urgent: 'Urgent' },
  responsibility: {
    ofm_operations: 'OFM Operations',
    quality_review: 'Quality Review',
    direction_management: 'Direction Management',
    producing: 'Producing',
    writing: 'Writing',
    image_generation: 'Image Generation',
    video_generation: 'Video Generation',
    voice: 'Voice',
    editing: 'Editing',
    publishing: 'Publishing',
    analytics: 'Analytics',
    finance: 'Finance',
  },
});
