/**
 * Permission catalog (section 7.3). Keys are stable strings stored in roles.permissions.
 */
export const PERMISSION_GROUPS = {
  identity: [
    'workspace.read',
    'workspace.update',
    'members.read',
    'members.invite',
    'members.update',
    'members.suspend',
    'access.read',
    'access.manage',
    'ownership.transfer',
    'audit.read',
    'audit.export',
    'security.sessions.revoke',
  ],
  production: [
    'directions.read',
    'directions.manage',
    'projects.read',
    'projects.create',
    'projects.update',
    'projects.archive',
    'project.members.manage',
    'characters.read',
    'characters.write',
    'characters.approve',
    'series.read',
    'series.write',
    'accounts.read',
    'accounts.write',
    'accounts.assign',
    'accounts.archive',
    'references.read',
    'references.write',
    'content.read',
    'content.create',
    'content.edit',
    'content.upload',
    'content.submit',
    'content.approve',
    'content.archive',
    'tasks.read',
    'tasks.create',
    'tasks.edit',
    'tasks.assign',
    'tasks.complete',
    'tasks.reopen',
    'time.read.own',
    'time.read.scope',
    'time.write.own',
    'time.approve',
    'workload.read',
    'workload.manage',
    'publications.read',
    'publications.write',
    'publications.confirm',
    'publications.correct',
    'campaigns.read',
    'campaigns.write',
    'experiments.read',
    'experiments.write',
    'partners.read',
    'partners.write',
    'deals.read',
    'deals.write',
    'incidents.read',
    'incidents.write',
  ],
  media: [
    'assets.read',
    'assets.upload',
    'assets.download',
    'assets.link',
    'assets.archive',
    'assets.restricted.read',
    'knowledge.read',
    'knowledge.write',
    'knowledge.publish',
    'knowledge.acknowledge',
  ],
  ofm: [
    'ofm.overview.read',
    'ofm.assignments.manage',
    'shifts.read.own',
    'shifts.read.scope',
    'shifts.schedule',
    'shifts.start.own',
    'shifts.end.own',
    'shifts.correct',
    'shifts.approve',
    'handovers.read',
    'handovers.write',
    'handovers.acknowledge',
    'contacts.read',
    'contacts.write',
    'contacts.merge',
    'contacts.relate',
    'contacts.export',
    'contacts.erase',
    'operations.read',
    'operations.write',
    'quality.read.own',
    'quality.read.scope',
    'quality.write',
    'quality.publish',
    'sale-candidates.write',
    'sale-candidates.review',
  ],
  insights: [
    'metrics.read',
    'metrics.write',
    'metrics.revise',
    'metrics.approve',
    'analytics.production.read',
    'analytics.accounts.read',
    'analytics.content.read',
    'analytics.ofm.read',
    'analytics.team.read',
    'analytics.finance.read',
    'reports.read',
    'reports.create',
    'reports.share',
    'reports.schedule',
    'goals.read',
    'goals.write',
    'imports.create',
    'imports.commit',
    'exports.create',
    'exports.download',
  ],
  finance: [
    'finance.read',
    'finance.create',
    'finance.submit',
    'finance.post',
    'finance.reverse',
    'finance.allocate',
    'finance.close-period',
    'finance.manage',
    'settlements.create',
    'settlements.confirm',
    'settlements.reverse',
    'budgets.read',
    'budgets.write',
    'budgets.approve',
    'compensation.rules.read',
    'compensation.rules.write',
    'compensation.rules.approve',
    'compensation.runs.read',
    'compensation.runs.calculate',
    'compensation.runs.approve',
    'compensation.own.read',
    'payments.record',
    'finance.documents.read',
  ],
  automation: [
    'automations.read',
    'automations.create',
    'automations.edit',
    'automations.enable',
    'system.jobs.read',
    'system.jobs.retry',
    'backups.status.read',
    'retention.manage',
    'custom-fields.manage',
    'templates.manage',
    'trash.purge',
  ],
} as const;

export type PermissionGroup = keyof typeof PERMISSION_GROUPS;
export type Permission = (typeof PERMISSION_GROUPS)[PermissionGroup][number];

export const ALL_PERMISSIONS: readonly Permission[] = Object.values(PERMISSION_GROUPS).flat() as Permission[];
export const isPermission = (p: string): p is Permission => (ALL_PERMISSIONS as readonly string[]).includes(p);

/**
 * Sensitive permissions are never implied by broader grants and are checked separately
 * (finance, OFM contacts, restricted media, exports). Only an Owner may grant `finance.*`.
 */
export const SENSITIVE_PREFIXES = [
  'finance.',
  'settlements.',
  'budgets.',
  'compensation.',
  'payments.',
  'contacts.',
  'assets.restricted.',
  'exports.',
  'analytics.finance.',
] as const;

export const isSensitivePermission = (p: string): boolean => SENSITIVE_PREFIXES.some((prefix) => p.startsWith(prefix));

/** Permissions only an Owner can grant to others. */
export const OWNER_ONLY_GRANTABLE: readonly string[] = [
  'finance.manage',
  'ownership.transfer',
  'trash.purge',
];

export const isFinancePermission = (p: string): boolean =>
  ['finance.', 'settlements.', 'budgets.', 'compensation.', 'payments.', 'analytics.finance.'].some((prefix) =>
    p.startsWith(prefix),
  ) && p !== 'compensation.own.read';
