import type { ScopeType } from '@castlane/domain';
import { ALL_PERMISSIONS, type Permission } from './permissions';

export interface RolePreset {
  key: string;
  name: string;
  description: string;
  defaultScopeType: ScopeType;
  permissions: Permission[];
  isProtected?: boolean;
}

const own: Permission[] = ['time.read.own', 'time.write.own', 'knowledge.read', 'knowledge.acknowledge', 'compensation.own.read'];

const adminExcluded = (p: string) =>
  p.startsWith('finance.') ||
  p.startsWith('settlements.') ||
  p.startsWith('budgets.') ||
  (p.startsWith('compensation.') && p !== 'compensation.own.read') ||
  p === 'payments.record' ||
  p === 'analytics.finance.read' ||
  p.startsWith('contacts.') ||
  p === 'assets.restricted.read' ||
  p === 'ownership.transfer' ||
  p === 'trash.purge';

const productionLead: Permission[] = [
  'directions.read',
  'projects.read',
  'projects.create',
  'projects.update',
  'projects.archive',
  'project.members.manage',
  'characters.read',
  'characters.write',
  'characters.approve',
  'series.read',
  'series.write',
  'accounts.read',
  'accounts.write',
  'accounts.assign',
  'accounts.archive',
  'references.read',
  'references.write',
  'content.read',
  'content.create',
  'content.edit',
  'content.upload',
  'content.submit',
  'content.approve',
  'content.archive',
  'tasks.read',
  'tasks.create',
  'tasks.edit',
  'tasks.assign',
  'tasks.complete',
  'tasks.reopen',
  'time.read.scope',
  'time.approve',
  'workload.read',
  'workload.manage',
  'publications.read',
  'publications.write',
  'publications.confirm',
  'publications.correct',
  'campaigns.read',
  'campaigns.write',
  'experiments.read',
  'experiments.write',
  'partners.read',
  'partners.write',
  'deals.read',
  'deals.write',
  'incidents.read',
  'incidents.write',
  'assets.read',
  'assets.upload',
  'assets.download',
  'assets.link',
  'assets.archive',
  'knowledge.write',
  'knowledge.publish',
  'metrics.read',
  'metrics.write',
  'metrics.revise',
  'analytics.production.read',
  'analytics.accounts.read',
  'analytics.content.read',
  'analytics.team.read',
  'reports.read',
  'reports.create',
  'reports.share',
  'goals.read',
  'goals.write',
  'imports.create',
  'exports.create',
  'exports.download',
  'members.read',
  'workspace.read',
];

export const ROLE_PRESETS: RolePreset[] = [
  {
    key: 'owner',
    name: 'Owner',
    description: 'All work modules, configuration, finance and ownership. Cannot bypass audit or domain rules.',
    defaultScopeType: 'workspace',
    permissions: [...ALL_PERMISSIONS],
    isProtected: true,
  },
  {
    key: 'admin',
    name: 'Admin',
    description: 'Team, settings, operational modules and audit. Finance, OFM contacts and restricted media need explicit grants.',
    defaultScopeType: 'workspace',
    permissions: ALL_PERMISSIONS.filter((p) => !adminExcluded(p)),
  },
  {
    key: 'direction_lead',
    name: 'Direction Lead',
    description: 'Projects, team assignments, production, schedules, scoped analytics and reviews in assigned directions.',
    defaultScopeType: 'direction',
    permissions: [
      ...own,
      ...productionLead,
      'ofm.overview.read',
      'ofm.assignments.manage',
      'shifts.read.scope',
      'shifts.schedule',
      'shifts.approve',
      'handovers.read',
      'operations.read',
      'quality.read.scope',
      'analytics.ofm.read',
      'templates.manage',
    ],
  },
  {
    key: 'project_lead',
    name: 'Project Lead',
    description: 'Project settings, tasks, content, accounts, approvals and scoped reports in assigned projects.',
    defaultScopeType: 'assigned_projects',
    permissions: [...own, ...productionLead.filter((p) => p !== 'projects.create' && p !== 'workload.manage')],
  },
  {
    key: 'producer',
    name: 'Producer',
    description: 'Briefs, production planning, versions and task assignment. No final approval of own work, no finance.',
    defaultScopeType: 'assigned_projects',
    permissions: [
      ...own,
      'projects.read',
      'directions.read',
      'members.read',
      'characters.read',
      'characters.write',
      'series.read',
      'series.write',
      'accounts.read',
      'references.read',
      'references.write',
      'content.read',
      'content.create',
      'content.edit',
      'content.upload',
      'content.submit',
      'tasks.read',
      'tasks.create',
      'tasks.edit',
      'tasks.assign',
      'tasks.complete',
      'tasks.reopen',
      'workload.read',
      'publications.read',
      'campaigns.read',
      'experiments.read',
      'assets.read',
      'assets.upload',
      'assets.download',
      'assets.link',
      'metrics.read',
    ],
  },
  {
    key: 'creator',
    name: 'Creator',
    description: 'Own tasks, versions, comments and time in assigned projects.',
    defaultScopeType: 'assigned_projects',
    permissions: [
      ...own,
      'projects.read',
      'characters.read',
      'series.read',
      'references.read',
      'content.read',
      'content.upload',
      'content.submit',
      'tasks.read',
      'tasks.edit',
      'tasks.complete',
      'assets.read',
      'assets.upload',
      'assets.download',
      'assets.link',
    ],
  },
  {
    key: 'publisher',
    name: 'Publisher',
    description: 'Plan and confirm publications, enter metrics and use approved files for assigned accounts.',
    defaultScopeType: 'assigned_accounts',
    permissions: [
      ...own,
      'accounts.read',
      'publications.read',
      'publications.write',
      'publications.confirm',
      'content.read',
      'assets.read',
      'assets.download',
      'metrics.read',
      'metrics.write',
      'tasks.read',
      'tasks.edit',
      'tasks.complete',
    ],
  },
  {
    key: 'ofm_manager',
    name: 'OFM Manager',
    description: 'Own shifts, handovers, permitted contacts, operations and sale candidates on assigned accounts.',
    defaultScopeType: 'assigned_accounts',
    permissions: [
      ...own,
      'accounts.read',
      'ofm.overview.read',
      'shifts.read.own',
      'shifts.start.own',
      'shifts.end.own',
      'handovers.read',
      'handovers.write',
      'handovers.acknowledge',
      'contacts.read',
      'contacts.write',
      'operations.read',
      'operations.write',
      'sale-candidates.write',
      'quality.read.own',
      'tasks.read',
      'tasks.create',
      'tasks.edit',
      'tasks.complete',
      'content.create',
      'metrics.read',
    ],
  },
  {
    key: 'ofm_supervisor',
    name: 'OFM Supervisor',
    description: 'Schedules, assignments, report approval, quality and operational analytics for assigned projects/accounts.',
    defaultScopeType: 'assigned_projects',
    permissions: [
      ...own,
      'projects.read',
      'accounts.read',
      'members.read',
      'ofm.overview.read',
      'ofm.assignments.manage',
      'shifts.read.own',
      'shifts.read.scope',
      'shifts.schedule',
      'shifts.correct',
      'shifts.approve',
      'handovers.read',
      'handovers.write',
      'handovers.acknowledge',
      'contacts.read',
      'contacts.write',
      'contacts.merge',
      'operations.read',
      'operations.write',
      'quality.read.scope',
      'quality.write',
      'quality.publish',
      'sale-candidates.write',
      'sale-candidates.review',
      'analytics.ofm.read',
      'metrics.read',
      'metrics.write',
      'tasks.read',
      'tasks.create',
      'tasks.edit',
      'tasks.assign',
      'tasks.complete',
      'content.create',
      'reports.read',
      'reports.create',
      'incidents.read',
      'incidents.write',
    ],
  },
  {
    key: 'analyst',
    name: 'Analyst',
    description: 'Metrics, correction review, reports and goals for granted scopes.',
    defaultScopeType: 'workspace',
    permissions: [
      ...own,
      'projects.read',
      'directions.read',
      'accounts.read',
      'content.read',
      'publications.read',
      'campaigns.read',
      'experiments.read',
      'experiments.write',
      'metrics.read',
      'metrics.write',
      'metrics.revise',
      'metrics.approve',
      'analytics.production.read',
      'analytics.accounts.read',
      'analytics.content.read',
      'analytics.team.read',
      'reports.read',
      'reports.create',
      'reports.share',
      'reports.schedule',
      'goals.read',
      'goals.write',
      'imports.create',
      'imports.commit',
      'exports.create',
      'exports.download',
    ],
  },
  {
    key: 'finance_manager',
    name: 'Finance Manager',
    description: 'Ledger, reconciliation, budgets, compensation calculation and approval within granted finance scopes.',
    defaultScopeType: 'workspace',
    permissions: [
      ...own,
      'projects.read',
      'directions.read',
      'accounts.read',
      'campaigns.read',
      'deals.read',
      'partners.read',
      'members.read',
      'finance.read',
      'finance.create',
      'finance.submit',
      'finance.post',
      'finance.reverse',
      'finance.allocate',
      'finance.close-period',
      'settlements.create',
      'settlements.confirm',
      'settlements.reverse',
      'budgets.read',
      'budgets.write',
      'budgets.approve',
      'compensation.rules.read',
      'compensation.rules.write',
      'compensation.rules.approve',
      'compensation.runs.read',
      'compensation.runs.calculate',
      'compensation.runs.approve',
      'payments.record',
      'finance.documents.read',
      'analytics.finance.read',
      'sale-candidates.review',
      'reports.read',
      'reports.create',
      'imports.create',
      'imports.commit',
      'exports.create',
      'exports.download',
    ],
  },
  {
    key: 'contractor',
    name: 'Contractor',
    description: 'Brief, attachments, task state and own uploads/comments for explicitly assigned objects only.',
    defaultScopeType: 'assigned_object',
    permissions: ['tasks.read', 'tasks.edit', 'tasks.complete', 'content.upload', 'assets.read', 'assets.upload', 'assets.download', 'time.read.own', 'time.write.own'],
  },
  {
    key: 'viewer',
    name: 'Viewer',
    description: 'Read ordinary data in the granted scope. No changes, exports or sensitive data.',
    defaultScopeType: 'workspace',
    permissions: [
      'directions.read',
      'projects.read',
      'characters.read',
      'series.read',
      'accounts.read',
      'references.read',
      'content.read',
      'tasks.read',
      'publications.read',
      'campaigns.read',
      'experiments.read',
      'partners.read',
      'deals.read',
      'assets.read',
      'knowledge.read',
      'knowledge.acknowledge',
      'metrics.read',
      'goals.read',
      'reports.read',
      'workload.read',
      'analytics.production.read',
      'analytics.accounts.read',
      'analytics.content.read',
    ],
  },
];

export const rolePresetByKey = (key: string): RolePreset | undefined => ROLE_PRESETS.find((r) => r.key === key);
