import { registerLabels } from '@/lib/labels';

/** English labels for platform enum values (dictionary keys, ready for localisation). */
registerLabels({
  notificationView: { unread: 'Unread', all: 'All', archived: 'Archived' },
  notificationEvent: {
    'review.requested': 'Review requested',
    'review.changes_requested': 'Changes requested',
    'task.assigned': 'Task assigned',
    'publication.due': 'Publication due',
    'metrics.update_needed': 'Metrics update needed',
    'shift.report_awaiting_review': 'Shift report awaiting review',
    'payment.recorded': 'Payment recorded',
    'incident.assigned': 'Incident assigned',
    'security.new_sign_in': 'Security alert',
  },
  importState: {
    uploaded: 'Checking file',
    parsed: 'Ready to map',
    validating: 'Validating',
    validated: 'Validated',
    needs_revalidation: 'Needs Revalidation',
    committing: 'Importing',
    committed: 'Imported',
    failed: 'Failed Without Changes',
    cancelled: 'Cancelled',
    undone: 'Undone',
  },
  exportState: { queued: 'Queued', running: 'Generating', completed: 'Ready', failed: 'Failed', cancelled: 'Cancelled', expired: 'Expired', deleted: 'File deleted' },
  duplicatePolicy: { skip: 'Skip existing', revise_existing: 'Revise existing (only provided fields)', error: 'Report as error' },
  classification: { normal: 'Normal', private: 'Private', finance: 'Finance', ofm: 'OFM' },
  changeSource: { ui: 'UI', api: 'API', import: 'Import', automation: 'Automation', system: 'System' },
  auditSensitivity: { normal: 'Normal', finance: 'Finance', ofm: 'OFM', security: 'Security' },
  actorKind: { member: 'Member', system: 'System', api_key: 'API key', support: 'Support' },
  incidentState: { open: 'Open', investigating: 'Investigating', resolved: 'Resolved' },
  incidentKind: { operational: 'Operational', system: 'System' },
  jobPool: { light: 'Light', data: 'Data', media: 'Media' },
  mailStatus: { queued: 'Queued', sent: 'Sent', failed: 'Failed' },
  backupStatus: { running: 'Running', succeeded: 'Succeeded', failed: 'Failed' },
  severity: { low: 'Low', medium: 'Medium', high: 'High', critical: 'Critical' },
  templateKind: { task: 'Task', content: 'Content', checklist: 'Checklist', quality_rubric: 'Quality Rubric' },
  templateStatus: { draft: 'Draft', published: 'Published', disabled: 'Disabled' },
  templateVersionState: { draft: 'Draft', published: 'Published', disabled: 'Withdrawn' },
  customFieldType: {
    short_text: 'Short Text',
    long_text: 'Long Text',
    number: 'Number',
    date: 'Date',
    datetime: 'Date & Time',
    single_select: 'Single Select',
    multi_select: 'Multi Select',
    checkbox: 'Checkbox',
    url: 'URL',
    member_reference: 'Member Reference',
  },
  jobState: { queued: 'Queued', running: 'Running', succeeded: 'Succeeded', failed: 'Failed', dead: 'Dead-lettered', cancelled: 'Cancelled' },
});

export {};
